### ISSUE TITLE
containerboot does not shut down cleanly when SIGTERM received

### ISSUE THREAD

**Issue by irbekrm** [tailscale/tailscale#10090]
### What is the issue?

When [containerboot](https://github.com/tailscale/tailscale/tree/main/cmd/containerboot) container receives a SIGTERM/SIGINT signal, it does not shut down cleanly, instead the container exits with an error, which means that if tailscale is used as a sidecar to a [Kubernetes Job](https://kubernetes.io/docs/concepts/workloads/controllers/job/) or a similar resource, it will cause the Job to fail even if the 'main' process exited with success. 

This happens because containerboot's [watcher](https://github.com/tailscale/tailscale/blob/v1.52.0/cmd/containerboot/main.go#L309-L387) does not listen on OS signals. If a SIGTERM is received, it will cause tailscaled to exit [here](https://github.com/tailscale/tailscale/blob/v1.52.0/cmd/containerboot/main.go#L479-L483) at which point [the watcher will receive an error](https://github.com/tailscale/tailscale/blob/v1.52.0/cmd/containerboot/main.go#L228) and cause the containerboot to exit with an error.

### Steps to reproduce

- set up a Kubernetes cluster
- create an [API token](https://tailscale.com/kb/1252/key-secret-management/?q=auth%20token#api-access-tokens)
- create a `Secret` with the API token `kubectl create secret generic tailscale-auth --from-literal=TS_AUTHKEY=<API token>`
- apply a Kuberentes Job with a main container that sleeps for 5s, then sends SIGTERM to  containerboot:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: tailtest
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      shareProcessNamespace: true
      containers:
      - name: nettools
        image: alpine:3.18
        env:
        command: ["/bin/sh"]
        args: ["-c", "sleep 10; pkill /usr/local/bin/containerboot"]
      - name: tailscale
        image: tailscale/tailscale
        env:
        - name: TS_KUBE_SECRET
          value: ""
        - name: TS_STATE_DIR
          value: "/tmp/ts"
        - name: TS_USERSPACE
          value: "false"
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
```
Observe that Job  ends up in a failed state an error [from containerboot]() in tailscale container logs:
```
...
boot: 2023/11/02 18:33:33 failed to read from tailscaled: EOF
...
```

### OS version

Kubernetes

### Tailscale version

v1.52.0
