### ISSUE TITLE
k8s-operator api proxy: remote error: tls: internal error

### ISSUE THREAD

**Issue by boomam** [tailscale/tailscale#10127]
### What is the issue?

Following the process for the kube-proxy functionality [here](https://tailscale.com/kb/1236/kubernetes-operator/#configuring-the-api-server-proxy), every step works until `kubectl get pods`, where the following error output is generated -  
```
E1105 09:55:32.633129   55472 memcache.go:265] couldn't get current server API group list: Get "https://tailscale-operator.XXXX.ts.net/api?timeout=32s": remote error: tls: internal error
E1105 09:55:34.266489   55472 memcache.go:265] couldn't get current server API group list: Get "https://tailscale-operator.XXXX.ts.net/api?timeout=32s": remote error: tls: internal error
E1105 09:55:34.973559   55472 memcache.go:265] couldn't get current server API group list: Get "https://tailscale-operator.XXXX.ts.net/api?timeout=32s": remote error: tls: internal error
E1105 09:55:35.708324   55472 memcache.go:265] couldn't get current server API group list: Get "https://tailscale-operator.XXXX.ts.net/api?timeout=32s": remote error: tls: internal error
E1105 09:55:36.529173   55472 memcache.go:265] couldn't get current server API group list: Get "https://tailscale-operator.XXXX.ts.net/api?timeout=32s": remote error: tls: internal error
Unable to connect to the server: remote error: tls: internal error
```

### Steps to reproduce

Follow steps [here](https://tailscale.com/kb/1236/kubernetes-operator/#configuring-the-api-server-proxy), then run any kubectl command, in this example, 'kubectl get pods'.

### Are there any recent changes that introduced the issue?

None.

### OS

macOS

### OS version

Sonoma 14.1

### Tailscale version

1.50.1

### Bug report

BUG-6984ad9c274d166d760a649fec631d5592251cf016784f2db8dac41ab06d616b-20231105150327Z-c70b79c357e70f49

**Comment by boomam** [comment]
Looking into the logs for the tailscale-operator log, i see this error - 
`2023/11/05 15:10:30 http: TLS handshake error from 1.2.3.4:54428: 500 Internal Server Error: SetDNS "_acme-challenge.tailscale-operator.XXXX.ts.net" => "8-ZPLdwe2QnJY1Y4xCt4kab26874Mczg_DNH7HDgkpMfnUNo": set-dns response: 400 Bad Request, domain does not have HTTPS enabled`.   
Could this be as i have "HTTPS Certificates" off in my tailscale config perhap?

**Comment by irbekrm** [comment]
Have you enabled https? https://tailscale.com/kb/1153/enabling-https/?q=enable%20https

**Comment by boomam** [comment]
> Have you enabled HTTPS? https://tailscale.com/kb/1153/enabling-https/?q=enable%20https

Yes.

**Comment by irbekrm** [comment]
> Looking at the kubectl config, it appears to have created the relevant details i would expect to see, but the 'auth' appears to be trying to passthrough the machine name, instead of my TS username - which is a bit wierd.

I missed this part in your description. That'll probably because the tailnet node you are running the commands from is [tagged](https://tailscale.com/kb/1068/acl-tags/)- is that the case? If you are running from a tagged node, the apiserver proxy uses node name rather than user name to authenticate to kube apiserver and you should create RBAC for the tags, not for your username, see https://tailscale.com/kb/1236/kubernetes-operator/#enabling-tagged-nodes-to-authenticate-using-the-api-server-proxy

Let us know if this worked.

**Comment by boomam** [comment]
> Let us know if this worked.

It does not, no.

Role binding yaml  
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-operator-tag-k8s-users
  namespace: tailscale-system
subjects:
- kind: Group
  name: "tag:k8s-users"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```
(Applied with kubectl -f).

Then `kubectl create clusterrolebinding --clusterrole cluster-admin --group "tailscale-operator-tag-k8s-users" tag-k8s-users` was ran successfully.

Logged into test computer, activated tailscale, switched context, tried 'kubectl get pods -A', same error as before.


To ask - are we able to submit content to the docs to improve them?  
The reason being is that there's a few bits of missing content, this topic section is a good example.   
Some areas list explicit example yaml/steps, whereas others list just an excerpt or comment. Would be much more complete and idiot proof to have the same consistency throughout.

**Comment by irbekrm** [comment]
Our docs are private, but suggestions are very welcome. The operator docs do need some love- it's on our list.

**Comment by boomam** [comment]
> In your case that'll be the `laptop.XXXX.ts.net` from logs you pasted in.

Sure - to be exact, you are suggesting - 
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-operator-laptop.XXXX.ts.net
  namespace: tailscale-system
subjects:
- kind: Group
  name: "laptop.XXXX.ts.net"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```
Followed by `kubectl create clusterrolebinding --clusterrole cluster-admin --group "tailscale-operator-laptop.XXXX.ts.net" laptop.XXXX.ts.net`  
&nbsp;  
Correct?

> Our docs are private, but suggestions are very welcome. The operator docs do need some love- it's on our list.

Great! Is there a place we can submit?
I'd like to update/suggest this particular topic with my notes thus far. :)

**Comment by irbekrm** [comment]
That should be a Clusterrolebinding for a user. It should be just `kubectl create clusterrolebinding --user <your laptop's tailnet FQDN> clusterrole cluster-admin <some name>` - that should work as long as the FQDN is correct and Clusterrole `cluster-admin` exists.
(I am traveling today, but will double check when I have a computer).
With regards to suggestions, just here would be fine - and much appreciated:)

**Comment by boomam** [comment]
Unfortunately, the syntax on the example doesn't work. 
I tried working it through using other CRB's and similar, and those work (as direct connections), so its defiantly an issue either with the operator, TS itself, or associated syntax from what i can tell thus far.  
&nbsp;  
As an alternative, is there a way to force the connection to _not_ use the machine name and instead the logged in TS user?

**Comment by irbekrm** [comment]
Hi @boomam, sorry for the late reply, I am at Kubecon at the moment.

Yes, the doc is confusing I'll see if I can fix it today or over the weekend.

The `tailscale-auth-proxy` ClusterRole and ClusterRoleBinding are for the operator to be able to function as an impersonating proxy for any tailnet users. You only need to apply those once for the operator. If you are installing via helm, they will get applied if you set [`.apiServerProxyConfig.mode`](.apiServerProxyConfig.mode) to true.
If you are not installing via helm then you have to apply the manifests from [here](https://github.com/tailscale/tailscale/blob/ed1b935238a7c6cce3aa4865aa13181eb679361a/cmd/k8s-operator/deploy/manifests/authproxy-rbac.yaml). These don't need to be modified.

And then when you are giving an individual tailnet user (identified by a username) or a group (identified by a tag) permissions to access resources in cluster, you create RBAC for that user or group.

For example, if you want to be able to get/list Pods in default namespace from a device that has some Tailscale ACL tags, you'd create RBAC like this:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: list-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata:
  name: ts-group
subjects:
- kind: Group
  name: "TAG"
  namespace: default 
roleRef:
  kind: Role 
  name: list-pods
  apiGroup: rbac.authorization.k8s.io
```

where TAG is a tag that your device is tagged with i.e
`tailscale status --json | jq -r '.Self.Tags[0]'`.

I have just tested this example from my machine that has two tags.

If you get a chance to test these yamls and let us know if that worked that would be awesome- I am not sure at the moment why it doesn't work for you, but I can't see how it could be related to creating a rolebinding for a group rather than a user.
