### ISSUE TITLE
FR: Support K8s Operator creating ephemeral auth keys

### ISSUE THREAD

**Issue by tylerj93** [tailscale/tailscale#10166]
### What are you trying to do?

I would like both the auth key created for the Kubernetes operator and for the proxy stateful sets to be ephemeral or at least support that as an option. We treat our Kubernetes clusters and services as disposable, and so it may happen that an instance of the tailscale operator is created and destroyed by automation, and it would be nice if the device didn't persist in the list of machines.

### How should we solve this?

Based on my surface-level understanding of the code, I think we would just need to set `Ephermal: true` (or make it configurable via env var) in these two parts of the operator code:

https://github.com/tailscale/tailscale/blob/main/cmd/k8s-operator/operator.go#L157
https://github.com/tailscale/tailscale/blob/main/cmd/k8s-operator/sts.go#L296

### What is the impact of not solving this?

We need to write our own method for cleaning up old k8s operator devices.

**Comment by irbekrm** [comment]
Thank you for opening the issue.

> proxy stateful sets

For the proxy statefulsets, the operator [deletes the device](https://github.com/tailscale/tailscale/blob/v1.54.1/cmd/k8s-operator/sts.go#L153-L165) associated with the proxy from the Tailscale control plane when the proxy is deleted. I assume this is sufficient for automation needs.

With regards to the operator itself, I agree that it would be preferable if the operator device was removed if the operator has been uninstalled.
We should at the same time also solve the problem where, if an instance of the operator has been deleted then redeployed, the new instance gets a different hostname because the original hostname is still held by the old operator device. Because of this, I am not sure whether ephemeral keys would be the best solution because the removal of the ephemeral keys does not happen 'immediately', so if for example, Tailscale operator is deleted from one cluster and redeployed to another one right after, the ephemeral key for the old operator will likely be still around so the new operator instance will get a different hostname (i.e `tailscale-operator-1`).

Perhaps we could externalize auth key creation into a standalone component that could add a [finalizer](https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/) to the operator `Deployment` and delete the associated device from the Tailscale control plane when the `Deployment` is being deleted.

This needs more thinking and potentially a design. It is somewhat related to how can we create auth keys for proxies if we want to allow external tools to scale the proxy Statefulset (multiple proxy replicas) cc @knyar

**Comment by SimonHaas** [comment]
I would love true ephemeral nodes via the operator as well.

I use github codespaces with minikube and the tailscale operator inside to work on applications and access them through my tailnet. When I am done working on a feature I simply delete the codespace with the whole cluster inside. Leaving me with orphaned nodes in tailscale which I have to remove manually.

**Comment by kbpersonal** [comment]
+1 please. Could we potentially get the fancy TS_EXPERIMENTAL_ flag with the necessary warnings/literature/flashing red lights in place to have a quick and dirty implementation of 'Ephemeral = true' for the operator?

**Comment by SimonHaas** [comment]
I have created a github action to remove orphaned nodes https://github.com/SimonHaas/tailscale-node-remover

**Comment by tatupesonen** [comment]
Very much need this functionality.

**Comment by Aubermean** [comment]
There is a PR open: https://github.com/tailscale/tailscale/pull/15508

**Comment by iypetrov** [comment]
If anyone's interested, here's a workaround I use: I create a Kubernetes Job (or a CronJob, if you want it scheduled) that automatically removes all stale machines.

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: remove-stale-devices
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: remove-stale-devices
          image: badouralix/curl-jq
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                DEVICES=$(curl -s -H "Authorization: Bearer $TAILSCALE_API_KEY" "https://api.tailscale.com/api/v2/tailnet/$TAILNET/devices")
                if [ -n "$DEVICES" ]; then
                  break
                fi
                echo "Retrying: Failed to fetch devices from Tailscale API..."
                sleep 15
              done
              NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
              echo "Current time in UTC: $NOW"
              echo "$DEVICES" | jq -r '.devices[] | "\(.id) \(.lastSeen)"' > /tmp/devices.txt
              if [ ! -s /tmp/devices.txt ]; then
                echo "Error: No devices found in API response or JQ processing failed"
                exit 1
              fi
              echo "Devices to process:"
              cat /tmp/devices.txt
              while read DEVICE_ID LAST_SEEN; do
                echo "Processing device $DEVICE_ID, last seen at $LAST_SEEN"
                if [ -n "$LAST_SEEN" ] && [ "$LAST_SEEN" \< "$NOW" ]; then
                  echo "Device $DEVICE_ID has not been seen since $LAST_SEEN, removing..."
                  curl -s -X DELETE -H "Authorization: Bearer $TAILSCALE_API_KEY" "https://api.tailscale.com/api/v2/device/$DEVICE_ID"
                fi
              done < /tmp/devices.txt
          env:
            - name: TAILSCALE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-cleanup-creds
                  key: ts-api-key
            - name: TAILNET
              valueFrom:
                secretKeyRef:
                  name: tailscale-cleanup-creds
                  key: tailnet
      restartPolicy: Never
```
