### ISSUE TITLE
FR: Kubernetes operator - integration with external ingress controllers

### ISSUE THREAD

**Issue by cterence** [tailscale/tailscale#10330]
### What are you trying to do?

I use the nginx ingress controller to handle all incoming traffic. I use [special annotations](https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/) on my ingresses to add an authentication layer.
If I want to expose my service using Tailscale Funnel, I have to use the tailscale ingress class, thus losing all nginx ingress controller features.

### How should we solve this?

Make the tailscale ingress class annotations, especially funnel, available on non-tailscale ingress class.
The behavior of the tailscale proxy pod should therefore be to forward all incoming traffic to the targeted ingress controller's service.

### What is the impact of not solving this?

Set both an ingress for creating the tailscale funnel redirecting to the nginx ingress controller service, and another ingress to instruct nginx to route traffic coming from the funnel to the target service.
While this workaround works, it complexifies the entire ingress configuration.

**Comment by samdyzon** [comment]
We would be very keen for this kind of functionality, but would also want to add the ability to allow the external ingress controller to handle TLS termination - this would also allow us to expose our services over tailscale with custom FQDN (rather then the magic DNS host name) and we can configure cert-manager to handle SSL certificate generation/renewal.

**Comment by ianhundere** [comment]
@cterence same predicament here. i'm currently only. using tailscale for one service, but ideally, it would be nice to have my public services exposed via tailscale instead of messing with my router "and" keep TLS termination via nginx.

**Comment by cterence** [comment]
Hey @ianhundere 

I have changed my implementation and in the meantime, scrapped my cluster momentarily, but here was the workaround I did :

Ingress for the nginx ingress controller
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: funnel
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: ingress-nginx-controller
      port:
        name: https
  tls:
    - hosts:
      - k8s-ingress
```

Ingress for argocd (value in helm chart)

```yaml
    ingress:
      enabled: true
      ingressClassName: nginx
      https: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        cert-manager.io/issue-temporary-certificate: "true"
        external-dns.alpha.kubernetes.io/target: terence.cloud
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          auth_request_set $auth_header $upstream_http_x_auth_request_email;
          proxy_set_header 'x-remote-user' $auth_header;
      pathType: ImplementationSpecific
      paths:
        - /argocd(/|$)(.*)
      hosts:
        - k8s-ingress.snow-delta.ts.net
```

As you can see, I used the `tailscale` class to create a single funnel ingress that redirects traffic to all my services, and create `nginx` class ingresses for all my other apps, but it didn't feel satisfying for multiple reasons :

* Being forced to use path based routing instead of subdomain routing, because you can have only one level of subdomain for your tailscale machines.
* Using the tailscale domain instead of my personal domain, which I knew was a limitation. I tried to circumvent it using a cloudflare worker as a reverse proxy but it was not great.

I would not recommend trying to replicate this if these things would bother you. You can explore my [gitops repo](https://github.com/cterence/homelab-gitops) if you want to see my implementation in more details.

**Comment by ianhundere** [comment]
> * Being forced to use path based routing instead of subdomain routing, because you can have only one level of subdomain for your tailscale machines.

ah yeah, this was definitely a deal breaker. i don't think some of my services like unifi-controller would accept that. may just wait it out for a better implementation then and just use tailscale for non-http services.

**Comment by Hobbit44** [comment]
I would like if this could be integrated as well. Im using a similar setup. I have internal and external ingress classes setup up with external dns on different providers, with certmanager for TLS. MetalLb handles the L2 address assignment for external IPs. Im having difficulty sorting the access becuase with the seperated ingress i think my DNS is resolving to a different IP than what tailscale is authorising. 

Whats the limitation that requires having to use a seperate Ingress? Could we not just use an annotation like for accessing services?

```
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "homeassistant"
  namespace: "home"
  annotations:
    "cert-manager.io/cluster-issuer": "default
    "tailscale.com/expose" = "true"
spec:
  ingressClassName: "internal"
  rules:
    - host: "hass.domain"
      http: 
        paths: 
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: "homeassistant"
                port:
                  number: 8123
  tls:
    - hosts:
      - "hass.domain",
      secretName: "homeassistant-tls"
```
