### ISSUE TITLE
Kubernetes-operator: tailscale.com/hostname is ignored when exposing via ingress

### ISSUE THREAD

**Issue by jbrinksmeier** [tailscale/tailscale#10493]
### What is the issue?

Hi there,
thanks a lot for creating tailscale.

I'm testing the kubernetes operator and struggle setting a custom machine name for an exposed ingress.
I try to give a custom name via the `tailscale.com/hostname` annotation, but this seems to be ignored as the machine appears with the usual `<k8s-namespace>-<k8s-servicename>` name in my admin console. Changing the machine name via the admin console works like a charm. I also set custom tags via `tailscale.com/tags` annotation which works as expected.

Thanks for looking into this, would be cool if tailscale.com/hostname annotation would work.

Best,
Johannes

### Steps to reproduce

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-tailscale
  namespace: tailscale
  annotations:
    tailscale.com/tags: "tag:k8s-test"
    tailscale.com/hostname: "website"
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: nginx-tailscale-service
                port:
                  name: web-service
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-tailscale-service
  namespace: tailscale
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - name: web-service
      protocol: TCP
      port: 80
      targetPort: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: tailscale
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
          name: web
```

**Expectation**
The machine appears with name `website` in the admin console and is accessible via https://website.my-tailnet.ts.net

**Actual Result**
The machine appears as `tailscale-nginx-tailscale-ingress` in the admin console and is accessible via https://tailscale-nginx-tailscale-ingress.my-tailnet.ts.net

As mentioned, I can rename the machine to `website` just fine.

### OS

Linux

### Tailscale version

1.55.73
