### ISSUE TITLE
k8s operator: support ExternalName Services

### ISSUE THREAD

**Issue by aviau** [tailscale/tailscale#10606]
### What are you trying to do?

When using the k8s operator, it does not look like it create proxies for annotated ExternalName services.

I used a service similar to this one:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "test-hostname"
spec:
  externalName: some.service.name
  type: ExternalName
```

While the documentation is unclear about if this is supported, I think it should!

**Comment by irbekrm** [comment]
Hi @aviau 

It is true that it does only support `ClusterIP` `Service`s. We set up proxy routing rules using the cluster IP address of the annotated `Service` and we do need an IP address for our proxy routing as we do it currently. Even if we can resolve the underlying IP address of the `.spec.externalName` there would be no way for us to observe if that has changed and reconfigure the proxy rules.

What is your use case for wanting to expose `ExternalName` `Service`s?

> While the documentation is unclear about if this is supported

Thanks for pointing out, we should improve that.

**Comment by aviau** [comment]
> What is your use case for wanting to expose ExternalName Services?

Our infrastructure runs in an AWS VPC, and while most things are hosted in k8s, we have services such as database that are accesible from the k8s cluster, but hosted outside of it in AWS managed services. It would be really simple for us to access them using tailscale by creating an ExternalName service that point to it.

> there would be no way for us to observe if that has changed and reconfigure the proxy rules.

Before you released the k8s operator, I built my own terraform module that would manage multiple tailscale proxies running in k8s. I worked around that problem by just killing the pod every x amount of time. If I was to build something "clean" I would build a supervisor process that:
- Resolves the domain every TTL
- Restart the service only when the IP changed.

This is my current ugly restart hack:
```bash
export TS_DEST_IP=$(getent hosts $${PROXY_DEST_HOST} | awk '{ print $1 }')

timeout $${PROXY_RESTART_TIMEOUT} /usr/local/bin/containerboot
```

I am curious. If there is no ExternalName support, what would be the next best way to setup proxies running in k8s that point to my database?

**Comment by maisem** [comment]
@aviau I wonder if this could be solved using an [app connector](https://tailscale.com/kb/1281/app-connectors) instead.

In that case you wouldn't need to create an ExternalName service, and instead would run the app connector inside your cluster and add the DNS name of your DB to the connector directly.

I haven't thought through it fully, but have a feeling that it might work.

**Comment by irbekrm** [comment]
FWIW, I played around with a private RDS instance accessible from the k8s cluster and the app connector and was able to get it working, steps in the details:
<details>
- set up ACLs and tags as per the [app connector docs](https://tailscale.com/kb/1281/app-connectors)
- create an [auth key](https://tailscale.com/kb/1085/auth-keys) tagged with `tag:connector`
- `kubectl create secret generic app-connector --from-literal=authkey=<auth key>`
- apply the following manifests to deploy app connector to the cluster:
```
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: connector 
spec:
  replicas: 1 # Only one replica is supported at time
  selector:
    matchLabels:
      app: connector 
  template:
    metadata:
      labels:
        app: connector 
    spec:
      serviceAccountName: connector 
      containers:
      - env:
        - name: TS_USERSPACE
          value: "false"
        - name: TS_AUTH_ONCE
          value: "true"
        - name: TS_KUBE_SECRET
          value: app-connector 
        - name: TS_HOSTNAME
          value: connector
        - name: TS_EXTRA_ARGS
          value: "--advertise-connector"
        - name: TS_DEBUG_FIREWALL_MODE
          value: auto
        image: tailscale/tailscale:v1.56.0
        imagePullPolicy: Always
        name: tailscale
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      initContainers:
      - args:
        - -c
        - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1
        command:
        - /bin/sh
        image: tailscale/tailscale:v1.54.0
        imagePullPolicy: IfNotPresent
        name: sysctler
        securityContext:
          privileged: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector 
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connector 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: connector 
subjects:
- kind: ServiceAccount
  name: connector 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: connector
```
</details>

Keen to hear if the flow would make sense for you.
We could potentially look into automating the flow a bit more by adding app connector to our [new Connector Custom Resource](https://github.com/tailscale/tailscale/pull/9505).

Out of interest, are you also using the [AWS Kubernetes controllers](https://aws.amazon.com/blogs/database/deploy-amazon-rds-databases-for-applications-in-kubernetes/) to create or manage those RDS instances? (I am just curious whether there is some resource in the cluster that already displays the connection endpoint for the database that could perhaps be integrated sometime in the future).
