### ISSUE TITLE
Under OpenShift - The k8s-operator fails to start with a permission denied on file creation

### ISSUE THREAD

**Issue by butler54** [tailscale/tailscale#10638]
### What is the issue?

Running the helm install as specified [here](https://tailscale.com/kb/1236/kubernetes-operator) results in the operator install results in a failure creating `/.config`. Forcing a run as root fixes the problem.

May be an issue related to: https://docs.openshift.com/container-platform/4.14/openshift_images/create-images.html#use-uid_create-images the fact that OCP randomly minted users

### Steps to reproduce

On Openshift either:
Run helm install by:
```
helm upgrade \
  --install \
  tailscale-operator \
  tailscale/tailscale-operator \
  --namespace=tailscale \
  --create-namespace \
  --set-string oauth.clientId=<OAauth client ID> \
  --set-string oauth.clientSecret=<OAuth client secret> \
  --wait
``` 
or using the manifest file. 

Using `oc get pod -n tailscale operator8` will show failures. Using the manifest file and forcing UID=0 e.g.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
      - env:
        - name: OPERATOR_HOSTNAME
          value: tailscale-operator
        - name: OPERATOR_SECRET
          value: operator
        - name: OPERATOR_LOGGING
          value: debug
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENABLE_CONNECTOR
          value: "false"
        - name: CLIENT_ID_FILE
          value: /oauth/client_id
        - name: CLIENT_SECRET_FILE
          value: /oauth/client_secret
        - name: PROXY_IMAGE
          value: tailscale/tailscale:stable
        - name: PROXY_TAGS
          value: tag:k8s
        - name: APISERVER_PROXY
          value: "false"
        - name: PROXY_FIREWALL_MODE
          value: auto
        image: tailscale/k8s-operator:stable
        imagePullPolicy: Always
        name: operator
        securityContext:
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - mountPath: /oauth
          name: oauth
          readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: operator
      volumes:
      - name: oauth
        secret:
          secretName: operator-oauth
```
Does work

### OS

Linux

### OS version

OpenShift 4.14 and corresponding RHCOS

### Tailscale version

1.56.0-1

### Bug report

NA
