### ISSUE TITLE
Access Denied Error when Fetching Certificate with Traefik and Tailscale

### ISSUE THREAD

**Issue by jpabbuehl** [tailscale/tailscale#10647]
### What is the issue?

**Background:* I'm attempting to set up Traefik with Tailscale as outlined in [this guide](https://tailscale.com/kb/1234/traefik-certificates), using the [Traefik Helm chart](https://github.com/traefik/traefik-helm-chart). I've mounted /var/run/tailscale from the host into the Traefik container to make tailscaled.sock available.

**Issue Description:** When I start the ingress with Tailscale as the TLS resolver, I encounter an 'access denied' error when fetching the certificate. However, running sudo tailscale cert master.XXX.ts.net on my host works fine. I'm not sure how to proceed further on tailscale's side. Here's the error message:

```
2023-12-19T13:46:47Z ERR github.com/traefik/traefik/v3/pkg/provider/tailscale/provider.go:249 > Unable to fetch certificate for domain "master.XXX.net" error="Access denied: cert access denied" providerName=myresolver.tailscale
```

**Expected vs. Actual Behavior:** I expected the certificate fetching process to complete without errors, but instead, I'm facing an access denial.

**Logs and Error Messages:** Full error log is included above. The issue seems related to this line in the Tailscale provider for Traefik relying on tailscale/tscert: [provider.go#L247](https://github.com/traefik/traefik/blob/0ee377bc9f036124b063e7abc3f0958d51ace5fb/pkg/provider/tailscale/provider.go#L247).

**Question:** Am I missing some authentication steps, or should I mount additional resources to allow proper authentication? Any guidance on debugging this permission issue would be greatly appreciated.

### Steps to reproduce

```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  repo: https://traefik.github.io/charts
  chart: traefik
  version: 26.0.0
  set:
    global.systemDefaultRegistry: ""
  valuesContent: |-
    image:
      tag: "v3.0.0-beta5"
    deployment:
      additionalVolumes:
      - name: tailscale-ipc
        hostPath:
          path: /var/run/tailscale
      initContainers:
      - name: adjust-tailscale-socket-permissions
        image: busybox
        command: ["sh", "-c", "chmod 666 /var/run/tailscale/tailscaled.sock"]
        securityContext:
          runAsNonRoot: false
          runAsGroup: 0
          runAsUser: 0
        volumeMounts:
          - name: tailscale-ipc
            mountPath: /var/run/tailscale
    additionalVolumeMounts:
    - name: tailscale-ipc
      mountPath: /var/run/tailscale
    experimental:
      plugins:
        sablier:
          moduleName: github.com/acouvreur/sablier
          version: v1.5.0
    http3:
        enabled: true
    rbac:
      enabled: true
    ports:
      websecure:
        tls:
          enabled: true
        http3:
          enabled: true
    podAnnotations:
      prometheus.io/port: "8082"
      prometheus.io/scrap: "true"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    additionalArguments:
    - '--certificatesresolvers.myresolver.tailscale=true'
    logs:
      general:
        level: DEBUG
```

### OS

Linux

### OS version

ubuntu 22.04 LTS

### Tailscale version

1.56.1

### Other software

k3s version v1.28.4+k3s2 (6ba6c1b6)
helm v3.10.1

### Bug report

BUG-1066bd97d5cd6880a4809b6419334c7686e7215611f9c07b447d301027a7bccc-20231219141045Z-49d21c16589fcf41
