### ISSUE TITLE
FR: Kubernetes operator: integrate Connector with ServiceCIDR resource for Service route exposure

### ISSUE THREAD

**Issue by irbekrm** [tailscale/tailscale#10683]
### What are you trying to do?

In Kubernetes 1.29 a new `ServiceCIDR`s resource was added, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1880-multiple-service-cidrs
`ServiceCIDR`s will contain the default `Service` CIDR allocated to a cluster as well as allows cluster admins to expand or change the range by creating additional `ServiceCIDR`s/deleting the default one.

We currently support exposing `Service` CIDR range creating a `Connector` custom resource with hardcoded CIDR range for which a Tailscale subnet router gets deployed in the cluster https://github.com/tailscale/tailscale/pull/9505

We could integrate the `Connector` with `ServiceCIDR`s to allow users to define that all `Service` CIDR ranges in cluster should be exposed without specifying the actual range, i.e 

```
apiVersion: tailscale.io/v1alpha1
kind: Connector
metadata:
  name: foo
spec:
  subnetRouter:
    serviceCIDRS:
      all: <set to true to expose all Service CIDR ranges via a subnet router>
      <maybe also allow passing Service CIDRs by name>
```

`ServiceCIDR` API is currently alpha and requires enabling the alpha `MultiCIDRServiceAllocator` feature gate, so this issue is a placeholder till it reaches GA in a sufficiently widely adopted Kubernetes version.
