### ISSUE TITLE
Debian ARM64 Package Broken: Exec format error

### ISSUE THREAD

**Issue by moloch--** [tailscale/tailscale#10705]
### What is the issue?

Cannot build docker container with Tailscale using Github Action's buildx for Linux/arm64 however the same build works fine with amd64:

`Error while loading /var/lib/dpkg/info/tailscale.postinst: Exec format error`

```
 #9 40.85 Setting up tailscale (1.56.1) ...
#9 40.86 Error while loading /var/lib/dpkg/info/tailscale.postinst: Exec format error
#9 40.86 dpkg: error processing package tailscale (--configure):
#9 40.86  installed tailscale package post-installation script subprocess returned error exit status 1
#9 40.86 Processing triggers for libc-bin (2.36-9+deb12u3) ...
#9 40.98 Errors were encountered while processing:
#9 40.98  tailscale
#9 41.07 E: Sub-process /usr/bin/dpkg returned an error code (1)
#9 ERROR: process "/dev/.buildkit_qemu_emulator /bin/sh -c curl -fsSL https://tailscale.com/install.sh | sh" did not complete successfully: exit code: 100
```

### Steps to reproduce

Dockerfile:

```Dockerfile
FROM debian:bookworm-slim

# Tailscale
RUN curl -fsSL https://tailscale.com/install.sh | sh
```

Github Action:
```
      - name: Build and Load
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          platforms: linux/arm64
          push: false
          load: true
          tags: tailscale-subnet-router
          cache-from: type=gha
          cache-to: type=gha,mode=max

```

### OS

Linux

### OS version

Debian 12

### Tailscale version

1.56

### Other software

Github Actions, Docker
