### ISSUE TITLE
FR: Document how to authenticate in a K8s Cluster with apiServerProxyConfig.mode set to "noauth"

### ISSUE THREAD

**Issue by janus-reith** [tailscale/tailscale#10739]
### What are you trying to do?

I'm trying to perform kubectl operations in my cluster using its Tailscale https-enabled MagicDNS domain instead of directly connecting to it by IP (Restricted by external Firewall to my IP).
As so far I was unable to sort out some security concerns I have with the Auth Proxy the Tailscale Operator provides I would rather not like to use it[^1][^2].

Instead, I'd like to use the existing user I have defined with `client-certificate-data` and `client-key-data`
So far I however was unable to authenticate against my cluster using it in "noauth" mode, where it should just forward the requests.
First I just replaced the `server` in my kubeconfig which previously was https://SOMEIP:API-Port with https://clustername.tail1234a.ts.net
kubectl operations would now fail with:

```
Get "https://clustername.tail1234a.ts.net/version?timeout=5s": x509: certificate signed by unknown authority
Unable to connect to the server: tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Next I tried to get the CA from the cert generated for clustername.tail1234a.ts.net, base64 encode it and set it as `certificate-authority-data` in my kube config.
Now I'm stuck at:

```
I0104 16:02:16.558624   71094 versioner.go:58] the server has asked for the client to provide credentials
error: You must be logged in to the server (Unauthorized)
```

I'm unsure if there either is some dependency between `client-certificate-data`/`client-key-data` and `certificate-authority-data` which prevents this from working, or if the Tailscale Auth proxy strips Auth headers or something else that prevents this from adding up the way I expected to.

[^1]: It seems that if my tagged device has any cluster access granted, anything running on my machine including some arbitrary website using fetch could make authenticated requests against the API using its MagicDNS name. I might be wrong and there are some security measures in place that would prevent this. Also it might be unlikely that some third party even knows that MagicDNS name, but still a concern to me. Also there might be some part of the bigger picture of how this feature is intended to be used that I didn't get yet.
[^2]: If I understood the doc for the Tailscale Operator properly, it allows assigning certain system groups which do not require further setup within my cluster, potentially making the Tailscale ACL config a single point of failure for cluster access. Again, I didn't dive deep there yet and might be wrong.

### How should we solve this?

Document how to access a Cluster with the Tailscale Operator deployed with `apiServerProxyConfig.mode="noauth"`
I believe this to be a rather common usecase.

### What is the impact of not solving this?
I switched to using token-based authenticaton in the meantime. Using X.509 certificates like I would by default when connecting to a cluster seems to be more secure.

**Comment by irbekrm** [comment]
Hi @janus-reith 

We issue LetsEncrypt certs for the API server proxy (for the MagicDNS name of the operator). So generally you should not need to set `certificate-authority-data` in your kubeconfig- kubectl should trust the operator cert.

> I'm unsure if there either is some dependency between client-certificate-data/client-key-data and certificate-authority-data which prevents this from working

Did you issue your client certs via kube Certificates API? https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/
I have not tried to use the proxy with these certs- I will try to reproduce this. The noauth mode was originally aimed at clusters that have use an external auth provider, so I am not sure if anyone has tested it with kube client certs
https://github.com/tailscale/tailscale/issues/8317

I am not sure if there

**Comment by janus-reith** [comment]
>  I will try to reproduce this. The noauth mode was originally aimed at clusters that use an external auth provider, so I am not sure if anyone has tested it with kube client certs. #8317

Thank you!

> Did you issue your client certs via kube Certificates API?

I did not issue them manually but I assume that's where they are from. I took them from the kubeconfig created during the k3s installation script.

**Comment by jace-ys** [comment]
👋🏻 Any updates on this?

We are encountering a similar problem which is a blocker for us adopting the tailscale-operator as an API server proxy.

**Comment by wvell** [comment]
@jace-ys or @janus-reith  Did you fix this? I still get `error: You must be logged in to the server (Unauthorized)`.

I am also using client-certificates for authentication and would like to keep using that.

**Comment by wvell** [comment]
For anyone wondering how to "fix" this. I am not using the authproxy anymore. I have the following service and deployment in my config.

I am using a very simple tcp proxy to proxy all calls to the k8s api in my cluster.
To fix the insecure certificate errors i'm using https://kubernetes.default.svc as my server in the ~/.kube/config and i point kubernetes.default.svc to the tailscale ip of the service (ugly hack but it works).

```yaml
apiVersion: v1
kind: Service
metadata:
  name: tailscale-api
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - protocol: TCP
      port: 443           
      targetPort: 443    
  selector:
    app: tcp-proxy

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-proxy
  template:
    metadata:
      labels:
        app: tcp-proxy
    spec:
      containers:
        - name: tcp-proxy
          image: hpello/tcp-proxy:1.1.0
          args:
            - "kubernetes.default.svc"
            - "443"
          ports:
            - containerPort: 443
```

~/.kube/config
```yml
- cluster:
    certificate-authority-data: ........
    server: https://kubernetes.default.svc
  name: tailscale-prod
```

/etc/hosts
```
100....(the ip to the service)  kubernetes.default.svc
```

**Comment by east4ming** [comment]
I have the same problem, I am installing via k3s, my kubeconfig looks like this, please write a document to guide me on exactly what I should do to achieve a successful login.

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    server: https://192.168.1.10:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: xxx
    client-key-data: xxx
```
