### ISSUE TITLE
FR: K8s Operator: add tailscale.com & custom labels to pod template spec

### ISSUE THREAD

**Issue by JJGadgets** [tailscale/tailscale#10854]
### What are you trying to do?

I'd like to have predictable labels on the spawned Tailscale StatefulSet pods, for use with network policies and other label-matching operations.

### How should we solve this?

Supporting both of the below solutions would be ideal, but just one for now is also fine.

1. Propagating the current tailscale.com StatefulSet labels to the pod template spec so spawned pods also get the labels. This is useful for having network policies that allow traffic based on a specific app, e.g. network policy to allow ingress traffic to Minecraft pods.

e.g:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    tailscale.com/managed: "true"
    tailscale.com/parent-resource: minecraft
    tailscale.com/parent-resource-ns: minecraft
    tailscale.com/parent-resource-type: svc
...
spec:
  template:
    metadata:
      labels:
        tailscale.com/managed: "true"
        tailscale.com/parent-resource: minecraft
        tailscale.com/parent-resource-ns: minecraft
        tailscale.com/parent-resource-type: svc
```

3. Allowing setting custom labels on the pod template in the Helm chart. This is useful for e.g. Istio sidecar, Multus NetworkAttachments, etc.

e.g:
```yaml
apiVersion: apps/v1
kind: StatefulSet
...
spec:
  template:
    metadata:
      labels:
        egress.home.arpa/internet: "allow"
```

### What is the impact of not solving this?

I am forced to allow all the Tailscale pods to access all pods that are exposed via Tailscale, e.g. my Minecraft Tailscale pod can access my ingress-nginx pods.

I'd like to make my network policies more specific, to only allow an app's Tailscale pod to access only said app pod and no other pods.
