### ISSUE TITLE
FR: Support Wildcard entries for tailscale proxy

### ISSUE THREAD

**Issue by os14** [tailscale/tailscale#10920]
### What are you trying to do?

It's frustrating to add new UIs to the path based system of routing UIs with ingress-nginx currently.
e.g. http://cluster1/prometheus and http://cluster1/grafana

### How should we solve this?

We've went for path based routing because it was the easiest to achieve. Tailscale did not support a way of defining a wildcard entry routing to a single nginx and for nginx to take it from there.

when registering the talscale-proxy as "cluster1" we want to be able to accept *.cluster1 requests to the tailscale proxy.

### What is the impact of not solving this?

Instead, we should offer something that does not require from the specific UI serving the backend to support base path routing as it requires some work and it not always support.
See example in Ceph, instead of:

```
rook-ceph-cluster:
    dashboard:
      urlPrefix: /ceph
  ingress:
    dashboard:
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /ceph/$2
        nginx.ingress.kubernetes.io/configuration-snippet: |
          if ($uri = "/ceph") { return 302 /ceph/; }
      host:
        name: cluster1
        path: "/ceph(/|$)(.*)"
```
We would have:
```
rook-ceph-cluster:
  ingress:
    dashboard:
      host:
        name: ceph.cluster1
```
