### ISSUE TITLE
FR: Configurable MTU for TCP MSS clamping when using k8s-operator

### ISSUE THREAD

**Issue by clrxbl** [tailscale/tailscale#11002]
### What are you trying to do?

I'm trying to migrate from my own DIY Tailscale operator to the official one, but running into an issue with network connectivity.

I need to clamp MSS to a specific MTU size (e.g. 1280) otherwise Tailscale seems to be currently clamping onto MTU 9000 which seems to be breaking HTTPS connections

### How should we solve this?

The ability to define a configurable MTU size in the Helm chart's proxyConfig, disabling clamping onto PMTU

### What is the impact of not solving this?

I can work around this by forcing our Kubernetes CNI to use an MTU size that fits within Tailscale's 1280, disabling jumbo frames temporarily, but this is not ideal.

**Comment by knyar** [comment]
Any thoughts why `clamp-mss-to-pmtu` might be clamping to a value that's too high? Any additional details you could share about your environment where this happens that would make it easier to reproduce?

**Comment by clrxbl** [comment]
> Any thoughts why [clamp-mss-to-pmtu](https://github.com/tailscale/tailscale/blob/b4b2ec780159f472af787224b7b1339ae5841346/util/linuxfw/iptables_runner.go#L312) might be clamping to a value that's too high? Any additional details you could share about your environment where this happens that would make it easier to reproduce?

The setup here is a baremetal Kubernetes cluster running Cilium, with 10Gbit NICs where the MTU is 9000 normally for jumbo frames.

**Comment by clrxbl** [comment]
I don't really write Go but I've forked Tailscale and jankily added what I needed for iptables at https://github.com/clrxbl/tailscale/commit/2441f172a9b182f08e732e29f1396e4575a10857

Clamping TCP MSS to 1280 solves my issues and makes the Tailscale operator usable again. Without this change, connections are either hanging on connecting (e.g. HTTPS connections) or just unusably slow.

**Comment by knyar** [comment]
Thanks for confirming that setting the MSS value manually addressed your issue. I think we'd want to avoid exposing this as a user-facing configuration parameter, instead improving the existing behaviour or determining the MSS value automatically.

Do you think you could please share the output of the following commands from the pod running Tailscale that required this change?
* `ip addr`
* `ip route show cache`
* `sysctl -a | grep mtu`

Thank you!

**Comment by clrxbl** [comment]
> Thanks for confirming that setting the MSS value manually addressed your issue. I think we'd want to avoid exposing this as a user-facing configuration parameter, instead improving the existing behaviour or determining the MSS value automatically.
> 
> Do you think you could please share the output of the following commands from the pod running Tailscale that required this change?
> 
> * `ip addr`
> * `ip route show cache`
> * `sysctl -a | grep mtu`
> 
> Thank you!

Sure thing.

```
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq state UNKNOWN group default qlen 500
    link/none
    inet 100.69.77.47/32 scope global tailscale0
       valid_lft forever preferred_lft forever
    inet6 fd7a:115c:a1e0::8745:4d2f/128 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::90ee:1993:783a:d025/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
53584: eth0@if53585: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
    link/ether b6:cd:db:a6:da:13 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.16.0.6/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::b4cd:dbff:fea6:da13/64 scope link
       valid_lft forever preferred_lft forever
/ # ip route show cache
/ # sysctl -a | grep mtu
sysctl: error reading key 'kernel.apparmor_display_secid_mode': Operation not permitted
sysctl: error reading key 'kernel.unprivileged_userns_apparmor_policy': Operation not permitted
net.ipv4.ip_forward_use_pmtu = 0
net.ipv4.ip_no_pmtu_disc = 0
net.ipv4.route.min_pmtu = 552
net.ipv4.route.mtu_expires = 600
net.ipv4.tcp_mtu_probe_floor = 48
net.ipv4.tcp_mtu_probing = 0
net.ipv6.conf.all.accept_ra_mtu = 1
net.ipv6.conf.all.mtu = 1280
sysctl: error reading key 'net.ipv6.conf.all.stable_secret': I/O error
net.ipv6.conf.default.accept_ra_mtu = 1
net.ipv6.conf.default.mtu = 1280
sysctl: error reading key 'net.ipv6.conf.default.stable_secret': I/O error
net.ipv6.conf.eth0.accept_ra_mtu = 1
net.ipv6.conf.eth0.mtu = 9000
sysctl: error reading key 'net.ipv6.conf.eth0.stable_secret': I/O error
net.ipv6.conf.lo.accept_ra_mtu = 1
net.ipv6.conf.lo.mtu = 65536
sysctl: error reading key 'net.ipv6.conf.lo.stable_secret': I/O error
net.ipv6.conf.tailscale0.accept_ra_mtu = 1
net.ipv6.conf.tailscale0.mtu = 1280
net.ipv6.route.mtu_expires = 600
```

**Comment by clrxbl** [comment]
I should clarify that clamping the tailscale0 interface MSS to a smaller MTU value doesn't resolve the issue. Instead I have to apply this rule onto the container's main network interface e.g.

```bash
iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -o eth0 -j TCPMSS --set-mss 1240
```

**Comment by knyar** [comment]
I don't have access to a bare metal cluster with jumbo frames, but I could not reproduce this on a GKE cluster with a higher MTU. E.g.:

```
2: eth0@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8896 qdisc noqueue state UP group default
    link/ether 32:ef:80:2d:64:80 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.44.0.11/24 brd 10.44.0.255 scope global eth0
       valid_lft forever preferred_lft forever
3: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 100.80.228.1/32 scope global tailscale0
       valid_lft forever preferred_lft forever
```

A TCP connection from the cluster into the tailnet gets its MSS correctly adjusted (from 8856 to 1240).

```
 # tcpdump -ni any port 8092
tcpdump: data link type LINUX_SLL2
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
15:12:58.836981 eth0  In  IP 10.44.0.7.59534 > 10.44.0.11.8092: Flags [S], seq 619223444, win 17712, options [mss 8856,sackOK,TS val 4008564504 ecr 0,nop,wscale 7], length 0
15:12:58.837012 tailscale0 Out IP 100.80.228.1.59534 > 100.99.113.119.8092: Flags [S], seq 619223444, win 17712, options [mss 1240,sackOK,TS val 4008564504 ecr 0,nop,wscale 7], length 0
```

Could you please share a bit more details about what feature of the operator you are using ([egress](https://tailscale.com/kb/1236/kubernetes-operator#cluster-egress), [ingress via a Service](https://tailscale.com/kb/1236/kubernetes-operator#loadbalancerclass) or [ingress via an Ingress resource](https://tailscale.com/kb/1236/kubernetes-operator#ingress-resource)) and about HTTPS client and server involved?

**Comment by clrxbl** [comment]
> Could you please share a bit more details about what feature of the operator you are using ([egress](https://tailscale.com/kb/1236/kubernetes-operator#cluster-egress), [ingress via a Service](https://tailscale.com/kb/1236/kubernetes-operator#loadbalancerclass) or [ingress via an Ingress resource](https://tailscale.com/kb/1236/kubernetes-operator#ingress-resource)) and about HTTPS client and server involved? Capturing MSS values of a connection (like I shared above) would be helpful too.

I use Ingress via a Service only currently.

> This is a bit odd - why is it necessary to clamp MSS to 1240 while egressing to eth0, which has mtu of 9000?
Honestly, not sure. But for some reason this has been my only solution to Tailscale networking issues. Without this, it seems to specifically break within any other Docker container.

Server is in this case ingress-nginx, Let's Encrypt TLS certificate handled by cert-manager & client is just curl.

If I curl something on the host, it seems to connect just fine. If I repeat the same within e.g. a Debian docker container, the connection breaks. Docker by default creates a network with 1500 MTU. Manually changing this to 1240 makes it work; so either I change it on every host to 1240 or I change it in the Tailscale operator to change the MTU for egress.

**Comment by knyar** [comment]
I could not reproduce this on a GKE cluster using [Dataplane V2](https://cloud.google.com/kubernetes-engine/docs/concepts/dataplane-v2), which I believe is based on Cilium. Are you able to share additional details about the cluster you are running this in that might help us reproduce the issue? Could you please share your Cilium configuration and the version of Cilium you are using?

**Comment by clrxbl** [comment]
> I could not reproduce this on a GKE cluster using [Dataplane V2](https://cloud.google.com/kubernetes-engine/docs/concepts/dataplane-v2), which I believe is based on Cilium. Are you able to share additional details about the cluster you are running this in that might help us reproduce the issue? At the minimum I think it would help to see your Cilium configuration and the version of Cilium you are using.

https://github.com/tailscale/tailscale/issues/11002#issuecomment-1921655988 describes my setup
My Cilium config/Helm values are:

```yaml
    devices: ["bond0.+", "tailscale0"]
    rollOutCiliumPods: true
    bandwidthManager:
      enabled: true
    hostFirewall:
      enabled: true
    nodePort:
      enabled: true
    nodeinit:
      enabled: true
      restartPods: true
    socketLB:
      enabled: true
      hostNamespaceOnly: true
    kubeProxyReplacement: true
    k8sServiceHost: cluster-endpoint
    k8sServicePort: 6443
    hubble:
      tls:
        auto:
          method: cronJob
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
      metrics:
        serviceMonitor:
          enabled: true
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - icmp
          - port-distribution
    hostPort:
      enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    ipv6:
      enabled: false
    bpf:
      hostRoutingLegacy: false
      masquerade: true
    l7Proxy: false
```
