### ISSUE TITLE
FR: is there any to authentication user of drep that installed tailscale not on same server?

### ISSUE THREAD

**Issue by joebnb** [tailscale/tailscale#11031]
### What are you trying to do?

for latency i hold up a self hosted a drep server in aliyun ecs for proxy traffic of my home server,after setup success i found that if others konw or scanned my ip and port they also can connect this server.

(the drep server and tailsscale installed in different server,one is in aliyun,one is in my home)

how to ensure that node only can serve only me or specified account.

**Comment by bradfitz** [comment]
Seems like you figured it out?

**Comment by joebnb** [comment]
> for latency i hold up a self hosted a drep server in aliyun ecs for proxy traffic of my home server,after setup success i found that if others konw or scanned my ip and port they also c

no，im now trap in how aliyun ECS can access my home server,would you have pleasure to give me some suggest to get out of this,if not just ignore it,i will investigate another day


<img width="1255" alt="image" src="https://github.com/tailscale/tailscale/assets/1646883/d09e7ce8-3344-4cb2-9f07-07f0f5831079">

here is my  ip tables, on my mobile tailscale the 192.168.31.1 have response,but on this server never get data


and this is my security group on ecs

<img width="2600" alt="image" src="https://github.com/tailscale/tailscale/assets/1646883/c1a2aafd-5512-4ca7-943e-cba69a07faf1">

**Comment by bradfitz** [comment]
Sorry, we don't have the resources to provide custom DERP consulting in this forum.

**Comment by joebnb** [comment]
<img width="1866" alt="image" src="https://github.com/tailscale/tailscale/assets/1646883/460a8c13-a4b4-44b1-bbd0-8b14855cbf14">

<img width="1207" alt="image" src="https://github.com/tailscale/tailscale/assets/1646883/76dd28d4-9ffe-4bcc-b7ec-19488e6f2cad">

would this could help to figure out?

**Comment by joebnb** [comment]
and this is my docker compose of tailscale

```
services:
    tailscale:
        container_name: tailscale
        image: tailscale/tailscale:latest
        network_mode: 'host'
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
            - NET_RAW
        volumes:
            - 'tailscale_data:/var/lib/tailscale'
            - /var/lib:/var/lib
            - /dev/net/tun:/dev/net/tun
        environment:
            TS_AUTHKEY: tskey-key
            TS_EXTRA_ARGS: '--netfilter-mode=off --accept-dns=false --accept-routes'
            TS_STATE_DIR: /var/lib/tailscale
volumes:
    tailscale_data:
        driver: local
        name: tailscale_data
```
