### ISSUE TITLE
FR: Enable deploying app connectors on kube via Connector custom resource

### ISSUE THREAD

**Issue by irbekrm** [tailscale/tailscale#11113]
### What are you trying to do?

We should make it possible to deploy app-connectors on Kubernetes via [Connector custom resource](https://tailscale.com/kb/1236/kubernetes-operator#deploying-exit-nodes-and-subnet-routers-on-kubernetes-using-connector-custom-resource) i.e

```
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: prod
spec:
  connector: true
  tags:
  - "tag:prod"
  hostname: ts-prod
  subnetRouter:
    advertiseRoutes:
    - "10.40.0.0/14"
    - "192.168.0.0/14"
```

**Comment by tobiasehlert** [comment]
@irbekrm;
I was looking for that as well, but this could maybe help some (it's docker-compose but could be rewritten):
https://github.com/tailscale-dev/docker-guide-code-examples/blob/main/02-oauth/compose.yaml

But would definitely be nice to be able to deploy it with the operator :)

**Comment by maxlareo** [comment]
In the meantime it'd be nice to have an example of Kubernetes manifests for deploying app connector, in `docs/k8s/` ?, to make it easy to deploy a separate node able to be advertised as app connector, i.e. `--advertise-connector`, until the Connector CRD supports it.

**Comment by maxlareo** [comment]
In case that helps, here a working example of a Kubernetes StatefulSet to deploy a Tailscale node used as App Connector:

```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ts-app-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-app-connector
  serviceName: ts-app-connector
  template:
    metadata:
      labels:
        app: ts-app-connector
    spec:
      containers:
        - env:
            - name: TS_USERSPACE
              value: "true"
            - name: TS_ACCEPT_DNS
              value: "true"
            - name: TS_KUBE_SECRET
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
                  optional: false
            - name: TS_EXTRA_ARGS
              value: >
                --advertise-connector
                --advertise-tags=tag:appc
                --reset
          image: tailscale/tailscale:v1.62.1
          name: tailscale
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      serviceAccount: proxies
      serviceAccountName: proxies

```

NB: serviceAccount `proxies` from the Kubernetes Operator: https://github.com/tailscale/tailscale/blob/main/cmd/k8s-operator/deploy/chart/templates/proxy-rbac.yaml

**Comment by frmrm** [comment]
Would love to see some movement here. I needed this today and was sad to find it wasn't a thing.

**Comment by tobiasehlert** [comment]
@maxlareo; implemented your suggestion, but there the population of routes does for some reason not work.

I had to modify it slightly until I got it to work..
- set _TS_ACCEPT_DNS_ to `false`
- set _TS_EXTRA_ARGS_ for `--snat-subnet-routes` (not fully understand why though)
- set _TS_AUTHKEY_ to use Tailscale Kubernetes operator `operator-oauth` secret instead 
- add _TS_HOSTNAME_ for visibility in [login.tailscale.com/admin/machines](https://login.tailscale.com/admin/machines)
- add _TS_ROUTE_ with routes (`--advertise-connector` doesn't seem to work)

The thing that is annoying is the _TS_ROUTE_ part.. the other parts I "can live with". 😛 

This is how it looks right now at least..

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ts-app-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-app-connector
  serviceName: ts-app-connector
  template:
    metadata:
      labels:
        app: ts-app-connector
    spec:
      containers:
        - env:
            - name: TS_USERSPACE
              value: "true"
            - name: TS_ACCEPT_DNS
              value: "false"
            - name: TS_HOSTNAME
              value: "app-connector-nbg1"
            - name: TS_KUBE_SECRET
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: operator-oauth
                  key: client_secret
                  optional: false
            - name: TS_EXTRA_ARGS
              value: >
                --advertise-connector
                --advertise-tags=tag:app-connectors-nbg1
                --snat-subnet-routes
                --reset
            - name: TS_ROUTES
              value: 104.18.114.8/32,104.18.185.8/32
          image: tailscale/tailscale:v1.62.1
          name: tailscale
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      serviceAccount: proxies
      serviceAccountName: proxies
```

**Comment by bkonicek** [comment]
I've tested with both of these examples and I found that while it does work for external sites (e.g. ipchicken.com) if I add them to the app connector domains, it doesn't work for my own sites in the same cluster exposed via an `Ingress`. Instead, the client IP appears as the app connector pod's own IP. This means that if I want to expose my other services via an ingress so that they can use my public DNS zone but secure them behind Tailscale, I would have to whitelist the Pod's IP on my ingress. However, since pod IPs can change any time the pod is rescheduled that's not really a feasible option. I tried adding my Ingress controller's load balancer IP to `TS_ROUTES` but it didn't seem to make a difference.

```
> curl -L test.mydomain.com
Hostname: whoami-deployment-b5b78b9b4-fzpm6
IP: 127.0.0.1
IP: ::1
IP: 10.244.2.7
RemoteAddr: 10.244.2.2:39054
GET / HTTP/1.1
Host: test.mydomain.com
User-Agent: curl/8.1.2
Accept: */*
X-Forwarded-For: 10.244.2.155
X-Forwarded-Host: test.mydomain.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Scheme: https
X-Real-Ip: 10.244.2.155
```

```
> k get pod -n tailscale ts-app-connector-0 -o wide
NAME                 READY   STATUS    RESTARTS   AGE     IP             NODE         NOMINATED NODE   READINESS GATES
ts-app-connector-0   1/1     Running   0          8m28s   10.244.2.155   10.0.1.202   <none>           <none>
```

Setting an IP whitelist on my ingress to my cluster's NAT Gateway (same IP that ipchicken shows when routed over the app connector) results in getting the ingress-nginx 403 error page.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    nginx.ingress.kubernetes.io/whitelist-source-range: $NAT_GATEWAY_IP/32
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - test.mydomain.com
      secretName: whoami-cert
  rules:
    - host: test.mydomain.com
```

**Comment by maxlareo** [comment]
I'm not from Tailscale so I might be wrong on this but from what I understand, Apps and Apps-Connectors works entirely upon DNS and Tailscale MagicDNS mechanisms. Thus for route discovering to work you must ensure MagicDNS is enabled, i.e. `TS_ACCEPT_DNS` to `"true"` using official container image.

Also there seems to be an ongoing issue on Tailscale ACLs system that breaks Apps-connector DNS queries when only [autogroup:internet is allowed](https://tailscale.com/kb/1281/app-connectors#access-to-apps), for now you must also explicitly allow the device running as connector in your ACLs dst alongside the autogroup:internet. That made the tricks for me, this is the only extra step I've done after following the documentation and using the manifest I've posted above.

Regarding internal kubernetes routes, as it relies on DNS resolution made by the app connector, if it returns your pod IP I think it means the pod is prioritizing internal nameserver over externals, in this case tailscale nameserver. It could probably be solved by tinkering with [DNS Pod Policy](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy). I did not tested it as I don't have a need for it but it should do the job.

**Comment by bkonicek** [comment]
Regarding the DNS I have to assume something like that is going on, however considering that my Ingress's host record only points to a public IP I would think that this means the app connector would have to go out to the public internet in order to reach it, in which case shouldn't the client IP show as my NAT Gateway IP? My only guess is that my cluster (Oracle Kubernetes Engine) has NAT hairpinning enabled and I need to find a way to disable that.

**Comment by bkonicek** [comment]
Changing it to `"hairpinMode":false` didn't help unfortunately. I'd be curious if people running the app connector in different providers' clusters see the same behavior.

**Comment by maxlareo** [comment]
I think this is now achievable using the ProxyClass CRD to specify the StatefulSet Containers specs. I didn't tested it yet but I'll probably try soon. I'm sharing it now in case it helps someone before I test it myself.

Here the setup I attempt to try:

```yaml
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: prod
spec:
  proxyClass: app-connector
  tags:
  - "tag:prod"
  hostname: ts-prod
  subnetRouter:
    advertiseRoutes:
    - "10.40.0.0/14"
    - "192.168.0.0/14"
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: app-connector
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        env:
          - name: TS_EXTRA_ARGS
            value: >
              --advertise-connector
          - name: TS_ACCEPT_DNS
            value: "true"
```
The above ProxyClass is a draft, I'll need to test it to confirm it works. It might require other args/options to achieve it.

I still think this should be available from the Connector CRD directly as suggested in the issue description but at least this solution would allow to manage app connector via Tailscale CRD only and not managing separate manually crafted kubernetes manifests.

**Comment by mback2k** [comment]
I just tested this, but unfortunately it is now working with the current `tailscale-operator` due to this error:
```
Defaulted container "tailscale" out of: tailscale, sysctler (init)
boot: 2024/10/05 15:04:51 skipping file "..data" in tailscaled config directory "/etc/tsconfig": input does not match format
boot: 2024/10/05 15:04:51 Using tailscaled config file '_' for capability version 'a'
boot: 2024/10/05 15:04:51 invalid configuration: TS_EXPERIMENTAL_VERSIONED_CONFIG_DIR cannot be set in combination with TS_HOSTNAME, TS_EXTRA_ARGS, TS_AUTHKEY, TS_ROUTES, TS_ACCEPT_DNS.
```
`TS_EXTRA_ARGS` is not supported due to the operator using `TS_EXPERIMENTAL_VERSIONED_CONFIG_DIR`.

**Comment by irbekrm** [comment]
We have added `.appConnector` field to `Connector` spec in https://github.com/tailscale/tailscale/pull/13950 and there is now a Tailscale dev release with this change (`v1.77.88` Kubernetes Operator dev Helm chart/`unstable-v1.77.88` proxy and operator images + latest manifests).
A basic `Connector` that deploys an app connector on Kubernetes looks like this:

```
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: prod
spec:
  appConnector: {}
```

See also the API docs https://github.com/tailscale/tailscale/blob/main/k8s-operator/api.md#connector

Note that as per the comment on `spec.appConnector` field this comes with a bunch of notes/caveats:
- the only supported/tested use case is deploying app connector for access of SaaS apps over the public internet
- this only deploys app connector device - manual config of apps/ACLs is still required, see app connector docs https://tailscale.com/kb/1281/app-connectors
- users themselves need to ensure static egress IP for the traffic from app connector

If folks have other app connector use cases and workflows that they would like to be better supported on kube, we would be interested to hear 🙏🏼 

Note also that the `Connector` currently only supports a single replica. We are looking at allowing multiple replicas and better failover soon, see https://github.com/tailscale/tailscale/issues/14020

**Comment by laszlocph** [comment]
This looks very promising @irbekrm !

I tried with `unstable-v1.77.88` but I got 

```
invalid: spec: Invalid value: \"object\": A Connector needs to have at least one of exit node, subnet router or app connector configured.
```

for the following connector:

```
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: prod
spec:
  appConnector: {}
```
