### ISSUE TITLE
Cannot establish direct connection / DERP servers slow

### ISSUE THREAD

**Issue by Valiceemo** [tailscale/tailscale#11112]
### What is the issue?

Direct connection over cellular (mobile data) is not possible, falling back to relays 99.99% of the time.
And then the DERPS are slow.
I am in the UK, so nearest server geographically is London, yet Tailscale reports Madrid as the closest
```
Report:
        * UDP: true
        * IPv4: yes, xx.xx.xxx.x:57185
        * IPv6: no, but OS has support
        * MappingVariesByDestIP: false
        * HairPinning: false
        * PortMapping: UPnP
        * CaptivePortal: false
        * Nearest DERP: Madrid
        * DERP latency:
                - mad: 64.7ms  (Madrid)
                - waw: 66.1ms  (Warsaw)
                - lhr: 85.2ms  (London)
                - nyc: 92.5ms  (New York City)
                - mia: 116.1ms (Miami)
                - tor: 118.8ms (Toronto)
                - ord: 121.7ms (Chicago)
                - den: 127.5ms (Denver)
                - dfw: 130.4ms (Dallas)
                - dbi: 153.7ms (Dubai)
                - lax: 161.5ms (Los Angeles)
                - sea: 164.9ms (Seattle)
                - sfo: 168.4ms (San Francisco)
                - sin: 172.7ms (Singapore)
                - nai: 176.8ms (Nairobi)
                - hnl: 183.7ms (Honolulu)
                - jnb: 188.7ms (Johannesburg)
                - sao: 191.5ms (São Paulo)
                - hkg: 226.4ms (Hong Kong)
                - tok: 246.9ms (Tokyo)
                - blr: 277.3ms (Bangalore)
                - syd: 277.7ms (Sydney)
```
Tailscale ping shows I am indeed connect to London derp, but latency is high, with anywhere from 200ms, to as high as 900ms!
Bug report from Linux machine:
`
BUG-27ad229fc0e6ef459e126942d91cb8c118d16354e18b9329cc21862b505cfde2-20240212150557Z-aa6caf4a7dc97faa
`
Bug report generated on Android device:
`
BUG-59b18464c3a691025c7355c659faa95a77b7c96d699c139a481f55fdfeb7ca79-20240212150522Z-fe09d191bbf9997e
`
Direct connections have been achieved, once or twice, but do not last long, falling back to relays

### Steps to reproduce

Connect to tailscale via mobile data
Tested across Android and iOS devices, across multiple mobile carriers (UK based, EE, O2 and Sky Mobile)

### Are there any recent changes that introduced the issue?

-

### OS

Linux

### OS version

Raspbian 11 Bullseye

### Tailscale version

1.58.2

### Other software

Pihole with unbound as recursive DNS server

### Bug report

BUG-27ad229fc0e6ef459e126942d91cb8c118d16354e18b9329cc21862b505cfde2-20240212150557Z-aa6caf4a7dc97faa
