### ISSUE TITLE
own DERP server not working

### ISSUE THREAD

**Issue by vampywiz17** [tailscale/tailscale#11180]
### What is the issue?

My own derp server are not working. It worked well 2-3 release before.

### Steps to reproduce

Here my configs:

Docker Compose:

```
version: '3.3'
services:
  tailscale:
    container_name: tailscaled
    volumes:
      - '$APPDATA_PATH/tailscale:/var/lib/tailscale'
      - '/var/run/tailscale/:/var/run/tailscale/'
    environment:
      - TS_AUTHKEY=$TS_AUTHKEY
      - TS_ROUTES=192.168.31.0/24
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
      - TS_STATE_DIR=/var/lib/tailscale
    network_mode: host
    image: tailscale/tailscale:latest
    restart: unless-stopped

  derper:
    environment:
      - DERP_DOMAIN=myderpserver.org
      - DERP_STUN=true
      - DERP_STUN_PORT=16667
      - DERP_ADDR=:16666
      - DERP_HTTP_PORT=16666
      - DERP_VERIFY_CLIENTS=true
    depends_on:
      - tailscale
    ports:
      - '16666:16666'
      - '16667:16667'

    volumes:
      - '/var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock:ro'
    image: fredliang/derper
    restart: unless-stopped
```

ACL
```

	"derpMap": {
		"OmitDefaultRegions": true,
		"Regions": {
			"900": {
				"RegionID":   900,
				"RegionCode": "vamp-system",
				"Nodes": [
					{
						"Name":     "home",
						"RegionID": 900,
						"HostName": "myderpserver.org",
						"STUNPort": 16667,
					},
				],
			},
		},
	},
	"randomizeClientPort": true,
}
```
port 16666 are behind a HAProxy (the frontend are 443/HTTP)
port 16667 are forwarded to Docker host 16667 port

### Are there any recent changes that introduced the issue?

it worked 2-3 release before.

### OS

Linux, Other

### OS version

Docker (Alpine 3.19.0) and Linux Ubuntu 22.04

### Tailscale version

1.60.0 and 1.58.2

### Bug report

BUG-b91eb5442015fbc8a4b830a691681439e8a9afc0c0d6e670fd6b1afcef6e7c9f-20240220162954Z-b91ebbcbbedd6ee7
