### ISSUE TITLE
expose service with tailnet name 

### ISSUE THREAD

**Issue by Ludea** [tailscale/tailscale#11205]
### What is the issue?

Hi,
I install tailscale operator and k8s dashboard.
I would like to access dashboard only into my private server.
So I use this ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-dashboard
spec:
  defaultBackend:
    service:
      name: kubernetes-dashboard 
      port:
        name: https
  ingressClassName: tailscale
```

I connect to my private Network with tailscale, reach my service with tailnet name, `foo.bar.ts.net`
But I get nothing. 

### Steps to reproduce

Install tailscale operator
Install kubernetes dashboard without nginx, cert manager, and ingress.
Apply ingress :
```
 apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
spec:
  defaultBackend:
    service:
      name: nginx
      port:
        name: https
  ingressClassName: tailscale
```

### OS

Linux

### OS version

Opensuse 

### Tailscale version

1.60
