### ISSUE TITLE
Tailscale in Docker not using Mullvad exit node

### ISSUE THREAD

**Issue by bedesv** [tailscale/tailscale#11219]
### What is the issue?

I'm trying to get Tailscale and Mullvad set up in Docker to download Linux ISOs. I currently use a Wireguard Mullvad config and a Wireguard VPN container for this, but I'm trying to transition to Tailscale with Mullvad so that I can have both enabled on my phone and computers and not have to switch between them.

The Tailscale container reports that it is using the Mullvad exit node, but the Tailscale container and attached containers all report my actual public IP.

### Steps to reproduce

I'm using the docker-compose file at the bottom of the post. There are a few things to note:
1. Docker 25.0.1 is running on my server, which is Ubuntu Server 22.04.3 LTS. It is also running a Tailscale client natively.
2. Using the MagicDNS name for the Mullvad exit node (e.g. `se-sto-wg-006.mullvad.ts.net`) doesn't work - it says `invalid value "se-sto-wg-006.mullvad.ts.net" for --exit-node; must be IP or unique node name`
3. I've tried different Mullvad servers and they all have the same behaviour
4. I've tried with `--exit-node-allow-lan-access` set to both `true` and `false`
5. I get this message on startup `magicsock: disco: node [e8+dM] d:9dd4e3a812aeb422 now using 192.168.80.25:41641 mtu=1360 tx=fbcddbfac58b`. I'm not 100% sure what it means but `192.168.80.25` is my laptops local IP, which is running Tailscale and using a Mullvad exit node

When the container is running I can check the IP with the following steps:
```
docker exec -it tailscale sh
apk add curl
curl ifconfig.me
```
This returns my actual public IP. When I run `curl ifconfig.me` on my laptop, it returns the IP of the Mullvad exit node.

I can also access the Firefox web UI at `http://mediaserver-torrentbox:5800`. The internet works but again, checking my public IP shows my actual public IP, not the Mullvad one.

I've also tried using the Tailscale web UI to edit the configuration, including changing around to a few different Mullvad exit nodes. It says that it's using the exit node as expected.

```
services:
  tailscale: 
    container_name: tailscale 
    image: tailscale/tailscale:stable 
    hostname: mediaserver-torrentbox 
    environment:
      - TS_AUTHKEY=${TAILSCALE_TOKEN}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --exit-node=100.115.139.145 --exit-node-allow-lan-access=false
      - TS_STATE_DIR=/var/lib/tailscale
    volumes: 
      - ${HOMEDIR}/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add: 
      - net_admin 
      - sys_module 
    restart: unless-stopped


  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-test
    network_mode: "service:tailscale"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - WEBUI_PORT=80
    volumes:
      - ${HOMEDIR}/qbittorrent/config:/config
      - ${HOMEDIR}/qbittorrent/downloads:/downloads
    restart: unless-stopped

  firefox:
    image: jlesage/firefox
    network_mode: "service:tailscale"
    volumes:
      - ${HOMEDIR}/firefox:/config:rw

    restart: unless-stopped
```

### OS

Linux

### OS version

Ubuntu Server 22.04.3 LTS

### Tailscale version

1.60.0

### Bug report

BUG-2179d646ab92f03b6979d1996909a63e9c4919cea31b0e52ebd30e102d800b28-20240223225521Z-b4a65ef89c14a8c3

**Comment by knyar** [comment]
Hey, I think you might want to disable [userspace mode](https://tailscale.com/kb/1282/docker#ts_userspace) if you expect Tailscale client to configure the kernel routing table.

Some of the examples in our Docker docs are missing this as well, I will get that fixed.

**Comment by bedesv** [comment]
That solved it, thank you.

**Comment by Jorundur** [comment]
@bedesv Would you mind posting your final docker compose? I'm still having an issue similar to this, even after disabling user space.

**Comment by bedesv** [comment]
@Jorundur I went back to using my Wireguard Mullvad setup as I found that the Tailscale container was leaking my IP for a few seconds when it started up. Here's the compose I was using for the project. The Firefox container was for testing for IP leaks.


The Tailscale token is of the form: `TAILSCALE_TOKEN=tskey-client-...-...?ephemeral=false`

```
version: "3.8"
services:
  tailscale: 
    container_name: tailscale 
    image: tailscale/tailscale:stable 
    hostname: server-torrentbox 
    environment:
      - TS_AUTHKEY=${TAILSCALE_TOKEN}
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=true
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --exit-node=${EXIT_NODE_IP} --exit-node-allow-lan-access=false --reset
      - TS_STATE_DIR=/var/lib/tailscale
    volumes: 
      - ${HOMEDIR}/tailscale:/var/lib/tailscale # State data will be stored in this directory 
      - /dev/net/tun:/dev/net/tun # Required for tailscale to work 
    cap_add: # Required for tailscale to work 
      - net_admin 
      - sys_module 
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-test
    network_mode: "service:tailscale"
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=80
    volumes:
      - ${HOMEDIR}/qbittorrent/config:/config
      - ${HOMEDIR}/qbittorrent/downloads:/downloads
    restart: unless-stopped

  firefox:
    image: jlesage/firefox
    network_mode: "service:tailscale"
    volumes:
      - ${HOMEDIR}/firefox:/config:rw
    restart: unless-stopped
```
