### ISSUE TITLE
Can't access port 8080 when using tailscale/tailscale to expose my container

### ISSUE THREAD

**Issue by g3rv4** [tailscale/tailscale#11283]
### What is the issue?

When using the `tailscale/tailscale` container to expose a container, exposing the port `8080` does not work on `v1.60.0`. Downgrading to `v1.58.2` fixes the problem.

This doesn't happen on port `80`.

### Steps to reproduce

A small repro can be achieved with this `docker-compose.yml` file:

```
services:
  http-echo:
    image: hashicorp/http-echo
    command: ["-listen=:8080", "-text=Hello from http-echo"]
    depends_on:
      - ts
    network_mode: service:ts
  ts:
    image: tailscale/tailscale:v1.60.0
    environment:
      - TS_AUTHKEY
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
````

The machine appears on the console, but doing `curl` fails:

````
curl http://100.68.124.112:8080/
curl: (52) Empty reply from server
````

### Are there any recent changes that introduced the issue?

Yes, `v1.60.0` introduced this bug. This can be verified by changing the version of the `tailscale/tailscale` container on the `docker-compose.yml` from the repro:

```
services:
  http-echo:
    image: hashicorp/http-echo
    command: ["-listen=:8080", "-text=Hello from http-echo"]
    depends_on:
      - ts
    network_mode: service:ts
  ts:
    image: tailscale/tailscale:v1.58.2
    environment:
      - TS_AUTHKEY
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
```

now I can `curl` into it:

```
curl http://100.107.115.94:8080/
Hello from http-echo
```

### OS

macOS

### OS version

macOS Sonoma 14.3.1 (23D60)

### Tailscale version

1.60.0

### Bug report

BUG-7332d35c8b16a3f27105a9db7cefb5c4db06b724f08501729c19eb967a900fd8-20240228153851Z-caac12e65945f95c

**Comment by oxtoacart** [comment]
Digging into this ...

**Comment by oxtoacart** [comment]
The fix for this is available in unstable-v1.61.61. The below `docker-compose.yml` works for me.

```
services:
  http-echo:
    image: hashicorp/http-echo
    command: ["-listen=:8080", "-text=Hello from http-echo"]
    depends_on:
      - ts
    network_mode: service:ts
  ts:
    image: tailscale/tailscale:unstable-v1.61.61
    environment:
      - TS_AUTHKEY
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
```

**Comment by oxtoacart** [comment]
I've confirmed that this is fixed in the latest stable release as used in the below docker-compose.yml.

```
services:
  http-echo:
    image: hashicorp/http-echo
    command: ["-listen=:8080", "-text=Hello from http-echo"]
    depends_on:
      - ts
    network_mode: service:ts
  ts:
    image: tailscale/tailscale:v1.60.1
    environment:
      - TS_AUTHKEY
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
```
