### ISSUE TITLE
Expose multiples port from k8s service 

### ISSUE THREAD

**Issue by Ludea** [tailscale/tailscale#11300]
### What is the issue?

I have a single k8s service with some ports (3000, 3001, 50051).
I would like to expose them by ingress with funnel support.
For starting, I only expose 50051 port (grpc server)
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
    annotations:
      tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-svvc
            port:
              number: 443
```

But my server is unreachable. 

### Steps to reproduce

Create a service with multiple port and try to expose them with tailscale ingress 

### OS

Linux

### OS version

Opensuse
