### ISSUE TITLE
TLS handsake error when connecting to a gRPC backend via Kubernetes Ingress

### ISSUE THREAD

**Issue by Ludea** [tailscale/tailscale#11343]
### What is the issue?

I get `TLS handshake error from 100.120.57.80:55177: tls: first record does not look like a TLS hanshake` from tailscale proxy pod
It's a grpc server. I get this issue when connecting to tailnet, I didn't try with funnel yet 

### Steps to reproduce

deploy tailscale operator 
deploy a service
apply :
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: svc-ns
    annotations:
      tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-svc
            port:
              number: 443
```

### Are there any recent changes that introduced the issue?

/

### OS version

OpenSuse Tumbleweed

### Tailscale version

1.61.11

### Other software

I get another service well served by tailscale, with tls support
