### ISSUE TITLE
Strange routing decision on Linux/docker

### ISSUE THREAD

**Issue by awsong** [tailscale/tailscale#11420]
### What is the issue?

```
/ # ip rule
0:	from all lookup local
5210:	from all fwmark 0x80000/0xff0000 lookup main
5230:	from all fwmark 0x80000/0xff0000 lookup default
5250:	from all fwmark 0x80000/0xff0000 unreachable
5270:	from all lookup 52
32766:	from all lookup main
32767:	from all lookup default
/ # ip r s table local
local 100.102.76.70 dev tailscale0 proto kernel scope host src 100.102.76.70 
local 127.0.0.0/8 dev lo proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo proto kernel scope link src 127.0.0.1 
local 172.25.0.3 dev eth1 proto kernel scope host src 172.25.0.3 
broadcast 172.25.255.255 dev eth1 proto kernel scope link src 172.25.0.3 
local 192.168.3.70 dev eth0 proto kernel scope host src 192.168.3.70 
broadcast 192.168.3.255 dev eth0 proto kernel scope link src 192.168.3.70 
/ # ip r g 192.168.3.9
192.168.3.9 dev tailscale0 table 52 src 100.102.76.70 uid 0 
    cache 
/ # 
```
Please see my above routing decision to address 192.168.3.9, according to 'ip rule' it should look up table local and should hit line `local 192.168.3.70 dev eth0 proto kernel scope host src 192.168.3.70 ` and route to dev eth0. But it actually resulted looking up table 52, which is as following: 
```
/ # ip r s table 52
100.67.155.16 dev tailscale0 
100.67.167.49 dev tailscale0 
100.68.225.62 dev tailscale0 
100.75.252.39 dev tailscale0 
100.80.80.122 dev tailscale0 
100.80.89.78 dev tailscale0 
100.82.230.103 dev tailscale0 
100.88.93.85 dev tailscale0 
100.89.163.4 dev tailscale0 
100.90.60.30 dev tailscale0 
100.92.228.39 dev tailscale0 
100.93.204.64 dev tailscale0 
100.95.18.117 dev tailscale0 
100.97.118.26 dev tailscale0 
100.98.38.47 dev tailscale0 
100.100.100.100 dev tailscale0 
100.101.102.103 dev tailscale0 
100.104.110.150 dev tailscale0 
100.108.104.5 dev tailscale0 
100.111.66.133 dev tailscale0 
100.112.66.3 dev tailscale0 
100.117.223.72 dev tailscale0 
100.118.79.23 dev tailscale0 
100.118.177.123 dev tailscale0 
100.120.190.63 dev tailscale0 
100.122.189.12 dev tailscale0 
100.125.48.43 dev tailscale0 
100.126.124.123 dev tailscale0 
100.127.52.104 dev tailscale0 
192.168.1.0/24 dev tailscale0 
192.168.2.0/24 dev tailscale0 
192.168.3.0/24 dev tailscale0 
```

### Steps to reproduce

I started tailscale in docker, here is the relavent docker-compose part:
```
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:stable
    environment:
      - TZ=Asia/Shanghai
      - TS_HOSTNAME=ts-fx
      - TS_ROUTES=192.168.3.0/24
      - TS_STATE_DIR=/etc/tailscale
      - TS_AUTHKEY=tskey-auth-xxxxx
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--accept-routes
    restart: unless-stopped
    network_mode: "service:npm"
    cap_add:
      - net_admin
      - sys_module
    volumes:
      - /docker_data/tailscale:/etc/tailscale
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

### Are there any recent changes that introduced the issue?

no

### OS

Linux

### OS version

Debian GNU/Linux trixie

### Tailscale version

1.60.1
