### ISSUE TITLE
Ping tailnet name, deployed with funnel fail 

### ISSUE THREAD

**Issue by Ludea** [tailscale/tailscale#11423]
### What is the issue?

I install tailscale operator on k8s.
I get a service like
```
Name:              speedupdate
Namespace:         speedupdate
Labels:            app.kubernetes.io/instance=speedupdate
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/name=speedupdate
                   app.kubernetes.io/version=1.16.0
                   helm.sh/chart=speedupdate-0.1.0
Annotations:       meta.helm.sh/release-name: speedupdate
                   meta.helm.sh/release-namespace: speedupdate
Selector:          app.kubernetes.io/instance=speedupdate,app.kubernetes.io/name=speedupdate
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.43.170.177
IPs:               10.43.170.177
Port:              http  3000/TCP
TargetPort:        http/TCP
Endpoints:         10.42.0.33:3000
Port:              grpc  50051/TCP
TargetPort:        grpc/TCP
Endpoints:         10.42.0.33:50051
Port:              ftp  2121/TCP
TargetPort:        ftp/TCP
Endpoints:         10.42.0.33:2121
Port:              metrics  3001/TCP
TargetPort:        metrics/TCP
Endpoints:         10.42.0.33:3001
Session Affinity:  None
Events:            <none>
```
 I deploy an ingress with funnel support
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedupdate
  namespace: speedupdate
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: speedupdate
            port:
              number: 443
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: speedupdate
            port:
              number: 50051
```
I try to ping or nmap my http svc marlin-atlas.ts.net on different port : 3000, 80, 443. It fail each time.
Grpc service is also unreachable 
There are no error logs into ts proxy pod.
All fine too, from operator pod

### Steps to reproduce

Deploy tailscale on k8s
Deploy an http service
Apply above manifest 

### OS

Linux

### OS version

Opensuse 

### Tailscale version

1.67.11
