### ISSUE TITLE
Tailscale DNS name changes when a Kubernetes Service exposed via Tailscale is recreated by ArgoCD

### ISSUE THREAD

**Issue by didlawowo** [tailscale/tailscale#11482]
### What is the issue?

i have tailscale operator with exposure service
when the service disapear and be recreated (like update with argo cd), tailscale create a new machine,
then the dns change 

<img width="1212" alt="image" src="https://github.com/tailscale/tailscale/assets/12622760/4c827d4c-2c37-4c7a-8c01-817182d9ed2f">

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlflow
    type: tailscale
  name: tailscale-mlflow
  namespace: mlops
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: tracking
    app.kubernetes.io/name: mlflow
  type: LoadBalancer
  loadBalancerClass: tailscale
```

### Steps to reproduce

delete and recreate service

### Are there any recent changes that introduced the issue?

nop 

### OS

Linux

### OS version

ubuntu 22 / debian raspian bookwork

### Tailscale version

1.61
