### ISSUE TITLE
Node shows as using Funnel, but in fact is not and has not been configured/asked to do so.

### ISSUE THREAD

**Issue by Zackey** [tailscale/tailscale#11572]
### What is the issue?

Hi,

A node in my dashboard is using serve to share a home automation docker container to my tailnet.

However, my tailscale "sidecar" is showing as "Funnel" in the dashboard. It is not accessible via the internet, nor does it have any DNS public facing. Its serve config states very clearly to disable (false) funnel, and at no point has funnel been permitted via ACL etc.

**To be clear:** Testing reveals this node is not accessible from WAN, thus this appears to be a visual issue only. 

Here is my docker compose file:
```
---
services:
   servicename:
    image: tailscale/tailscale:latest
    container_name: containername
    hostname: homeauto
    environment:
      - TS_AUTHKEY=<oClient keyhere>?ephemeral=false
      - "TS_EXTRA_ARGS=--advertise-tags=tag:services"
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_STATE_DIR=/state
    volumes:
      - /home/aname/homeassistant/tailscale/state:/state
      - /home/aname/homeassistant/tailscale/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
   homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: service:servicename
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=MyTimezone/Timezone
    volumes:
      - /home/aname/homeassistant/data:/config
    restart: unless-stopped
```

Here is my serve.json file:
```
{
    "TCP": {
      "443": {
        "HTTPS": true
      }
    },
    "Web": {
      "${TS_CERT_DOMAIN}:443": {
        "Handlers": {
          "/": {
            "Proxy": "http://127.0.0.1:8123"
          }
        }
      }
    },
    "AllowFunnel": {
      "${TS_CERT_DOMAIN}:443": false
    }
  }
```
Here is an image of my dashboard showing the tag:
![image](https://github.com/tailscale/tailscale/assets/5611682/a65b512f-13b9-4e32-a7c0-69762cc93c0f)

Here is the output of tailscale serve status:
![image](https://github.com/tailscale/tailscale/assets/5611682/74c022f9-7622-4a15-af43-aa050be8fefc)

### Steps to reproduce

- Using a Ubuntu 22.04 LTS, create a docker compose file using my config.
- Launch the container and approve the device in the dashboard.
- Enable HTTPS for certs.
- Repeat as needed to reproduce. 

### OS

Linux

### OS version

Ubuntu 22.04 LTS

### Tailscale version

1.62.1

### Other software

Home Assistant in the same compose file. 

### Bug report

BUG-fc7836367283c4d51c47510be98851e5e90ccc2372723fe6733cddb7522a2b33-20240401015821Z-3d18fb30e1330a39
