### ISSUE TITLE
FR: Add Tailscale Kubernetes Operator Helm Chart to https://artifacthub.io

### ISSUE THREAD

**Issue by jason-riddle** [tailscale/tailscale#11580]
### What are you trying to do?

I'm currently running the Tailscale Kubernetes Operator in my homelab Kubernetes Cluster. In order to do this, I need to have a way to determine what versions are available and where the helm repo is located. I'm currently deploying via Kustomize, and I'm using the following `kustomization.yml` to deploy.

```yml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    includeCRDs: true
    valuesInline:
      operatorConfig:
        hostname: "tailscale-operator"
        logging: "info"
    releaseName: tailscale-operator
    # Tailscale Releases: https://github.com/tailscale/tailscale/releases
    # Helm Chart Releases: https://pkgs.tailscale.com/helmcharts/index.yaml
    version: 1.60.1
```

And deploying this way works great, however, there isn't a straightforward way to tell when there is a new version of the chart is available. I can look at https://github.com/tailscale/tailscale/releases for tailscale binary releases, but it seems like helm charts can take longer to roll out as with what happened with `v1.58.2` (https://github.com/tailscale/tailscale/issues/10963).

I understand the reasoning for waiting to roll this out, but on my own I'd like to be able to monitor for updates. So as an example, because the `hashicorp/vault` helm chart is hosted here: https://artifacthub.io/packages/helm/hashicorp/vault, I can subscribe to the RSS feed available here: https://artifacthub.io/api/v1/packages/helm/hashicorp/vault/feed/rss and be notified when an update is available for that helm chart.

### How should we solve this?

Create a package in https://artifacthub.io/, perhaps for example as https://artifacthub.io/packages/helm/tailscale/k8s-operator and by doing that, now users can subscribe for notifications via RSS feed.

### What is the impact of not solving this?

Right now, I'm doing a combination of checking https://github.com/tailscale/tailscale/releases and https://pkgs.tailscale.com/helmcharts/index.yaml.

The releases page has an RSS feed available at https://github.com/tailscale/tailscale/releases and I can monitor for new Tailscale binary versions via that, but for helm chart changes, I'm just checking https://pkgs.tailscale.com/helmcharts/index.yaml every so often to see if that release has finished rolling out and is now available as a helm chart.

### Anything else?

This issue is not related to https://github.com/tailscale/tailscale/issues/11421, but there are involved in the same space of helm, so I want to link them so users watching that issue can also watch this, if they are interested.
