### ISSUE TITLE
Unauthorized to pull v1.56.1 in quay.io/tailscale/k8s-operator 

### ISSUE THREAD

**Issue by bingkunyangvungle** [tailscale/tailscale#11675]
### What is the issue?

When I was trying to run the tailscale operator helm with version v1.56.1, I get error: 
`"Failed to pull image "tailscale/k8s-operator:v1.56.1": reading manifest v1.56.1 in quay.io/tailscale/k8s-operator: unauthorized: access to the requested resource is not authorized"`

### Steps to reproduce

Just run the command to run the helm with the following command:
`  name       = "tailscale-operator"
  repository = "https://pkgs.tailscale.com/helmcharts"
  chart      = "tailscale-operator"
  version    = "1.56.1" # application version v0.66.0`

### OS

Linux

**Comment by bingkunyangvungle** [comment]
I tried with other versions (1.58.2, 1.62.1, 1.62.0) and all get the same error. Please help to take a look.

**Comment by bingkunyangvungle** [comment]
Follow up: I tried to set the image pull policy to be IfNotPresent on the Tailscale operator helm value, it does work for the tailscale deployment to pick this up. But for the other resource associated with Tailscale operator, it doesn't set the correct policy for the image pulling for the container (it does work for the initcontainer though). Please help to fix this.
```
      containers:
        image: tailscale/tailscale:v1.56.1
        imagePullPolicy: Always
        name: tailscale
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - -c
        - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1
        command:
        - /bin/sh
```
