### ISSUE TITLE
use tailscale offered drep server are work as expect,but use my custom can‘t work

### ISSUE THREAD

**Issue by joebnb** [tailscale/tailscale#11674]
### What is the issue?

if use tailscale offered drep server are work well,if use self hosted(under docker via:https://hub.docker.com/r/fredliang/derper) will get error.

NOTE:my drep server and tailscale client was installed on same VM

<img width="1436" alt="image" src="https://github.com/tailscale/tailscale/assets/1646883/a1f98af2-f6e9-4d20-8c22-39884932c512">

<img width="1029" alt="image" src="https://github.com/tailscale/tailscale/assets/1646883/449b9127-e088-4ee6-998a-f5d480486a9f">

VM's tailscale connect to Itself drep
<img width="963" alt="image" src="https://github.com/tailscale/tailscale/assets/1646883/0ed4457d-8611-4ddc-889a-0643ef2fa320">

NOTE:if use laptop to connect VM drep,drep server is work 

this is my drep server configuration:
```yaml
services:
    tailscale-drep:
        container_name: drep
        image: fredliang/derper:latest
        network_mode: 'bridge'
        restart: unless-stopped
        ports:
            - 8443:443
            - 3478:3478/udp
        environment:
            DERP_DOMAIN: dommain.of.drep
```
would i mapping some path to host machine？or is some bug on drep server?

### OS

Linux

### OS version

ubuntu 22

### Tailscale version

latest
