### ISSUE TITLE
Tailscale node sharing doesn’t work with Synology

### ISSUE THREAD

**Issue by clarkezone** [tailscale/tailscale#11840]
### What is the issue?

I would like to use tailscale sharing with my synology NAS.  At the moment these appear to be compatible as I have the most recent tailscale for synology build:

![IMG_0227](https://github.com/tailscale/tailscale/assets/1128250/4ea70fa9-bfea-45a4-a90c-6425308b9ce9)

and yet share requires a newer version

![IMG_0228](https://github.com/tailscale/tailscale/assets/1128250/671ef187-3b87-4d65-8e79-2430eb190472)

### Steps to reproduce

1. Install tailscale on a synology nas view package manager
2. Go to admin console, share machine

Result: warning that the version isn’t compatible

### OS

Synology

**Comment by kelivel** [comment]
Hi @clarkezone, we're working to update the Package Center to a newer version, which usually has a long approval process, and the version you're currently using shouldn't prevent you from sharing your device. Our most recent Synology builds are hosted at our packages repository over at https://pkgs.tailscale.com/stable/#spks — I'd recommend downloading version 1.64 that matches your Synology's CPU and install using the "Manual Install" option in the Package Center.

**Comment by jmsnll** [comment]
Alternatively @clarkezone you can use the Tailscale docker image via Container Manager, here's my docker compose if you should want to do so:

```
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: eu-lon-01
    network_mode: host 
    environment:
      - TS_AUTHKEY=$TS_AUTHKEY
      - TS_EXTRA_ARGS=--advertise-exit-node
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /volume1/docker/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
```

You'll need to generate an auth key and set `TS_AUTHKEY`: https://login.tailscale.com/admin/settings/keys
You might also find this blog post helpful: https://memoryleak.dev/post/fix-tun-tap-not-available-on-a-synology-nas/
