### ISSUE TITLE
Funnel works only within tailnet

### ISSUE THREAD

**Issue by marcinjahn** [tailscale/tailscale#11849]
### What is the issue?

It seems to me that `funnel` and `serve` do the same thing.
Both allow me to serve content, which is then available via HTTPS only within my tailnet. As I understand, `funnel` should allow me to publish content publicly, on internet. However, my funneled resource works only when I'm connected to my tailnet.

### Steps to reproduce

1. On Device A, Run some web app locally on one of the nodes, e.g. via `podman run -d -p 8080:80 tutum/hello-world`
2. On Device A, Enable funnel: `tailscale funnel 8080`
3. On another Device B (not connected to your tailnet), try to navigate to Device A's DNS address.
4. Page will not be found

### Are there any recent changes that introduced the issue?

Nope, it never worked for me

### OS

Linux, iOS

### OS version

Fedora 39, iOS 17.4.1

### Tailscale version

1.64.0

### Bug report

BUG-e75df7e9a917df61bd3b4c6244e8924e06db465d45115a81747489e4fae37b8c-20240423153805Z-00750e64e97bc4fe

**Comment by jimmybrancaccio** [comment]
I was able to replicate this today due to an incoming support ticket (TSS-37882). I setup a basic `docker-compose.yml`:

```json
version: "3.7"
services:
  ts-dillinger-webserver:
    image: tailscale/tailscale:latest
    container_name: ts-dillinger
    hostname: dillinger
    environment:
      - TS_AUTHKEY=tskey-client-kMq9ax11CNTRL-gGBoK58SWxnGj
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/dillinger.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /home/jimmy/.docker/data/ts-dillinger-webserver/state:/var/lib/tailscale
      - /home/jimmy/.docker/data/ts-dillinger-webserver/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  ts-dillinger:
    image: lscr.io/linuxserver/dillinger:latest
    container_name: dillinger
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/jimmy/.docker/data/dillinger/config:/config
    network_mode: service:ts-dillinger-webserver
    depends_on:
      - ts-dillinger-webserver
    restart: unless-stopped
```

In my SERVE file I have:

```json
{
  "TCP": {
    "443": {
      "HTTPS": true
    }
  },
  "Web": {
    "${TS_CERT_DOMAIN}:443": {
      "Handlers": {
        "/": {
          "Proxy": "http://127.0.0.1:8080"
        }
      }
    }
  },
  "AllowFunnel": {
    "${TS_CERT_DOMAIN}:443": true
  }
}
```

I ran `docker compose up -d --remove-orphans` and everything looks to have started up fine. I observed these couple of lines which seems to indicate the funnel is running:

```
ts-dillinger  | 2024/05/07 20:34:15 serve: closing idle connections to http://127.0.0.1:8080
ts-dillinger  | boot: 2024/05/07 20:34:15 Applying serve config
ts-dillinger  | 2024/05/07 20:34:15 serve: creating a new proxy handler for http://127.0.0.1:8080
```

I see my container show up in my admin console, however I observed in the admin console, clicking on the machine to go to the machine page, under the TLS Configuration section the domain shows properly, but the Status shows as No certificate found. I observed that when trying to visit https://dillinger.taildfbdd.ts.net failed and I also couldn't resolve the hostname.

I then swapped from a different tailnet I was on to the tailnet where I had deployed the container node and I tried bringing up https://dillinger.taildfbdd.ts.net. At this point I observed in the Docker container logs:

```
ts-dillinger  | 2024/05/07 20:43:39 cert("dillinger.taildfbdd.ts.net"): registered ACME account.
ts-dillinger  | 2024/05/07 20:43:39 cert("dillinger.taildfbdd.ts.net"): starting SetDNS call...
ts-dillinger  | 2024/05/07 20:43:50 cert("dillinger.taildfbdd.ts.net"): did SetDNS
ts-dillinger  | 2024/05/07 20:43:51 cert("dillinger.taildfbdd.ts.net"): requesting cert...
ts-dillinger  | 2024/05/07 20:43:52 cert("dillinger.taildfbdd.ts.net"): got cert
ts-dillinger  | 2024/05/07 20:43:52 Accept: TCP{100.65.211.27:65338 > 100.80.14.102:443} 52 tcp non-syn
ts-dillinger  | 2024/05/07 20:43:52 http: TLS handshake error from 100.65.211.27:65338: EOF
dillinger     | 100.65.211.27 - GET / HTTP/1.1 200 - - 329.889 ms
dillinger     | 100.65.211.27 - GET /assets/app-9a52b028cbd397404e2c56df7c2f8e87.css HTTP/1.1 200 72955 - 7.123 ms
dillinger     | 100.65.211.27 - GET /img/icons/file.svg HTTP/1.1 200 - - 12.122 ms
dillinger     | 100.65.211.27 - GET /js/main.bundle.js HTTP/1.1 200 - - 20.965 ms
dillinger     | 100.65.211.27 - GET /theme-github.js HTTP/1.1 404 154 - 27.085 ms
dillinger     | 100.65.211.27 - GET /img/icons/code.svg HTTP/1.1 200 902 - 11.722 ms
dillinger     | 100.65.211.27 - GET /img/icons/enter-zen.svg HTTP/1.1 200 - - 13.855 ms
ts-dillinger  | 2024/05/07 20:44:02 Accept: TCP{100.65.211.27:65339 > 100.80.14.102:443} 107 tcp non-syn
```

so it seems clear that just trying to visit the service triggered a request for a TLS certificate. I had waited about 15 minutes before trying this as [our documentation](https://tailscale.com/kb/1223/funnel#run-tailscale-funnel) indicates it should happen in about 10 minutes but didn't for me.

In summary, I experienced the same issue as described in the original post as well as is the customer who submitted a recent support ticket. Funnel is working more like Serve in that you cannot reach the funneled service if you're not connected to the tailnet where the funnel is running.

**Comment by tommyboylab** [comment]
I'm encountering a similar issue with funnels but haven't yet investigated it as deeply as above. 

Simple issue is I'm hosting a few docker containers on a local machine (also an exit-node) of which I'd like to funnel. Each have an assigned port local to the machine which I can access within the tailnet (both by IP and by the magic-dns). With funnel on I can also access the services from the defined endpoint (either root or from --set-path) but if outside the tailnet this fails.

I've tried creating certs using the tailscale cert <name> command along with restarting the service on the local machine but when visiting the funneled endpoint I get the error from the browser `<server> unexpectedly closed the connection.`  

Without hijacking the issue above if there's a connected problem or missing configuration needed please inform me.

**Comment by brian316** [comment]
i followed this video here from tailscale https://www.youtube.com/watch?v=tqvvZhGrciQ
and used the following docker compose file
```
---
version: "3.7"
services:
  ts-homeassistant:
    image: tailscale/tailscale:latest
    container_name: ts-homeassistant
    hostname: homeassistant
    environment:
      - TS_AUTHKEY=tskey-auth-removed-for-obvious-reasons
      - "TS_EXTRA_ARGS=--advertise-tags=tag:container --reset"
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve-config.json
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - ${PWD}/serveconfig:/config
    cap_add:
      - net_admin
      - sys_module
      - sys_admin
    restart: unless-stopped
    privileged: true
    network_mode: host
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: homeassistant
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /home/homeassistant:/config
      - /run/dbus:/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    depends_on:
      - ts-homeassistant
    network_mode: service:ts-homeassistant

volumes:
  ts-homeassistant:
    driver: local
```

and this is my serve-config.json
```json
{
    "TCP": {
      "443": {
        "HTTPS": true
      }
    },
    "Web": {
      "${TS_CERT_DOMAIN}:443": {
        "Handlers": {
          "/": {
            "Proxy": "http://127.0.0.1:8123"
          }
        }
      }
    },
    "AllowFunnel": {
      "${TS_CERT_DOMAIN}:443": false
    }
  }
```

im not even using the funnel yet and i get an error for acme request.
```
acme: ARI check failed: failed to fetch renewal info from ACME server: fetching renewal info: 400 urn:ietf:params:acme:error:malformed: While parsing ARI CertID an error occurred :: Invalid path; falling back to expiry-based check
```
