### ISSUE TITLE
Funnel to share Home Assistant uses HTTP and port 8123

### ISSUE THREAD

**Issue by quietCoder500** [tailscale/tailscale#11937]
### What is the issue?

I tried to share my Home Assistant server (http://localhost:8123) using funnel, but when I opened the https url I got `400: Bad Request`. Only when I use `http://home***.tail******.ts.net:8123/` does Home Assistant open.

### Steps to reproduce

When I ran:
`> sudo tailscale funnel http://localhost:8123`
I recieved:
```
Available on the internet:

https://home***.tail******.ts.net/
|-- proxy http://127.0.0.1:8123

Press Ctrl+C to exit.
```

### Are there any recent changes that introduced the issue?

N/A

### OS

Linux

### OS version

Raspberry Pi OS Bookworm

### Tailscale version

1.64.0

### Other software

Home Assistant with Docker Compose

### Bug report

BUG-9063b89346358f044632aa76e34f3804be7a4f9f3dddb54416e4a25812b76fae-20240430163201Z-7817ecb4350be312

**Comment by peskyAdmin** [comment]
you need to run the serve command. which will act as a reverse proxy + handle certs. then when you go to the domain it will use port 443 and work as expected. the setup you have now is dangerous as you have unencrypted endpoint facing the web.

**Comment by quietCoder500** [comment]
So start serve first and then funnel serve port 443? Also, I didn't leave the funnel up after I realized that it was http. Thanks for the help.

**Comment by peskyAdmin** [comment]
yes, start serve first and funnel to the https port 443. verify it works in tailnet, make sure you https enabled in the tailscale console. then enable funnel and see if you can hit it from the outside

**Comment by brendiche** [comment]
Hello, i have quite the same setup of tailscale with home assistant. here is my compose.yml : 
```yaml
services:
  ts-homeassistant:
    image: tailscale/tailscale:latest
    container_name: ts-homeassistant
    hostname: homeassistant
    environment:
      - TS_AUTHKEY=${HOMEASSISTANT_AUTH_KEY}
      - "TS_EXTRA_ARGS=--advertise-tags=tag:container --reset"
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/homeassistant.json
    volumes:
      - ${PWD}/tailscaleHA/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - ${PWD}/tailscaleHA/config:/config
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  homeassistant:
      container_name: ${HOMEASSISTANT_CONTAINER_NAME}
      image: "homeassistant/home-assistant:stable"
      volumes:
        - ./config:/config
        - /etc/localtime:/etc/localtime:ro
        - /run/dbus:/run/dbus:ro
      restart: unless-stopped
      privileged: true
      network_mode: service:ts-homeassistant
      depends_on: 
        - ts-homeassistant
volumes:
  tailscaleHA:
    driver: local
```

my homeassistant.json look like this : 
```json
{
  "TCP": {
    "443": {
      "HTTPS": true
    }
  },
  "Web": {
    "${TS_CERT_DOMAIN}:443": {
      "Handlers": {
        "/": {
          "Proxy": "http://127.0.0.1:8123"
        }
      }
    }
  },
  "AllowFunnel": {
    "${TS_CERT_DOMAIN}:443": true
  }
}
```

and i can access my homeassistant thought my tailnet but i can't access it from the internet. 
the error i am getting form my container is :`[unexpected] magicsock: derp-18 does not know about peer [qFRGl], removing route`

i have unable https, i have add the nodeAttrs , the homeassistant node is well listed in my machines and is display as `Funnel`

I have no clue why it is not working.

**Comment by brendiche** [comment]
Finally it ends up working with a bit of patience

**Comment by lvolcov** [comment]
@brendiche would you mind sharing what did you do to have it working please? I am trying to implement a similar solution, thank you!!

**Comment by saineela** [comment]
I reverse proxied my home assitant from tailscale but still it shows 400: Bad request

**Comment by brendiche** [comment]
hi, @lvolcov i switch from docker-compose to k8s but i can share you the docker-compse file i have used: 
```
services:
  ts-homeassistant:
    image: tailscale/tailscale:latest
    container_name: ts-homeassistant
    hostname: home-assistant
    environment:
      - TS_AUTHKEY=${HOMEASSISTANT_OAUTH_CLIENT}
      - "TS_EXTRA_ARGS=--advertise-tags=tag:container --reset"
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/homeassistant.json
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscaleHA/state:/var/lib/tailscale
      - ${PWD}/tailscaleHA/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  homeassistant:
      container_name: ${HOMEASSISTANT_CONTAINER_NAME}
      image: "homeassistant/home-assistant:stable"
      volumes:
        - ./config:/config
        - /etc/localtime:/etc/localtime:ro
        - /run/dbus:/run/dbus:ro
      restart: unless-stopped
      privileged: true
      network_mode: service:ts-homeassistant
      depends_on: 
        - ts-homeassistant
volumes:
  tailscaleHA:
    driver: local
```

**Comment by saineela** [comment]
We can also use configuration.yml on home assistant to allow reverse proxy from other addresses. It worked for me

**Comment by adrianjost** [comment]
I think this issue comes from homeassistant itself. When used with a reverse proxy, you need to add `use_x_forwarded_for` and `trusted_proxies` to your homeassistant config.

```yml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    # whatever subnet your funnel requests from
    - 192.168.2.0/24 
    # - 172.30.33.0/24
```
