### ISSUE TITLE
"control: map response long-poll timed out!" without reconnect

### ISSUE THREAD

**Issue by bfallik** [tailscale/tailscale#12021]
### What is the issue?

I'm trying to track down a case where tailscale loses connectivity and never reconnects.  I'm running tailscale inside a container and this seems to leave the container in a broken state. I'm unable to connect to the contained service until I manually restart everything.

It'd be nice if tailscale were able to self-detect this error and reconnect or even exit the container so that it can be restarted instead of me having to manually intervene.

Here's the relevant log details
```
05/05 07:04:23 control: lite map update error after 120ms: initial fetch failed 404: node not found
658ad6db-d353-4d92-b9ab-ae65f7b50372
05/05 07:04:23 Received error: PollNetMap: initial fetch failed 404: node not found
551dda22-6e57-4ef7-8ea6-a955ee13cfcd
05/05 07:04:23 control: lite map update error after 637ms: initial fetch failed 404: node not found
05/05 07:04:23 Received error: PollNetMap: Post "https://controlplane.tailscale.com/machine/map": read tcp 10.89.0.>
05/05 07:04:22 control: lite map update error after 24.064s: Post "https://controlplane.tailscale.com/machine/map":>
05/05 07:03:58 control: lite map update error after 2m0.002s: Post "https://controlplane.tailscale.com/machine/map">
05/05 07:03:58 control: map response long-poll timed out!
05/05 07:03:37 Received error: PollNetMap: Post "https://controlplane.tailscale.com/machine/map": context canceled
05/05 07:03:37 control: map response long-poll timed out!
05/05 07:03:16 logtail: upload succeeded after 1 failures and 1m2s
05/05 07:03:16 logtail: bootstrap dial succeeded
05/05 07:03:16 magicsock: derp-1 connected; connGen=2
05/05 07:03:16 logtail: dial "log.tailscale.io:443" failed: dial tcp: lookup log.tailscale.io on 10.89.0.1:53: read>
05/05 07:03:12 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:03:10 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): context>
05/05 07:03:05 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:03:04 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): context>
05/05 07:02:59 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:02:57 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): context>
05/05 07:02:53 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:02:52 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): context>
05/05 07:02:47 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:02:46 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): context>
05/05 07:02:41 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:02:40 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): context>
05/05 07:02:36 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:02:35 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): context>
05/05 07:02:30 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:02:30 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): context>
05/05 07:02:25 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:02:24 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): context>
05/05 07:02:20 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:02:19 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): context>
05/05 07:02:15 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:02:15 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): context>
05/05 07:02:14 logtail: upload: log upload of 372 bytes compressed failed: Post "https://log.tailscale.io/c/tailnod>
05/05 07:02:14 bootstrapDNS("derp24b.tailscale.com", "2001:19f0:c000:c586:5400:4ff:fe26:2ba6") for "log.tailscale.i>
05/05 07:02:14 trying bootstrapDNS("derp24b.tailscale.com", "2001:19f0:c000:c586:5400:4ff:fe26:2ba6") for "log.tail>
05/05 07:02:14 bootstrapDNS("derp17c.tailscale.com", "208.111.40.12") for "log.tailscale.io" error: Get "https://de>
05/05 07:02:11 trying bootstrapDNS("derp17c.tailscale.com", "208.111.40.12") for "log.tailscale.io" ...
05/05 07:02:11 bootstrapDNS("derp24c.tailscale.com", "2001:19f0:c000:c591:5400:4ff:fe26:2c5f") for "log.tailscale.i>
05/05 07:02:11 trying bootstrapDNS("derp24c.tailscale.com", "2001:19f0:c000:c591:5400:4ff:fe26:2c5f") for "log.tail>
05/05 07:02:11 bootstrapDNS("derp4d.tailscale.com", "134.122.94.167") for "log.tailscale.io" error: Get "https://de>
05/05 07:02:10 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:02:10 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): dial tc>
05/05 07:02:08 trying bootstrapDNS("derp4d.tailscale.com", "134.122.94.167") for "log.tailscale.io" ...
05/05 07:02:08 bootstrapDNS("derp5b.tailscale.com", "2403:2500:9000:1::ce7") for "log.tailscale.io" error: Get "htt>
05/05 07:02:08 trying bootstrapDNS("derp5b.tailscale.com", "2403:2500:9000:1::ce7") for "log.tailscale.io" ...
05/05 07:02:08 bootstrapDNS("derp1i.tailscale.com", "199.38.181.103") for "log.tailscale.io" error: Get "https://de>
05/05 07:02:05 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:02:05 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): context>
05/05 07:02:05 trying bootstrapDNS("derp1i.tailscale.com", "199.38.181.103") for "log.tailscale.io" ...
05/05 07:02:05 bootstrapDNS("derp2f.tailscale.com", "2607:f740:0:3f::f4") for "log.tailscale.io" error: Get "https:>
05/05 07:02:05 trying bootstrapDNS("derp2f.tailscale.com", "2607:f740:0:3f::f4") for "log.tailscale.io" ...
05/05 07:02:05 bootstrapDNS("derp8f.tailscale.com", "176.58.88.183") for "log.tailscale.io" error: Get "https://der>
05/05 07:02:02 trying bootstrapDNS("derp8f.tailscale.com", "176.58.88.183") for "log.tailscale.io" ...
05/05 07:02:02 bootstrapDNS("derp12d.tailscale.com", "2607:f740:e::811") for "log.tailscale.io" error: Get "https:/>
05/05 07:02:02 trying bootstrapDNS("derp12d.tailscale.com", "2607:f740:e::811") for "log.tailscale.io" ...
05/05 07:02:02 bootstrapDNS("derp3c.tailscale.com", "43.245.49.83") for "log.tailscale.io" error: Get "https://derp>
05/05 07:02:01 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:02:01 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): context>
05/05 07:01:59 trying bootstrapDNS("derp3c.tailscale.com", "43.245.49.83") for "log.tailscale.io" ...
05/05 07:01:59 bootstrapDNS("derp1d.tailscale.com", "2604:a880:800:10::7fe:f001") for "log.tailscale.io" error: Get>
05/05 07:01:59 trying bootstrapDNS("derp1d.tailscale.com", "2604:a880:800:10::7fe:f001") for "log.tailscale.io" ...
05/05 07:01:59 bootstrapDNS("derp11d.tailscale.com", "148.163.220.210") for "log.tailscale.io" error: Get "https://>
05/05 07:01:58 magicsock: endpoints changed: 10.89.0.7:35459 (local)
05/05 07:01:58 control: NetInfo: NetInfo{varies= hairpin= ipv6=false ipv6os=true udp=false icmpv4=false derp=#1 por>
05/05 07:01:56 derphttp.Client.Recv: connecting to derp-1 (nyc)
05/05 07:01:56 trying bootstrapDNS("derp11d.tailscale.com", "148.163.220.210") for "log.tailscale.io" ...
05/05 07:01:56 magicsock: [0xc00013f9e0] derp.Recv(derp-1): derp.Recv: read tcp4 10.89.0.7:45814->199.38.181.93:443>
05/05 07:01:56 health("overall"): error: not in map poll
05/05 07:01:46 logtail: dial "log.tailscale.io:443" failed: dial tcp: lookup log.tailscale.io on 10.89.0.1:53: serv>
05/05 07:01:37 Received error: PollNetMap: context canceled
05/05 07:01:37 control: map response long-poll timed out!
```

I run the container within a systemd pod. Here's the YAML:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: rest-server
spec:
  containers:
  - name: rest-server
    image: "docker.io/restic/rest-server:0.12.1"
    ports:
    - containerPort: 8000
      hostPort: 8000
    env:
    - name: OPTIONS
      value: "--prometheus"
    - name: DISABLE_AUTHENTICATION
      value: "true"
    volumeMounts:
    - name: restic-data
      mountPath: /data/restic-repo
  - name: tailscale
    image: "ghcr.io/tailscale/tailscale:latest"
    env:
    - name: TS_AUTHKEY
      valueFrom:
        secretKeyRef:
          name: restic-rest-server-ts-authkey
          key: ts_authkey
    - name: TS_STATE_DIR
      value: /var/lib/tailscale
    volumeMounts:
    - name: ts-state
      mountPath: /var/lib/tailscale
  volumes:
  - name: restic-data
    persistentVolumeClaim:
      claimName: ts-state-dir
    hostPath:
      path: "/mnt/One Touch/backups/restic-repo"
      type: Directory
  - name: ts-authkey-data
    secret:
      secretName: restic-rest-server-ts-authkey
      optional: false
  - name: ts-state
    persistentVolumeClaim:
      claimName: ts-state-dir
```

LMK if I can provide any more details.

### Steps to reproduce

1. Start the service
2. Wait

### OS

Linux

### OS version

Fedora 39
