### ISSUE TITLE
Tailscale version 1.66.0 breaks docker swarm container connectivity to tailscale hosts

### ISSUE THREAD

**Issue by mrvalterhugo** [tailscale/tailscale#12206]
### What is the issue?

I run docker swarm in 3 Debian 11 LXC Proxmox containers without any issue.
I noticed my docker containers lost connectivity to tailscale nodes.
I have tested with prior docker versions with no changes.
I them  tested older tailscale versions, and I found that connectivity breaks from version 1.66.0

Connectivity still works fine from the LXC host, but does not work from inside the docker containers.

### Steps to reproduce

Upgrade to latest tailscale client version.
Try ping to a tailscale host from inside a docker container.
Ping does not work.

### Are there any recent changes that introduced the issue?

Version 1.66.0 onwards.

### OS

Linux

### OS version

Debian 11

### Tailscale version

1.66.0

### Other software

Docker swarm
LXC

**Comment by kelivel** [comment]
I suspect you're encountering the new stateful filtering flag introduced in 1.66.0 for [Security Bulletin TS-2024-005](https://tailscale.com/security-bulletins#ts-2024-005). Try disabling stateful filtering with `tailscale up --stateful-filtering=false` and let us know if that helps.

**Comment by haku** [comment]
i have encountered a similar issue that has been confusing me for the last week.
i have a bunch of docker containers that connect to tailscale addresses (100. addresses) and tailscaled is only running on the host machine.
the docker containers periodically stop being able to route packets to 100. addresses.

after a bunch of guessing, i think it depends on the service start up order.
if tailscale starts, then docker, it works file.
if docker starts first, or tailscale is restarted, connectivity is lost.
so i guess it breaks every time tailscale updates?

diffing `iptables --list` before and after:
```
 Chain FORWARD (policy DROP)
 target     prot opt source               destination         
-ts-forward  all  --  anywhere             anywhere            
 DOCKER-USER  all  --  anywhere             anywhere            
 DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
 ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
 DOCKER     all  --  anywhere             anywhere            
 ACCEPT     all  --  anywhere             anywhere            
 ACCEPT     all  --  anywhere             anywhere            
+ts-forward  all  --  anywhere             anywhere            
 ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
 DOCKER     all  --  anywhere             anywhere            
 ACCEPT     all  --  anywhere             anywhere 
```
i think it is dependent on the potion of the ts-forward line, - position does not work and + position does work.

using `--stateful-filtering=false` makes this issue go away, hence posting about it here.

**Comment by mrvalterhugo** [comment]
`tailscale up --stateful-filtering=false` does fix the issue, thank you.

**Comment by StevenMassaro** [comment]
Sorry for the redundancy here, but this seems to still not be working for me, but through docker compose for me. What am I missing?

```
  tailscale:
    container_name: tailscale
    hostname: tailscale
    image: tailscale/tailscale:v1.66.4
    volumes:
      - ...
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    command: tailscaled
    environment:
      - TS_USERSPACE=false
      - TS_ROUTES=192.168.1.0/24
      - TS_ACCEPT_DNS=true
      - TS_EXTRA_ARGS="--stateful-filtering=false --advertise-exit-node --accept-routes"
    privileged: true
    restart: always
    network_mode: host
```
