### ISSUE TITLE
FR: socks/http proxy by kubernetes operator

### ISSUE THREAD

**Issue by mweibel** [tailscale/tailscale#12211]
### What are you trying to do?

We have ArgoCD running which needs to access our git instance accessible via tailnet. ArgoCD pulls certain repositories via git URL and therefore needs access to the tailnet. 

The Kubernetes operator does not yet seem to support a way to set the `TS_SOCKS5_SERVER` environment variable (or other proxy env variables). This means we had to create a separate sidecar which we then can use as a proxy target.

### How should we solve this?

Add the ability to specify proxy options for exposing an egress service. Could be done by adding more annotations or using a separate CRD (or maybe the ProxyClass CRD can be reused?). 

### What is the impact of not solving this?

As mentioned - separate sidecar. The trouble with managing a separate sidecar is that we didn't want to use an auth key since they auto-expire after 90 days and the pods running can be recreated any time. This means we had to settle for an Oauth2 client which means the container has (a) too much permissions (device write) and (b) every time a new pod gets scheduled, the respective machine needs to be manually approved.

**Comment by irbekrm** [comment]
@mweibel you can configure env vars for the operator proxies via ProxyClass https://github.com/tailscale/tailscale/blob/main/k8s-operator/apis/v1alpha1/types_proxyclass.go#L179

**Comment by mweibel** [comment]
Thanks @irbekrm! While I looked at ProxyClass I somehow oversaw this possibility. Will test and report back 👍

**Comment by irbekrm** [comment]
Thanks, it was added quite recently. Let us know how it goes- it might anyway make sense to make something custom for this.

**Comment by mweibel** [comment]
I tried to make it work but couldn't. I believe the problem is that we can't specify ports for service or the sts pod so the socks5 port doesn't get exposed. 

setup to reproduce:
```yaml
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: socks5-proxy
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        env:
          - name: TS_SOCKS5_SERVER
            value: ":1055"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: service.example.ts.net
  labels:
    tailscale.com/proxy-class: "socks5-proxy"
  name: service
spec:
  externalName: placeholder
  type: ExternalName
```

```bash
$ kubectl debug -it pod/<existing-pod> --image=nicolaka/netshoot

existing-pod ~ curl -v -x socks5://service:1055 https://device-name-in-tailnet
* Host service:1055 was resolved.
* IPv6: (none)
* IPv4: <stsPodIp>
*   Trying <stsPodIp>:1055...
* connect to <stsPodIp> port 1055 from <sourcePod> port 47024 failed: Connection refused
* Failed to connect to service port 1055 after 82 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to service port 1055 after 82 ms: Couldn't connect to server
```

I believe to make this work we'd need to be able to specify which port to expose in the STS and possibly also in the associated services. 
I tried to manually edit the service/sts but of course the operator immediately overwrites any changes. I didn't yet try to stop the operator to test it out - that's one thing I could try. But maybe another day :smile:
