### ISSUE TITLE
tailscale-operator: internal names from `Ingress` resources refuse connection

### ISSUE THREAD

**Issue by embik** [tailscale/tailscale#12230]
### What is the issue?

I'm trying to use the brand new feature in the Kubernetes operator [to expose tailscale service names within the cluster](https://tailscale.com/kb/1236/kubernetes-operator#expose-a-tailnet-https-service-to-your-cluster-workloads). I've got DNS resolution running, but when trying to use hostnames from within a pod I'm running into the following problem:

```sh
$ root@shell:/# curl https://vaultwarden.<tailnet>.ts.net
curl: (7) Failed to connect to vaultwarden.<tailnet>.ts.net port 443 after 1 ms: Couldn't connect to server
root@shell:/# curl https://vaultwarden.<tailnet>.ts.net -v
* Host vaultwarden.<tailnet>.ts.net:443 was resolved.
* IPv6: (none)
* IPv4: 10.244.1.205
*   Trying 10.244.1.205:443...
* connect to 10.244.1.205 port 443 from 10.244.1.201 port 39584 failed: Connection refused
* Failed to connect to vaultwarden.<tailnet>.ts.net port 443 after 3 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to vaultwarden.<tailnet>.ts.net port 443 after 3 ms: Couldn't connect to server
```

An ingress exists:

```sh
k get ing -A
NAMESPACE         NAME                 CLASS       HOSTS           ADDRESS                               PORTS     AGE
[...]
vaultwarden       vaultwarden          tailscale   vaultwarden     vaultwarden.<tailnet>.ts.net     80, 443   18d
[...]
```

The resolved IP address is identical with the local proxy pod:

```sh
$ k get pods -n tailscale -o wide | grep 10.244.1.205
ts-vaultwarden-7cgqn-0          1/1     Running   0          13m   10.244.1.205   rpi-02   <none>           <none>
```

And the service is also reachable from regular machines signed into my tailnet:

```sh
$ curl https://vaultwarden.<tailnet>.ts.net -XGET -I
HTTP/2 200
```

So everything individually seems to work up to the in-cluster pod trying to talk to the local proxy pod in the cluster. I don't know exactly why this would happen. Trying to talk to the local proxy pod directly also doesn't work:

```sh
$ curl --resolve vaultwarden.<tailnet>.ts.net:443:10.244.1.205 https://vaultwarden.<tailnet>.ts.net -v
* Added vaultwarden.<tailnet>.ts.net:443:10.244.1.205 to DNS cache
* Hostname vaultwarden.<tailnet>.ts.net was found in DNS cache
*   Trying 10.244.1.205:443...
* connect to 10.244.1.205 port 443 from 10.244.1.201 port 57362 failed: Connection refused
* Failed to connect to vaultwarden.<tailnet>.ts.net port 443 after 0 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to vaultwarden.<tailnet>.ts.net port 443 after 0 ms: Couldn't connect to server
```

I assume I've either misconfigured something or my setup is exotic enough to trigger some sort of issue, but I'm not exactly sure what. Any suggestions on what is going wrong? Any more information I can provide? I'm aware this is an early new feature, so happy to help where I can to improve this.

### Steps to reproduce

Deploy tailscale-operator 1.66.3 with the following values:

```yaml
operatorConfig:
  hostname: "raspi"
apiServerProxyConfig:
  mode: "noauth"
```

Create a DNS config:

```yaml
apiVersion: tailscale.com/v1alpha1
kind: DNSConfig
metadata:
  name: ts-dns
spec:
  nameserver:
    image:
      repo: tailscale/k8s-nameserver
      tag: unstable
```

Add a ConfigMap to forward DNS requests for ts.net:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
    stubDomains: |
      {
        "ts.net": [
          "10.98.70.25"
        ]
      }
```

Try to curl service names from within a pod.

### OS

Linux

### OS version

Debian GNU/Linux 12 (bookworm)

### Tailscale version

1.66.3

### Other software

- Kubernetes 1.27.13, deployed with KubeOne 1.7.3
- CNI: Canal (Flannel v0.21.3, Calico v3.26.3)

### Bug report

BUG-87f57f70fd6d04359b0a4287c0bd348488b099cf0b41268e5838f28ed75c7518-20240523182959Z-4de9d4880a09fa51
