### ISSUE TITLE
failed to create cert

### ISSUE THREAD

**Issue by brian316** [tailscale/tailscale#12264]
### What is the issue?

i followed this video here from tailscale https://www.youtube.com/watch?v=tqvvZhGrciQ
and used the following docker compose file
```
---
version: "3.7"
services:
  ts-homeassistant:
    image: tailscale/tailscale:latest
    container_name: ts-homeassistant
    hostname: homeassistant
    environment:
      - TS_AUTHKEY=tskey-auth-removed-for-obvious-reasons
      - "TS_EXTRA_ARGS=--advertise-tags=tag:container --reset"
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve-config.json
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - ${PWD}/serveconfig:/config
    cap_add:
      - net_admin
      - sys_module
      - sys_admin
    restart: unless-stopped
    privileged: true
    network_mode: host
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: homeassistant
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /home/homeassistant:/config
      - /run/dbus:/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    depends_on:
      - ts-homeassistant
    network_mode: service:ts-homeassistant

volumes:
  ts-homeassistant:
    driver: local
```

and this is my serve-config.json
```json
{
    "TCP": {
      "443": {
        "HTTPS": true
      }
    },
    "Web": {
      "${TS_CERT_DOMAIN}:443": {
        "Handlers": {
          "/": {
            "Proxy": "http://127.0.0.1:8123"
          }
        }
      }
    },
    "AllowFunnel": {
      "${TS_CERT_DOMAIN}:443": false
    }
  }
```

im not even using the funnel yet and i get an error for acme request.
```
ts-homeassistant  | 2024/05/28  Accept: TCP{xxxxxxxxxx:63005 > xxxxxxxxxx:443} 52 tcp ok
ts-homeassistant  | 2024/05/28  Accept: TCP{xxxxxxxxxx:63006 > xxxxxxxxxx:443} 52 tcp ok
ts-homeassistant  | 2024/05/28  Accept: TCP{xxxxxxxxxx:63005 > xxxxxxxxxx:443} 52 tcp ok
ts-homeassistant  | 2024/05/28  cert("homeassistant.xxxxxxxxxx.ts.net"): registered ACME account.
ts-homeassistant  | 2024/05/28  cert("homeassistant.xxxxxxxxxx.ts.net"): starting SetDNS call...
ts-homeassistant  | 2024/05/28  cert("homeassistant.xxxxxxxxxx.ts.net"): did SetDNS
ts-homeassistant  | 2024/05/28  cert("homeassistant.xxxxxxxxxx.ts.net"): requesting cert...
ts-homeassistant  | 2024/05/28  cert("homeassistant.xxxxxxxxxx.ts.net"): got cert
ts-homeassistant  | 2024/05/28  Accept: TCP{xxxxxxxxxx:63006 > xxxxxxxxxx:443} 40 tcp non-syn
ts-homeassistant  | 2024/05/28  acme: ARI check failed: failed to fetch renewal info from ACME server: fetching renewal info: 400 urn:ietf:params:acme:error:malformed: While parsing ARI CertID an error occurred :: Invalid path; falling back to expiry-based check
....
acme: ARI check failed: failed to fetch renewal info from ACME server: fetching renewal info: 400 urn:ietf:params:acme:error:malformed: While parsing ARI CertID an error occurred :: Invalid path; falling back to expiry-based check
```

### OS

Linux

**Comment by brian316** [comment]
using this image
```
❯ docker image ls
REPOSITORY                              TAG       IMAGE ID       CREATED         SIZE
tailscale/tailscale                     latest    a8c3bf542685   2 weeks ago     88.1MB
```

**Comment by awly** [comment]
@brian316 does the cert get generated? Can you reach `https://homeassistant.xxxxxxxxxx.ts.net`?

The error about the ARI check is non-critical. It checks for when to renew the certificate, and falls back to checking the expiry time on the certificate on failure. We should fix that, of course, but I want to make sure that it's not preventing your TLS certificates from getting provisioned.

**Comment by brian316** [comment]
actually i was able to fix this. i thought that was the error but it was actually home assistant itself that wasnt trusting the tailscale proxy. I had to add this to `configuration.yaml`
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1  # proxy is internal for tailscale
```
will close this issue now since i can access my domain even on clearnet.

I do have another issue though that im not sure what to do even looking at tailscale docs. I want to assign my subdomain `home.*.com` so my tailscale subdomain `home.*.ts.net` i added a CNAME in my cloudflare dns to point to it but i get an error of too many redirects. i know this issue may be out of scope but if anyone know i would appreciate it.
