### ISSUE TITLE
Docker v1.66.4 `tailscale up` error

### ISSUE THREAD

**Issue by owine** [tailscale/tailscale#12307]
### What is the issue?

After updating a working container to v1.66.4:

```
Error: changing settings via 'tailscale up' requires mentioning all
non-default flags. To proceed, either re-run your command with --reset or
use the command below to explicitly mention the current value of
all non-default settings:
```

I can only guess this related to the stateful filtering change introduced in this version

### Steps to reproduce

Update container image to v1.66.4

### Are there any recent changes that introduced the issue?

I am guessing the stateful filtering change introduced in v1.66.4

### OS

Linux

### OS version

Ubuntu 22.04 / Docker 26.1.3

### Tailscale version

v1.66.4

**Comment by owine** [comment]
Just to note, pinning the container to the `:v1.66.3` image tag restores it to a working state.

**Comment by irbekrm** [comment]
Hi @owine thank you for reporting the issue.

What's your Dockerfile config? To clarify- did you see the issue on after a bump from `v1.66.3` -> `v1.66.4` (with preserved tailscaled state)?

**Comment by owine** [comment]
> Hi @owine thank you for reporting the issue.
> 
> What's your Dockerfile config? To clarify- did you see the issue on after a bump from `v1.66.3` -> `v1.66.4` (with preserved tailscaled state)?

Indeed - preserved state (sorry, I should have mentioned that.) Here is my docker compose

```
  tailscale:
    image: tailscale/tailscale:latest
    container_name: ts4
    hostname: ts4
    environment:
      - TS_AUTHKEY=[redact]
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=ts4
    volumes:
      - /opt/appdata/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
```
