### ISSUE TITLE
IPV4-only subnet routers show "Unable to relay traffic" even though they are correct and working

### ISSUE THREAD

**Issue by disconn3ct** [tailscale/tailscale#12345]
### What is the issue?

Now that the k8s operator works on ipv4-only, there is an issue in the admin dashboard. IPV4-only subnet relays are showing the "Unable to relay traffic" warning. Inside the pod, `/proc/sys/net/ipv4/ip_forward` is 1 and using it as an exit node works.

### Steps to reproduce

Disable ipv6 on a machine hosting a subnet router

### OS

Linux

### OS version

Debian GNU/Linux 12 (bookworm)

### Tailscale version

1.66.4

### Other software

Running under k3s

**Comment by irbekrm** [comment]
Hi, thanks for opening the issue

> IPV4-only subnet relays are showing the "Unable to relay traffic" warning. Inside the pod, /proc/sys/net/ipv4/ip_forward is 1 and using it as an exit node works.

Could you clarify what you have deployed and how? Is it a subnet router or exit node, is it deployed via the operator?

> Now that the k8s operator works on ipv4-only

What do yo mean by this? The operator's proxies do not all support IPv6, but the one created for `Connector` does

**Comment by disconn3ct** [comment]
```yaml
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: cat-relay
spec:
  hostname: cat-relay
  exitNode: true
  subnetRouter:
    advertiseRoutes:
      - "11.11.11.11/32"
```
(plus a bunch of other /32s and a /15)

If I had to guess, I'd guess the check is failing because ipv6 forwarding doesn't exist on hosts that do not have ipv6.
