### ISSUE TITLE
In Kernel Space networking, nodes which advertise subnets routes CAN‘T forward traffic to LAN subnets.

### ISSUE THREAD

**Issue by wx2020** [tailscale/tailscale#12396]
### What is the issue?

I use Docker to deploy tailscale client. But I still want to let tailscale virtual network port be in my host machine so that I can use my other tailscale node ip directly anywhere on my host machine. So I set TS_USERSPACE to false, because I found that if I set it like this the tailscale virtual network port will appear in my host. But in this settings **I find a question**: I can't use my LAN ip to access my other devices in the same subnet as the tailscale client, even though I announced the subnet using TS_ROUTES in the configuration.

### Steps to reproduce

1. prepare docker-compose.yml, set tailscale container A
2. in docker-compose.yml, set A TS_USERSPACE to false
3. in other node, use LAN ip to access my other devices in the same subnet as the tailscale client A

### Are there any recent changes that introduced the issue?

Yes, I set TS_USERSPACE to false in my container.

### OS

Linux

### OS version

Docker on Ubuntu 22.04 LTS

### Tailscale version

1.66.3

### Other software

My Docker compose config:
```
  tailscaled:
    container_name: tailscaled
    image: tailscale/tailscale:stable
    environment:
      - TS_AUTHKEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - TS_ROUTES=192.168.100.0/24
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
      **- TS_USERSPACE=false**
    volumes:
      - /var/run/tailscale:/var/run/tailscale
      - /root/tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
```

In tailscale Admin console, I allow the Subnet routes:

![image](https://github.com/tailscale/tailscale/assets/35266946/07fc3794-103f-476d-a2dd-f241bdd911c2)

In the tailscale container A, I find the log about traffic forward, but my other node still CAN'T access LAN devices:

![image](https://github.com/tailscale/tailscale/assets/35266946/0d4c3317-1bf4-4ca1-9bed-178ebee077a7)

Please help me.
Thanks.

### Bug report

BUG-6f60917d2338371c5ec17c03e089158737d21661c6c2f1a0869193a9c0993133-20240607133243Z-50334bbc61012fbd
