### ISSUE TITLE
FR: "Default" flag for ProxyClass CR

### ISSUE THREAD

**Issue by ChandonPierre** [tailscale/tailscale#12421]
### What are you trying to do?

The `ProxyClass` CR allows an end-user to configure how they'd like the `Statefulset` proxy pods spawned by the operator to look. The operator provides minimal configuration, and the end-user configures the rest:

```
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: memory-limit
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          limits:
            memory: 2Gi
```

We then label the service we're exposing, and the operator will patch the `Statefulset` spec for the proxy:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
  labels:
    tailscale.com/proxy-class: memory-limit
```

There are settings I'd like to **asset to be true** for _every_ proxy pod however - I.E, Tailscale will not work without them. 

### How should we solve this?

Instead of adding an additional label to each service I annotate, I would prefer to define in my `ProxyClass` CR that I would like it to apply to _all_ operator controlled `Statefulsets` via a boolean flag ; e.g (not sure on naming here)

```
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
spec:
  applyToAll: true
```

### What is the impact of not solving this?

Outside of solving this in the operator code, we will likely add a mutating webhook to patch any exposed services for this. 

### Anything else?

Happy to take an approach with a PR, if this is desired functionality

**Comment by irbekrm** [comment]
Hi @ChandonPierre 

Thank you for writing up your use case.
I agree that it would be valuable to be able to have configuration applied to proxies without having to explicitly annotate each `Service`.

We will likely expand the `ProxyClass` concept slightly in the future. For example, right now we are working on a design for being able to untie the 1 <-> 1 relationship between the exposed Services and created tailnet proxy nodes (to be able to run the proxies in HA mode and also to not have to create a new tailnet node for each exposed Service) and `ProxyClass` will likely become the mechanism for specifying number of replicas to be created on top of which a number of Services get exposed. I think that with that model, having a mechanism that marks one `ProxyClass` as default will still make sense, but would like to get a bit further with HA before adding this field. Also, I am a bit wary of the fact that there won't be a good way to guarantee that only one 'default' `ProxyClass` gets created.
Perhaps we should set this via the operator. Would a mechanism where 'default' `ProxyClass` gets specified via operator's helm chart value or env var fit your workflow?

**Comment by irbekrm** [comment]
> hey @irbekrm is https://github.com/tailscale/tailscale/pull/12711 an acceptable approach?

@ChandonPierre sorry I missed the PR.

We need to sync the default `ProxyClass` idea with our in-progress HA proxy work that also assumes using `ProxyClass`.
I want to add the 'default' `ProxyClass` and your approach looks reasonable, but we need to finalize our HA design first (we've been slow with that).

Here's for some context:

_Currently_ we are thinking that a user would precreate a `ProxyClass` with a set number of replicas:
```
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: foo
spec:
   statefulSet:
    replicas 5
    ...
```

And then use the existing label mechanism to expose a `Service` on the replicas created for the `ProxyClass`.

The apporoach in your PR would _likely_ work for a default `ProxyClass` but there is a couple open questions/work we need to do before we can add this:

- we are still trying to understand if want to support running the existing model (`ProxyClass` with no replica count defined, a `StatefulSet` gets created as a `Service` is exposed) alongside the new HA model (`ProxyClass` defines replica count, exposed `Services` are proxied using pre-created `StatefulSet` with n replicas). If we do, we will not support migration

- if we support running both models alongside each other, we will need to understand what the behaviour should be if users apply a 'default' `ProxyClass` with/without replica count defined

- it would also be good to understand how common multi-ProxyClass clusters will be

These are all questions for us to figure out before - but if you have time to give us some more feedback/chat about the configuration in your clusters that would be really helpful too and we'd like to make sure that the HA design works for you
cc @tomhjp
