### ISSUE TITLE
Mullvad exit nodes not working on Tailscale docker containers in Synology

### ISSUE THREAD

**Issue by Jorundur** [tailscale/tailscale#12565]
### What is the issue?

I'm trying to set up a few docker containers on my Synology NAS.

Each container has a corresponding Tailscale sidecar container, like the [mealie example from the blog](https://tailscale.com/blog/docker-tailscale-guide#remote-access). They all work fine.

For one container, I'd like its Tailscale sidecar container to be set up to use a Mullvad exit node, so that traffic from it appears to be from another location. This is not working and any network requests from the container (both the main container and the TS sidecar) just hangs indefinitely - tested with `ping`, `traceroute`, etc. - all commands hang indefinitely with no output.

If I remove the exit node argument, then it works fine, just like all the other containers. Any help would be much appreciated.

Sidenote - I can set a Mullvad exit node on the NAS itself via the CLI and that works fine, i.e. `ping`, etc. works.

### Steps to reproduce

Example docker compose file (let's use mealie as the example use case here):

```yml
version: "3.2"
services:
  ts-mealie:
    image: tailscale/tailscale:latest
    container_name: ts-mealie
    hostname: mealie
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --exit-node=100.120.166.95 --reset
      - TS_SERVE_CONFIG=/config/mealie.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=true # set to 1.1.1.1 and 8.8.8.8 in admin console
    volumes:
      - ${DOCKERCONFDIR}/ts-mealie/state:/var/lib/tailscale
      - ${DOCKERCONFDIR}/ts-mealie/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0
    container_name: mealie
    network_mode: service:ts-mealie
    depends_on:
      - ts-mealie
    volumes:
      - mealie-data:/app/data/
    environment:
      - ALLOW_SIGNUP=true
    restart: unless-stopped
```

`mealie.json` is the same as in the Docker deep dive article linked above - I know that's working because I can always go to `https://mealie.myts-domain.ts.net`, regardless of the exit node being set or not.

### OS

Linux, Synology

### OS version

Synology DSM 7.2

### Tailscale version

1.68.1

### Bug report

BUG-648194364478384f6807dafd3e05edfc0cb3cf16e7c37e83402658cc8966c2b0-20240620233225Z-e09c143c97eebc5c

**Comment by cubagithub** [comment]
I was able to get this working by:

1. disabling `TS_ACCEPT_DNS` to stop pulling DNS from the control server, 
2. [defining a DNS server IP](https://docs.docker.com/engine/network/#custom-hosts) for the sidecar container,
3. setting extra arg `--exit-node-allow-lan-access` which I believe allows the sidecar container to send traffic back to its 'local' network, which is the docker network in this case.

### docker-compose.yml
```yaml
services:

  tailscale-sidecar:
    image: tailscale/tailscale:latest
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 1s
      timeout: 5s
      retries: 60
    container_name: tailscale-sidecar
    hostname: tailscale-sidecar
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - TS_AUTHKEY=${TS_KEY}
      - TS_EXTRA_ARGS=${TS_ARGS}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=false
    volumes:
      - ${DATA_ROOT}/tailscale-sidecar/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    logging:
      options:
        max-size: 10m
    ports:
      - 8088:80     # expose nginx port in docker host (in addition to the tailnet)
    dns:
     - ${TS_DNS}
     - 
  nginx:
    image: nginx
    container_name: nginx
    environment:
      - TZ=${TIMEZONE}
    depends_on:
      - tailscale-sidecar
    network_mode: service:tailscale-sidecar

```

### .env
```ini
## Tailscale
TS_KEY="tskey-auth-<GUID>"
TS_ARGS="--advertise-tags=tag:container --exit-node=<SUGGESTED_MULLVAD_PEER_IP> --exit-node-allow-lan-access --reset"
TS_DNS="<MULLVAD_PUBLIC_DNS_IP>"
```

### DNS lookup from sidecar
```bash
debian@host:~$ docker exec -it tailscale-sidecar sh
/ # nslookup google.co
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:
Name:   google.co
Address: 142.250.71.78

Non-authoritative answer:
Name:   google.co
Address: 2404:6800:4006:812::200e
```

Hope this helps you. Your issue may be related to outgoing traffic from `ping`, `traceroute` being sent out the exit node successfully but not receiving a response?
