### ISSUE TITLE
FR: tailscale operator: Add support for custom domains with tailscale IngressClass

### ISSUE THREAD

**Issue by gurchik** [tailscale/tailscale#12709]
### What are you trying to do?

Many people have a way to create publicly accessible services on Kubernetes with an ingress controller, a certificate issuer like `cert-manager`, and a DNS controller like `external-dns`. So for example, they could create an Ingress for their service using a hostname like `service.company.tld` and these parts work together to set up the public IP address, the certificate, and the DNS record.

If instead someone wanted to use this setup for a service that is only accessible with Tailscale, it would be great if all they had to do was change the IngressClass of their Ingress to `tailscale`. Frustratingly, this is so close to working, for example, the DNS controller automatically creates a CNAME record to `service.REDACTED.ts.net`. However, connections fail due to the Tailscale server responding with a certificate that was issued for the `ts.net` domain, not your `company.tld` domain.

### How should we solve this?

There are multiple possible solutions to this problem.

One solution could be that the Tailscale pod handle TLS termination itself using the data in the secret defined by the Ingress. In this case, `service.REDACTED.ts.net` could simply be an A record to the Tailscale Machine's IP. This is similar to how the Tailscale Operator enables access to Service resources, just with TLS termination.

Another solution could be that the Tailscale Operator reads the certificate from the secret and sends that to the `ts.net` server to handle the TLS connection with a custom certificate. However, this may be undesirable for Tailscale from a security standpoint. 

### What is the impact of not solving this?

There are multiple workarounds to this problem in the current state.

One way is to use a Service with the Tailscale annotations instead of an Ingress. This requires the application developer to perform their own TLS termination. This is undesirable due to the inconsistencies it would introduce if you have both public and private services. For example, if a developer wants to deploy a production service publicly and a development service behind Tailscale, it would be preferable if the differences between these two were kept to a minimum. Needing to perform TLS termination yourself for the latter case but not the former could be problematic.

Another workaround is to use Subnet Routers. If your internal applications are already using an Ingress controller running in your private network, then you simply need a Subnet Router to advertise those IPs. This is undesirable for two reasons. The first is that you lose the ability to control access to specific Kubernetes resources because the Ingress controller may be fronting many unrelated applications in the same cluster. The second reason is that the IP addresses for the ingress controller are often not static. When these IPs change, the Kubernetes ecosystem have ways to resolve this automatically (for example, external-dns can update DNS records whenever the Ingress's `Address` changes), but there is no such integration for Subnet Routers. You'd probably have to write your own custom Tailscale Operator Operator to do this.

### Anything else?

https://github.com/tailscale/tailscale/issues/10330 is a similar problem because if the Tailscale Operator could integrate with ingress controllers then the TLS termination problem is already solved. However, I think these should be considered separately as users may not need any of the features from an ingress controller besides the TLS termination.

https://github.com/tailscale/tailscale/issues/11253 is a similar problem but it relates to Kubernetes API access, not Kubernetes workloads themselves.

https://github.com/tailscale/tailscale/issues/4221 involves using a custom domain but doesn't address any of the TLS problems that would still remain when a custom domain is used.

**Comment by rowanmoul** [comment]
There should be another workaround, though I haven't tested it myself yet. You could expose your ingress controller with a LoadBalancer type service using the tailscale load balancer class, or using the `tailscale.com/expose` annotation. This would solve the second problem you mention above (changing IPs) but not the first (exposing only specific services), though it's fairly trivial to run multiple instances of ingress-nginx with different ingress classes, which could solve that issue).

All of that said, I strongly support this becomming natively supported by tailscale's own ingress proxies!

**Comment by james-nofrixion** [comment]
This is an issue for us also. Funnel is no good because we only want the service accessible to tailscale users, but with a 'sensible' hostname.

I've tried exposing services (both ClusterIP and LoadBalancer) that redirect to the nginx ingress pods, but it doesn't work.

I can live with putting an A record in the global DNS (although something via MagicDNS would be nice). However the tailscale ingress gives an TLS error due to the requested domain not matching the XXX.ts.net certificate.

FWIW, I think configuring the tailscale ingress class to use an existing secret for the TLS cert seems to make the most sense.

**Comment by beep-beep-beep-boop** [comment]
I created a `ingress-nginx` load balancer with the ingress class set to something else (`ingress-tailscale-custom`), and the `loadBalancerClass` set to `tailscale`, and pointed a domain w/ an `A` record at the internal (tailnet) IP it got and it seemed to work. I could also get a cert for it via cert-manager, using the DNS01 challenge, and just did it the same way you'd do it for an external ip.

I don't use `external-dns` so I'm not sure if it would work with that, but it lists the load balancer's internal (tailnet) ip in `kubectl get svc`, so i'd think it could get the information needed to setup the dns records. I think you could probably make one `A` record and `CNAME` everything else to it at least, to make changing IPs less annoying. 

here's my config for the `ingress-nginx` instance. note some of these values aren't necessary for this setup.

<details>
<summary>Click to expand</summary>

```yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-tailscale
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.1
    helm:
      valuesObject:
        controller:
          service:
            loadBalancerClass: tailscale
          allowSnippetAnnotations: true
          config:
            annotations-risk-level: Critical
            strict-validate-path-type: "false" # due to https://github.com/kubernetes/ingress-nginx/issues/11176 breaking paths like "/outpost.goauthentik.io"

          # -- This section refers to the creation of the IngressClass resource.
          # IngressClasses are immutable and cannot be changed after creation.
          # We do not support namespaced IngressClasses, yet, so a ClusterRole and a ClusterRoleBinding is required.
          ingressClassResource:
            # -- Name of the IngressClass
            name: tailscale-custom-ingress
            # -- Create the IngressClass or not
            enabled: true
            # -- If true, Ingresses without \`ingressClassName\` get assigned to this IngressClass on creation.
            # Ingress creation gets rejected if there are multiple default IngressClasses.
            # Ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class
            default: false
            # -- Annotations to be added to the IngressClass resource.
            annotations: {}
            # -- Controller of the IngressClass. An Ingress Controller looks for IngressClasses it should reconcile by this value.
            # This value is also being set as the \`--controller-class\` argument of this Ingress Controller.
            # Ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class
            controllerValue: k8s.io/ingress-nginx
            # -- Aliases of this IngressClass. Creates copies with identical settings but the respective alias as name.
            # Useful for development environments with only one Ingress Controller but production-like Ingress resources.
            # \`default\` gets enabled on the original IngressClass only.
            aliases: []
            # aliases:
            # - nginx-alias-1
            # - nginx-alias-2
            # -- A link to a custom resource containing additional configuration for the controller.
            # This is optional if the controller consuming this IngressClass does not require additional parameters.
            # Ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class
            parameters: {}
            # parameters:
            #   apiGroup: k8s.example.com
            #   kind: IngressParameters
            #   name: external-lb
          # -- For backwards compatibility with ingress.class annotation, use ingressClass.
          # Algorithm is as follows, first ingressClassName is considered, if not present, controller looks for ingress.class annotation
          ingressClass: tailscale-custom-ingress

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

```
</details>
