### ISSUE TITLE
rejected: tailscaled version is too old (out of sync with derper binary)

### ISSUE THREAD

**Issue by xinyunaha** [tailscale/tailscale#12879]
### What is the issue?

Hello Tailscale Team,
I hope this message finds you well. I am reaching out to bring to your attention an issue I've encountered while using the tailscale/tailscale Docker image. Currently, the image is on version 1.68.1, and it appears that this version is no longer compatible with the latest Tailscale infrastructure, as I'm experiencing connectivity issues.I kindly request an update of the tailscale/tailscale Docker image to include at least Tailscale version 1.70. 

### Steps to reproduce

This is my docker compose file:
```
  client:
    image: tailscale/tailscale:stable
    container_name: tailscale-client
    network_mode: "host"
    privileged: true
    environment:
      TS_EXTRA_ARGS: --netfilter-mode = off
    volumes:
      - ./tailscale:/var/run/tailscale
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    command: tailscaled
    restart: unless-stopped
```
And this is the result of running `tailscale version` after entering the container
```
root@netserver:/opt/docker/compose/headscale# docker exec -it tailscale-client /bin/sh
/ # tailscale version
1.68.1
  tailscale commit: 92eacec73f10616b2be7aae7a1ac53c8e44e9268
  go version: go1.22.4
/ # 
```

### OS

Linux

### OS version

debian12

### Tailscale version

1.70.0

### Other software

None
