### ISSUE TITLE
Issue with some traffic over funnel + docker

### ISSUE THREAD

**Issue by adriancaruana** [tailscale/tailscale#12942]
### What is the issue?

I'm using tailscale funnel in a docker container to access a service over the internet. This was all working fine, until today, when I simply did `docker-compose down` and then `docker-compose up` and began to see some strange behaviour. Some requests to my service work fine -- I see this in the container logs when a request works properly:

```
<my-container-name>  | 2024/07/28 21:28:35 Accept: TCP{100.XXX.XXX.XXX:65025 > 100.XXX.XXX.XXX:443} 64 tcp ok
<my-container-name>  | 2024/07/28 21:28:35 Accept: TCP{100.XXX.XXX.XXX:65025 > 100.XXX.XXX.XXX:443} 52 tcp non-syn
<my-container-name>  | 2024/07/28 21:28:35 Accept: TCP{100.XXX.XXX.XXX:65025 > 100.XXX.XXX.XXX:443} 1280 tcp non-syn
```

But, sometimes the requests _don't_ work (where they used to work fine before). When that happens, I see this in the logs:

```
<my-container-name>  | 2024/07/28 21:27:37 Drop: TCP{[XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX]:48656 > [XXXX:XXXX:XXXX::XXXX:XXXX]:1} 80 no rules matched
<my-container-name>  | 2024/07/28 21:27:37 Accept: TCP{[XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX]:48656 > [XXXX:XXXX:XXXX::XXXX:XXXX]:1} 72 tcp non-syn
<my-container-name>  | 2024/07/28 21:27:37 Accept: TCP{[XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX]:48656 > [XXXX:XXXX:XXXX::XXXX:XXXX]:1} 351 tcp non-syn
<my-container-name>  | 2024/07/28 21:27:38 [RATELIMIT] format("dns: resolver: forward: no upstream resolvers set, returning SERVFAIL") (3 dropped)
<my-container-name>  | 2024/07/28 21:27:38 dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
<my-container-name>  | 2024/07/28 21:27:38 dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
<my-container-name>  | 2024/07/28 21:27:38 dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
<my-container-name>  | 2024/07/28 21:27:38 dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
```

I'm not really sure what's going on here, but it seems to be some difference between ipv4 and ipv6 perhaps? (I really don't know). 

Here's some other details below:

My tailscale config:
```
{
  "TCP": {
    "443": {
      "HTTPS": true
    }
  },
  "Web": {
    "${TS_CERT_DOMAIN}:443": {
      "Handlers": {
        "/": {
          "Proxy": "http://127.0.0.1:8083"
        }
      }
    }
  },
  "AllowFunnel": {
    "${TS_CERT_DOMAIN}:443": true
  }
}
```

My docker-compose:
```yml
  my-container-name:
    image: tailscale/tailscale:latest
    container_name: my-container-name
    hostname: my-container-name
    environment:
      - TS_AUTHKEY=tskey-client-XXX...?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/config.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/state:/var/lib/tailscale
      - ${PWD}/ts-config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
```

Host: `tailscale netcheck`
```
Report:
	* UDP: true
	* IPv4: yes, X.X.X.X:35476
	* IPv6: no, but OS has support
	* MappingVariesByDestIP: false
	* HairPinning: false
	* PortMapping: UPnP
```

Container: `tailscale netcheck`
```
Report:
	* UDP: true
	* IPv4: yes, X.X.X.X:54753
	* IPv6: no, unavailable in OS
	* MappingVariesByDestIP: false
	* PortMapping:
```

Host: `cat /etc/resolv.conf`
```
# Generated by resolvconf
search tailXXXXX.ts.net
nameserver 100.100.100.100
```

Container: `cat /etc/resolv.conf`
```
search tailXXXXX.ts.net
nameserver 127.0.0.11
options ndots:0
```

Tailscale version (in container): 1.68.1
Tailscale version (on host): 1.66.4

Host is running on Linux. 

### Bug report

Host: `BUG-cb77030e662c9ea1c3a369d280c77714367fd6108a26b0474eb215762a66f573-20240729045515Z-8b31461b85707025`
Container: `BUG-0c73078a0c913610fde0223bbbbed1fa412818e0db2a6448ab6f3155b1cff8ca-20240729045554Z-68edabda868ad48c`
