### ISSUE TITLE
https backend

### ISSUE THREAD

**Issue by olinux-dev** [tailscale/tailscale#13226]
### What is the issue?

If I have an ingress that points to a backend that expects https, in a nginx ingress I can just set the annotations like: nginx.ingress.kubernetes.io/backend-protocol: "HTTPS". But is there a way that I could achieve the same with the tailscale operator?

### Steps to reproduce

deploy a pod that expects https traffic

### OS

Other

### OS version

kubernetes

### Tailscale version

1.70.0

**Comment by irbekrm** [comment]
Hi, we [detect https from port number/backend](https://github.com/tailscale/tailscale/blob/aedfb82876cd7d62ae808ac0064b5988cb9340dc/cmd/k8s-operator/ingress.go#L212), so you should be able to achieve the same if the backend port is 443 or named `https`.
Let us know if you have any issues.

**Comment by colabspecl** [comment]
I have the same issue, it is not working with this config:

```
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: default
spec:
  selector:
    app: node  # This should match the labels of your pod
  ports:
    - name: https
      port: 22900          # The Service exposes port 22900
      targetPort: 22900  # The Service forwards traffic to port 22900 on the pod
  type: ClusterIP
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-service
            port:
              name: https
  ingressClassName: tailscale
  tls:
    - hosts:
        - node-ingress
```
