### ISSUE TITLE
FR: Allow Ipset Usage in Tests

### ISSUE THREAD

**Issue by jason-riddle** [tailscale/tailscale#13254]
### What are you trying to do?

I am trying to test that my group and tag have proper access to use exit nodes by confirming if they have access to Google DNS server's. I want my group to be allowed to query the DNS servers and for the "tag:nobody" to not be able to query the exit nodes. Also, I want to make use of IPsets so that I can easily add IPs.

I have created the following example ACL policy to showcase this:

```json5
{
	"groups": {
		"group:example": ["example@gmail.com"],
	},

	"tagOwners": {
		"tag:nobody": ["group:example"],
	},

	"ipsets": {
		"ipset:google-dns": [
			"add 8.8.8.8",
			"add 8.8.4.4",
		],
	},

	"tests": [
		// Test that "group:example" can use exit nodes.
		{
			"src": "group:example",
			"allow": ["ipset:google-dns:*"],
		},

		// Test that "tag:nobody" cannot use exit nodes.
		{
			"src": "tag:nobody",
			"deny": ["ipset:google-dns:*"],
		},
	],

}
```

I also have the following Github Actions workflow to test this policy.

```yml
---
name: CI - Example

on:
  push: null
  pull_request: null
  workflow_dispatch: null

jobs:
  sync-acls:
    name: Sync ACLs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test ACLs
        uses: tailscale/gitops-acl-action@v1
        with:
          oauth-client-id: "${{ secrets.TS_OAUTH_CLIENT_ID }}"
          oauth-secret: "${{ secrets.TS_OAUTH_SECRET }}"
          tailnet: "${{ secrets.TS_TAILNET }}"
          policy-file: ci-example.hujson
          action: test
```

When running the tests, it fails with

```
For user group:example:
Errors found:
- [acl test error]: address ipset:google-dns:*: too many colons in address
For user tag:nobody:
Errors found:
- [acl test error]: address ipset:google-dns:*: too many colons in address
```

### How should we solve this?

Allow IPsets to be used in `tests`.

### What is the impact of not solving this?

I can write out the IP addresses by hand, so the impact is very low.
