### ISSUE TITLE
Docker: Failed to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)

### ISSUE THREAD

**Issue by pirate** [tailscale/tailscale#1356]
**Describe the bug**
When using the Dockerfile built from the v1.4.4 tag (or `main` as of 2021-02-17), Tailscale is unable to start.

**To Reproduce**

1. create this `docker-compose.yml`:
```yaml
version: '3.7'
services:
    tailscale:
        build: https://github.com/tailscale/tailscale.git#v1.4.4
        volumes:
            - /dev/net/tun:/dev/net/tun
        # privileged: true     # adding this makes no difference
        cap_add:
          - net_admin
          # - sys_admin        # adding this makes no difference
```
2. Run `docker-compose run tailscale tailscale up`, which produces this error:
```logs
Failed to connect to tailscaled. (safesocket.Connect: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory)
```

**Expected behavior**

Tailscale should start in the container independent from the host OS. e.g. I should be able to have tailscale running on my host, and a separate tailscale instance running inside the container that shows up as an independent tailscale host to other machines. I should not need to mount `/var/lib` as a volume or share other tailscale state between the host and container.

**Screenshots**

![image](https://user-images.githubusercontent.com/511499/108269982-c6125a00-713c-11eb-9879-644424cfe79a.png)

**Version information:**
 - OS: Ubuntu 20.04 host (amd64), Docker v20.10.3
 - Tailscale version: v1.4.4 (aka date.20210104)

**Relevant labels:** (just guessing here based on other issues)

`P3 Can't get started`, `T6 Major usability`, `containers`
