### ISSUE TITLE
Exposing tailnet service in Kubernetes will cause flux loop if doc is followed

### ISSUE THREAD

**Issue by Givemeurcookies** [tailscale/tailscale#13560]
### What is the issue?

Just a quick comment on the doc at https://tailscale.com/kb/1438/kubernetes-operator-cluster-egress

If you follow the documentation and use the code example with GitOps tool i.e Fluxcd, it will cause a reconciliation loop since the Operator updates the placeholder data for the "externalName" key and Flux will reset it back to the original every time it reconciles the Kustomization files. The issue might not be noticed unless you have flux monitoring set up.

Here's the particular code example:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: <Tailscale MagicDNS name>
  name: rds-staging   # service name
spec:
  externalName: placeholder   # any value - will be overwritten by operator
  type: ExternalName
  ```

To fix it, I simply removed the externalName variable from the manifest and this stopped the Flux issue and the operator inserts the correct value.

It's not something you might think of right away, so the doc should probably have a note related to GitOps tools and reconciliation issues as that type of setup is quite common.
