### ISSUE TITLE
Falco reports that the tailscale binary not part of the base image

### ISSUE THREAD

**Issue by samox73** [tailscale/tailscale#13595]
### What is the issue?

We are using [Falco](https://falco.org/) to monitor runtime activities in our K8s cluster. One of the default rules (`Drop and execute new binary in container`) is triggered because supposedly the binary `/usr/local/bin/tailscale` is not from the original base image of the container. However pulling and inspecting the image, it shows that the binary is indeed in the upper UpperDir. Is the binary perhaps modified during runtime so that this alert would be triggered?

Container Image: docker.io/tailscale/tailscale:v1.72.1

Falco Helm Chart:
Version: falco-4.8.1
```
driver:
  kind: modern_ebpf
  modernEbpf:
    leastPrivileged: false
falco:
  json_include_output_property: false
  json_output: true
tty: true
```

Tailscale Helm Chart:
Version: tailscale-operator-1.72.1
Values:
```
apiServerProxyConfig:
  mode: "true"
oauth:
  clientId: xxxxx
  clientSecret: xxxxx
operatorConfig:
  defaultTags:
  - tag:xxxxx
  hostname: xxxxx
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 10Mi
```

### Steps to reproduce

- install the mentioned charts in a K8s cluster
- create a tailscale ingress, so that a tailscale pod is created
- wait for falco to report the alert

### OS

Linux

### Tailscale version

1.72.1

### Other software

Falco 0.38.2
