### ISSUE TITLE
FR: provide official derp docker container

### ISSUE THREAD

**Issue by vsarunas** [tailscale/tailscale#13605]
### What are you trying to do?

Simplification of running own derp servers

### How should we solve this?

Create a new docker image or add derp into https://hub.docker.com/r/tailscale/tailscale

There is an official version https://github.com/fredliang44/derper-docker

**Comment by irbekrm** [comment]
Thanks for opening the issue.

Agree that we should do this, we just need to figure out the right configuration for containerized environment.

If you are currently running derp in a container and have any learnings from that, we'd be interested to hear.

**Comment by vsarunas** [comment]
Yes I'm and it works fine; Tailscale daemon it self runs on the host and socket access is provided in order to verify the clients:

docker-compose.yml:
```
version: '3.8'

services:
  derper:
    image: fredliang/derper:latest
    network_mode: "host"
    volumes:
      - /home/nginx:/app/certs:ro
      - /var/run/tailscale:/var/run/tailscale
    environment:
      - DERP_DOMAIN=<my_domain>
      - DERP_ADDR=:443
      - DERP_STUN_PORT=3478
      - DERP_HTTP_PORT=-1
      - DERP_VERIFY_CLIENTS=true
      - DERP_CERT_MODE=manual
```

This results with the following process:
```
/app/derper --hostname=$DERP_DOMAIN     --certmode=$DERP_CERT_MODE     --certdir=$DERP_CERT_DIR     --a=$DERP_ADDR     --stun=$DERP_STUN      --stun-port=$DERP_STUN_PORT     --http-port=$DERP_HTTP_PORT     --verify-clients=$DERP_VERIFY_CLIENTS     --verify-client-url=$DERP_VERIFY_CLIENT_URL
