### ISSUE TITLE
TS_USERSPACE=0 in docker container

### ISSUE THREAD

**Issue by truppelito** [tailscale/tailscale#13610]
### What is the issue?

I'm having an issue with Tailscale that for the life of me I cannot figure out. I have the following docker compose setup in both a Raspberry Pi 4 and an Ubuntu machine:

```
tailscale:
    image: tailscale/tailscale:v1.72.1
    container_name: tailscale
    restart: always
    network_mode: host
    hostname: server-1 # This will become the tailscale device name
    volumes:
        - ../volumes/tailscale/lib:/var/lib
        - /dev/net/tun:/dev/net/tun
    cap_add:
        - net_admin
        - net_raw
    environment:
        - TS_EXTRA_ARGS=--advertise-exit-node=false --accept-routes=true
        #- TS_USERSPACE=false # To allow other processes on this machine to access devices through Tailscale IPs. See: https://registry.hub.docker.com/r/tailscale/tailscale/
        - TS_STATE_DIR=/var/lib/tailscale
```

It works perfectly for incoming connections on both machines. But the moment I un-comment `TS_USERSPACE=false`, i.e. when I turn kernel networking on, my Ubuntu machine loses connection. Meaning, `ping 100.40.xxx.xxx` (tailscale IP of Ubuntu machine) works but `ping 10.22.33.xxx` (local IP of Ubuntu machine) times out (both pings done from another machine in the same local network). Furthermore, on the Raspberry Pi 4, kernel networking works without issues.

What am I doing wrong?

### OS

Linux

### OS version

Ubuntu 23.10 x86_64

### Tailscale version

1.72.1

### Other software

Docker version 27.1.1, build 6312585

### Bug report

BUG-9d8a1ec52f0ffae5365e653d1e43381cd3378ce1e4dea03a0f102f39cda8c2a5-20240927113959Z-38ade4ac898bc36f
