### ISSUE TITLE
FR: Support External Name Services for ingress proxies

### ISSUE THREAD

**Issue by aviau** [tailscale/tailscale#13806]
### What are you trying to do?

I woulld like to expose a service like so, where `hello` is an ExternalName service.
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale-hellp
  labels:
    component: support
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: hellp
      port:
        name: http
  tls:
    - hosts:
        - hello
```

**Comment by irbekrm** [comment]
Hi @aviau 

Thank you for opening the issue.

Would you be able to write up your use case as well? That would help us understand the user value better

**Comment by aviau** [comment]
Sure!

Here is my current situation.

## Current: Simple setup with network-level proxy

I have AWS OpenSearch in my VPC. I want to expose it via a tailscale proxy.

So I setup an ExternalName service and exposed it via `tailscale.com/expose: true`.

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: elasticsearch
  labels:
    component: support
  name: elasticsearch-private
spec:
  externalName: elasticsearch.internal.corp.com
  ports:
  - name: https
    port: 443
  type: ExternalName
```

Now I can access my OpenSearch instance using `curl https://elasticsearch.funny-name.ts.net --insecure`.

## What I want: application-layer proxy

Network-level proxies with ExternalName are cool for things that don't need HTTPs, but I would like to remove `--insecure` from the example above.

So, my proposed config would be:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale-elasticsearch
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: elasticsearch
      port:
        name: https
  tls:
    - hosts:
        - elasticsearch
```

This would setup and HTTPs server at `https://elasticsearch.funny-name.ts.net`. The cert would be generated just like other ingresses by tailscale and letsencrypt. Then it would forward all incomming requests to the externalname.

Something to keep in mind here: Tailscale would receive requests for `elasticsearch.funny-name.ts.net`, forward them to `elasticsearch` (the k8s service), but the service behind `elasticsearch` would have a TLS cert for `elasticsearch.internal.corp.com`, so we need to make sure that Tailscale verifies the cert for that name, not for `elasticsearch`.
