### ISSUE TITLE
FR: GRPC Support for Kubernetes Ingresses

### ISSUE THREAD

**Issue by aviau** [tailscale/tailscale#13854]
### What are you trying to do?

I would love to expose a GRPCs ingress using the tailscale kuberneted operator.

I would imagine it could have a config like so:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale-my-grpc-service
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: my-grpc-service
      port:
        number: 80
  tls:
    - hosts:
        - my-grpc-service
```

Then I would be able to access the service via `grpcs://my-grpc-service.funny-name.ts.net`

I inspired my suggestion from the nginx ingress controller config:
- https://kubernetes.github.io/ingress-nginx/examples/grpc/
