### ISSUE TITLE
Traffic stop after few minutes

### ISSUE THREAD

**Issue by Eisaichen** [tailscale/tailscale#13908]
### What is the issue?

I have a tailscale node deployed on the cloud, acting as an exit-node. But apparently, it will only work for a couple of minutes, works perfectly at the beginning, then starts to decline all the incoming traffic, including traffic to the internet and traffic to the associate subnets. If I restart the pod, it will start working for a couple of minutes and then the traffic stops again.

```
2024/10/24 19:38:21 magicsock: 2 active derp conns: derp-2=cr32m0s,wr30m0s derp-12=cr0s,wr0s
2024/10/24 19:38:21 derphttp.Client.Send: connecting to derp-12 (ord)
2024/10/24 19:38:21 magicsock: derp-12 connected; connGen=1
2024/10/24 19:38:51 netstack: decrementing connsInFlightByClient[100.66.8.68] because the packet was not handled; new value is 0
2024/10/24 19:39:04 netstack: decrementing connsInFlightByClient[100.66.8.68] because the packet was not handled; new value is 0
2024/10/24 19:39:21 magicsock: closing connection to derp-12 (idle), age 1m0s
2024/10/24 19:39:21 magicsock: 1 active derp conns: derp-2=cr33m0s,wr31m0s
2024/10/24 19:39:27 magicsock: adding connection to derp-12 for [WVfgr]
```
When declining, This "decrementing connsInFlightByClient" starts to show up in the logs. But no errors or anything abnormal.
Run `tailscale status` everything shows fine, with the opposite device directly connected.
```
100.66.8.68     samsung-sm-f    eisai@       android active; direct [2607::f4dc]:54201, tx 1616904 rx 1736552
```
Also, the admin panel looks normal
<img width="794" alt="image" src="https://github.com/user-attachments/assets/2e791319-879e-4775-9b7e-928db6e80648">
Config is simple, this node has a fixed WAN IP address and port.
<details>

```
        - name: tailscale
          image: tailscale/tailscale:stable
          imagePullPolicy: "Always"
          env:
            - name: TS_AUTH_ONCE
              value: 'true'
            - name: TS_ACCEPT_DNS
              value: 'false'
            - name: TS_EXTRA_ARGS
              value: '--advertise-exit-node --accept-routes=false --stateful-filtering=false'
            - name: TS_TAILSCALED_EXTRA_ARGS
              value: '--port 41641'
            - name: TS_USERSPACE
              value: "false"
            - name: TS_ROUTES
              value: '1.2.3.4/24'
            - name: TS_DEBUG_FIREWALL_MODE
              value: "nftables"
          volumeMounts:
            - name: tun
              mountPath: /dev/net/tun
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
      hostNetwork: true
      dnsPolicy: "ClusterFirstWithHostNet"
      enableServiceLinks: false
      volumes:
        - name: tun
          hostPath:
            path: /dev/net/tun
```
</details>
Only this node has this bizarre behavior, I have another node running a very similar config but working fine.

### OS

Linux

### OS version

6.5.0

### Tailscale version

1.76.1

### Other software

k8s

### Bug report

BUG-a01b85cdbd6a848efec787fb23f3df17a48cef225700f83c71e7845126433583-20241024201227Z-fe7452b0216a161b
