### ISSUE TITLE
netstack: could not connect to local backend server at 127.0.0.1:80: dial tcp 127.0.0.1:80: connect: connection refused

### ISSUE THREAD

**Issue by Joncallim** [tailscale/tailscale#13931]
## What is the issue?

So, I've been trying without luck to use the configuration at [this guide](https://tailscale.com/blog/docker-tailscale-guide) to have nice links for my self-hosted pages from my NAS. While I've managed to get the Nginx webserver to show up (literally the first few simple steps), anything else doesn't seem to work.

After going through the logs I found the error code `2024/10/28 10:51:22 netstack: could not connect to local backend server at 127.0.0.1:80: dial tcp 127.0.0.1:80: connect: connection refused`, no matter what port I was really trying to look at for a static webpage.

I'm currently trying to make this work with homer, which is one of the simplest examples I have running. I've tried resetting everything and starting from scratch, and it seems like everything else should be working (homer runs on port 8000 when not connected to ts-homer, and the tailscale machines page shows ts-homer as a funnel).

### Docker Compose File:
```
services:
  ts-homer:
    container_name: ts-homer
    image: tailscale/tailscale:latest
    hostname: homer
    environment:
      - TS_AUTHKEY=tskey-client-**notarealkey**?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/homer.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /volume1/docker/homer/ts-homer/state:/var/lib/tailscale
      - /volume1/docker/homer/ts-homer/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  homer:
    container_name: homer
    image: b4bz/homer
    network_mode: service:ts-homer
    depends_on:
      - ts-homer
    volumes:
      - /volume1/docker/homer:/www/assets
    user: 1234:123
    environment:
      - INIT_ASSETS=1 # default
    restart: unless-stopped
```

### JSON File:
```
{
  "TCP": {
    "443": {
      "HTTPS": true
    }
  },
  "Web": {
    "${TS_CERT_DOMAIN}:443": {
      "Handlers": {
        "/": {
          "Proxy": "http://127.0.0.1:8000"
        }
      }
    }
  },
  "AllowFunnel": {
    "${TS_CERT_DOMAIN}:443": false
  }
}
```

### Log Files
SSHing into my NAS and running `docker exec -it ts-homer netstat -pant` gives me:
```
 Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:42220        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:50751           0.0.0.0:*               LISTEN      11/tailscaled
tcp        0      0 192.168.224.2:35018     18.159.235.209:443      ESTABLISHED 11/tailscaled
tcp        0      0 127.0.0.1:8080          127.0.0.1:40804         TIME_WAIT   -
tcp        0      0 127.0.0.1:8080          127.0.0.1:40750         TIME_WAIT   -
tcp        0      0 192.168.224.2:58168     43.245.49.83:443        ESTABLISHED 11/tailscaled
tcp        0      0 192.168.224.2:50174     54.161.152.147:443      ESTABLISHED 11/tailscaled
tcp        0      0 :::8080                 :::*                    LISTEN      -
```

Finally, these are my logs for ts-homer:
```
boot: 2024/10/28 11:02:00 Startup complete, waiting for shutdown signal
boot: 2024/10/28 11:02:00 Applying serve config
2024/10/28 11:02:00 serve: creating a new proxy handler for http://127.0.0.1:8000
2024/10/28 11:03:07 wgengine: idle peer [VrfB4] now active, reconfiguring WireGuard
2024/10/28 11:03:07 wgengine: Reconfig: configuring userspace WireGuard config (with 1/7 peers)
2024/10/28 11:03:07 magicsock: disco: node [VrfB4] d:83dbdb728013570d now using 139.168.65.172:41641 mtu=1360 tx=0ad0d0803326
2024/10/28 11:03:07 netstack: could not connect to local backend server at 127.0.0.1:80: dial tcp 127.0.0.1:80: connect: connection refused
2024/10/28 11:03:07 netstack: could not connect to local backend server at 127.0.0.1:80: dial tcp 127.0.0.1:80: connect: connection refused
```

---

Any help at all would be GREATLY appreciated - I'm pulling my hair out here!

### OS

Synology DSM7

### Tailscale version

1.76.1
