### ISSUE TITLE
FR: Allow configuring operator port and hostnetwork

### ISSUE THREAD

**Issue by jaxxstorm** [tailscale/tailscale#13981]
### What are you trying to do?

Due to the nature of Kubernetes networking, there are sadly situations whereby we need to set host networking on the operator pod, and open a direct port to enable direct connections. 

### How should we solve this?

Add an env var to the pod and allow configurable host network

### What is the impact of not solving this?

User's trying to the operator proxy will see slow connections over relay

**Comment by nickjanssen** [comment]
For anyone hitting this issue with the Connector/subnet router pods, here's a workaround using Kyverno to mutate the StatefulSet:

```yaml
  apiVersion: kyverno.io/v1
  kind: Policy
  metadata:
    name: tailscale-subnet-router-hostnetwork
    namespace: tailscale
  spec:
    rules:
      - name: add-hostnetwork
        match:
          any:
            - resources:
                kinds:
                  - StatefulSet
                names:
                  - "ts-k8s-subnet-router-*"
        mutate:
          patchStrategicMerge:
            spec:
              template:
                spec:
                  hostNetwork: true
                  dnsPolicy: ClusterFirstWithHostNet
```

After applying the policy, delete the existing pod to trigger recreation with the mutation applied. This persists across operator reconciliations since Kyverno intercepts and mutates the StatefulSet at the admission controller level.
