### ISSUE TITLE
k8s-operator: Don't log transient optimistic locking failures as error level

### ISSUE THREAD

**Issue by tomhjp** [tailscale/tailscale#14072]
### What is the issue?

Several of the objects created by the operator's ProxyGroup controller are also updated by other controllers. This frequently causes error logs containing `"the object has been modified; please apply your changes to the latest version and try again"`. This is transient error that we expect to see from time to time in the control loop, and the next reconcile is highly likely to succeed applying the same changes, but it punts the ProxyGroup's status into an error state and prints a noisy error in the logs.

### Steps to reproduce

Deploy a `ProxyGroup` and tail the logs for the above error message. If not observed, scale the number of replicas up and down until observed.

```yaml
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: egress
spec:
  type: egress
  replicas: 2
  proxyClass: prod
```

### OS

Linux

### Tailscale version

1.76.6
