### ISSUE TITLE
Kubernetes Operator ProxyGroup replica ends up with an expired auth key

### ISSUE THREAD

**Issue by irbekrm** [tailscale/tailscale#14080]
### What is the issue?

After a [`ProxyGroup`](https://tailscale.com/kb/1236/kubernetes-operator?q=proxygroup#optional-pre-creating-a-proxygroup) recreation one of the replicas ended up with an apparently invalid auth key, from proxy's `Pod` logs:
```
...
2024/11/13 11:44:45 control: Generating a new nodekey.
2024/11/13 11:44:45 control: RegisterReq: onode= node=[QqeDx] fup=false nks=false
2024/11/13 11:44:46 control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=false; authURL=false
2024/11/13 11:44:46 Received error: invalid key: API key <key-id> not valid
2024/11/13 11:44:46 health(warnable=login-state): error: You are logged out. The last login error was: invalid key: API key <key-id> not valid
...
```

I cannot reproduce this at will. The key with this ID seems to not exist.
This needs more investigation.

### Tailscale version

A build from https://github.com/tailscale/tailscale/pull/14073/commits/881fa04b13abba2c5be85d83b017e48068c11efa

**Comment by tomhjp** [comment]
I saw a ProxyGroup pod get into a similar state where restarting never helped. In my case, the auth key existed in the db and had been used. The state secret for that pod was missing the `_current-profile` key, but was other fully populated with valid information for an authenticated tailnet device. Adding the `_current-profile` key with the correct value (base64-encoded `profile-84ed`) fixed it the next time it restarted.

I haven't been able to reproduce it yet, but it seems likely that the pod tried and failed to write `_current-profile` on its first run, and then every subsequent run was doomed because it no longer had a valid auth key (single-use) and didn't have valid state either.

Failing a reliable repro, the first thing to try is probably retries on the kube state store function, because there are a number of reasons I can see why that function could fail, especially if it's racing with another controller (kube, operator?) or process (containerboot).

**Comment by tomhjp** [comment]
> I haven't been able to reproduce it yet, but it seems likely that the pod tried and failed to write _current-profile on its first run, and then every subsequent run was doomed because it no longer had a valid auth key (single-use) and didn't have valid state either.

This was close but not quite right. I managed to dig out the correct logs and what actually happened was `kubelet` shut down the container just as tailscaled was writing its state towards the end of its startup sequence. As a result, there were 3 audit log entries for patching the state secret, with 2 of them at almost exactly the same time that `kubelet` logged "Stopping container tailscale". Tailscaled needs to make 4 patches to write a complete set of state keys (`_current-profile`, `_profiles`, `_machine-key`, and `profile-xxxx`), so it got interrupted just too early.

**Comment by ChaosInTheCRD** [comment]
I experienced something similar in a scenario where I:

1. Performed a `helm upgrade` of the operator (unstable version containing local operator changes)
2. Deleted all the pods in `-n tailscale` namespace (I feel this might have caught the proxy pods in a fragile state while they were establishing their connection with control
3. Observed a CrashLoop:
```
ingress-proxies-1 tailscale 2025/05/21 09:47:31 control: doLogin(regen=false, hasUrl=false)
ingress-proxies-1 tailscale 2025/05/21 09:47:31 control: Generating a new nodekey.
ingress-proxies-1 tailscale 2025/05/21 09:47:31 control: RegisterReq: onode= node=[GKPNK] fup=false nks=false
ingress-proxies-1 tailscale 2025/05/21 09:47:36 Received error: register request: http 500: Internal Server Error
ingress-proxies-1 tailscale REQ-20250521094731db609c7ad71ac436
ingress-proxies-1 tailscale 2025/05/21 09:47:36 health(warnable=login-state): error: You are logged out. The last login error was: register request: http 500: Internal Server Error
ingress-proxies-1 tailscale REQ-20250521094731db609c7ad71ac436
```
4. Checked the secrets for the crashlooping proxy pods:
```
apiVersion: v1
data:
  _machinekey: cHJp...
kind: Secret
metadata:
  labels:
    tailscale.com/managed: "true"
    tailscale.com/parent-resource: ingress-proxies
    tailscale.com/parent-resource-type: proxygroup
    tailscale.com/secret-type: state
  name: ingress-proxies-1
  namespace: tailscale
  ownerReferences:
  - apiVersion: tailscale.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ProxyGroup
    name: ingress-proxies
    uid: 532b125a-c0af-4d15-b846-031d403bde3b
type: Opaque
```

As seen above, it is lacking all data except the `_machinekey`
