### ISSUE TITLE
Total loss of connectivity in QNAP

### ISSUE THREAD

**Issue by ocalvo** [tailscale/tailscale#14224]
### What is the issue?

My qnap loses all connectivity after `tailscale` starts.
Only way to recover is to reboot and quickly disable or uninstall the `Tailscale` app in the AppCenter.

### Steps to reproduce

1. Update QNap with latest firmware.
2. Install Tailscale from the QNap store (version `1.40` at the time of writing this)
3. Reboot.
4. Connect to the tailscale network.

Expected:
Can access the qnap box locally
Actual:
Cannot access the qnap box both locally and remotely.

### Are there any recent changes that introduced the issue?

First time trying `tailscale` on QNap.

### OS

Linux

### OS version

QNap 5.2

### Tailscale version

1.40

**Comment by ocalvo** [comment]
I could try to test with version `1.70` but I am afraid of not being able to recover the box.

**Comment by intel66** [comment]
Same happened to me last week; Qnap TS453D. Had to stop Tailscale.

**Comment by ocalvo** [comment]
> Same happened to me last week; Qnap TS453D. Had to stop Tailscale.

What version of tailscale did you install? The one from the store or did you manually download the qnap package?

**Comment by intel66** [comment]
I have latest version (1.40.0-1) from store.
I found a solution:
Found owlery7's comment here: https://www.reddit.com/r/Tailscale/comments/18duw25/tailscale_fail_qnap_lan_ip_unreachable_after/

Started Tailscale on NAS, and was immediately disconnected, as usual. 
Used Terminal from my Mac to SSH to NAS' Tailscale IP-address.
Logged in and changed directory to Tailscale with command: «cd /share/CACHEDEV1_DATA/.qpkg/Tailscale».
Then ran the command "./tailscale up --accept-routes=false».
Got a reply: «Some peers are advertising routes but —accept-routes is false».

Now, I finally can connect via my LAN, as before.

**Comment by raizenica** [comment]
Yeah I can´t even SSH into it anymore not even with the tailscale IP,
Forced to reboot now and hope to intercept the tailscale process before it connects. :/

**Comment by JsmithCoding** [comment]
Got the very same issue.

Tried with the standard Tailscsale offered in QNap apps (v1.40) 

Tried installing manually Tailscale 1.74 from Tailscale packages at https://pkgs.tailscale.com/stable/#qpkgs

As soon as Tailscale is registered, the QNAP appliance is no longer reacheable on its regular LAN IP

Tried by setting the IP of QNAP at the "interface" level or the "virtual switch" level. Same issue.

The only way to get LAN connectivity again is to uninstall Tailscale; which by the way leaves the Tailscale DNS IP and requires to SSH to the appliance and modify the resolve.conf; or do something to the IP settings for this file to be updated.

**Comment by ULazdins** [comment]
Have the same issue. After installing Tailscale 1.40.0-1 from App Center, box looses all network connectivity.
Device: Qnap TS-451+
Firmware: QTS 5.2.7.3297

**Comment by mattlathrop** [comment]
I was also having connectivity issues and it turns out that tailscale was the culprit (1.40.0). Can someone from tailscale advise if we should be using the latest packages or what is going on here?

**Comment by emaba** [comment]
Still same problem on January 11th, 2026!!

**Comment by leszekw83** [comment]
Same issue even now. Total loss of internet on QNAP

**Comment by ULazdins** [comment]
fwiw, I'm currently overcoming this problem by running Tailscale in a container
**docker-compose.yml**
```
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    network_mode: host
    restart: unless-stopped
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTHKEY=tskey-auth-<redacted>
      - TS_ACCEPT_DNS=false
      - TS_EXTRA_ARGS=--advertise-routes=192.168.88.0/24 --advertise-exit-node
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
```
**docker-compose.resource.yml**
```
services:
  tailscale:
    cpus: 0
    cpuset: ""
    mem_limit: 0
    memswap_limit: 0
    mem_reservation: 0
```
