### ISSUE TITLE
FR: Operator: define a static ClusterIP in DNSProxy CRD

### ISSUE THREAD

**Issue by dorianm** [tailscale/tailscale#14305]
### What are you trying to do?

Define a custom IP for the Kubernetes service related to the `nameserver` deployed by the Kubernetes operator with the `DNSConfig` CRD. (see https://tailscale.com/kb/1438/kubernetes-operator-cluster-egress#expose-a-tailnet-https-service-to-your-cluster-workloads).

This allows us to have a static IP for this nameserver and configure our DNS service more easily (in GitOps, or IAC process).

### How should we solve this?

Maybe add some configuration in `DNSConfig` spec to define a static clusterIP (see https://kubernetes.io/docs/concepts/services-networking/service/#choosing-your-own-ip-address)

```yaml
apiVersion: tailscale.com/v1alpha1
kind: DNSConfig
metadata:
  name: ts-dns
spec:
  nameserver:
    image:
      repo: tailscale/k8s-nameserver
      tag: unstable
  service:
    clusterIP: a.b.c.d
```

### What is the impact of not solving this?

We have to (re)configure CoreDNS (or whatever DNS service we use) after the creation of the Kubernetes service by the operator. When we bootstrap our cluster in IAC/GitOps, it's not straightforward.
