### ISSUE TITLE
FR: Support defining additional init containers in the ProxyClass custom resource definition (helm chart)

### ISSUE THREAD

**Issue by AWildBeard** [tailscale/tailscale#14350]
### What are you trying to do?

I have a Kubernetes cluster which runs workloads behind a double NAT. One NAT at the gateway, the other the cluster itself. I can use Multus and macvlan CNI plugins to get Tailscale proxies to have an additional Layer2 network device outside of the cluster which allows them to only deal with 1 NAT (to support direct connections). In my case, the Gateway supports NAT-PMP and UPnP.

There is a problem however with this approach where many CNI plugins for overlay networks like Flannel and Calico don't easily or at all allow changing routing tables for containers. So without modifying the routing table for the Proxy when it starts, in my case, the Tailscale proxy is unable to reach the Kubernetes API and access it's tailscaled Secret resource in the cluster.

Currently, my solution is a manual one where I catch the container as it starts and manually add the route via `kubectl exec ...`

I could come up with a pretty convoluted workaround involving either admission controllers I impose ontop of the tailscale namespace, etc. but this involves a significant time investment when the solution on Tailscale's part is much easier...

### How should we solve this?

Tailscale should directly supported custom init container definitions in the ProxyClass custom resource definition. There is *limited* support to customize the `tailscaleInitContainer` field, but not in a meaningful way that would allow adding or removing routes from the pods route table.

An example ProxyClass definition that would meet this requirement would be;

```yaml
kind: ProxyClass
apiVersion: tailscale.com/v1alpha1
metadata:
    name: additional-init-containers-example
spec:
    statefulSet:
        pod: 
            annotations: # Add in a macvlan device to allow this pod to connect "around" the NAT implemented by Flannel & Calico
                k8s.v1.cni.cncf.io/networks: macvlan
            additionalInitContainers:
                - args:
                    - ip r a 10.43.0.0/16 via 10.42.1.1
                  command: 
                    - /bin/sh
                    - -c
                  ... etc
```

### What is the impact of not solving this?

Any custom CNI plugins that users wish to leverage to position the Tailscale proxies in better positions for network reasons (such as bypassing double NAT) will not be able to easily adjust the tailscale proxies for the changing network environment. Which would eliminate most out-of-the-box Kubernetes install's that exist in private subnets such as the clusters ran by large corporations in hybrid and private cloud environments (OpenShift, Rancher, etc...).

### Anything else?

The CNI plugin that allows customizing the routing table for pods (which is also supposed to be able to be used via Multus) doesn't appear to work in all cluster configurations, and certaintly not the three I tried (nil pointer issues). That CNI plugin may very well only work in OpenShift and OKD clusters to support KubeVirt usecases.
