### ISSUE TITLE
failed to auth tailscale with docker compose

### ISSUE THREAD

**Issue by thewh1teagle** [tailscale/tailscale#14425]
### What is the issue?

I'm trying to setup tailscale on raspbian lite with raspberry pi 4.
I used the the compose file from https://tailscale.com/kb/1282/docker
I created auth key in https://login.tailscale.com/admin/settings/keys and placed it in the compose file.
Then I ran it with `docker compose up` and it doesn't show up in devices. in the log I can see error:

```console
failed to auth tailscale
```

### Steps to reproduce

1. use the the compose file from https://tailscale.com/kb/1282/docker
2. I create auth key in https://login.tailscale.com/admin/settings/keys and placed it in the compose file.
3. `docker compose up`
Check if it's registered in machines https://login.tailscale.com/admin/machines

### OS

Linux

### OS version

Debian GNU/Linux 12 (bookworm)

### Tailscale version

v1.78.3-t1b41fdedd, Go 1.23.3:

### Bug report

Can't export it. the docker container restarting infinitly

**Comment by thewh1teagle** [comment]
I had to go to https://login.tailscale.com/admin/acls/file and add the following:

```console
"tagOwners": { "tag:container": ["autogroup:admin"] }
```

Then the authentication succeed. 
Can you please mention it in every docs related to docker / docker compose setup with tailscale?

The setup should be simple as:

## Tailscale on Raspberry PI with Docker

1. Install [Docker](https://docs.docker.com/engine/install/)
2. Save the following as `compose.yml`

<details>

```yml
# You must edit access control at https://login.tailscale.com/admin/acls/file
# and add the following: "tagOwners": { "tag:container": ["autogroup:admin"] }
services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: tailscale
    environment:
      - PUID=1000
      - PGID=1000
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      - TS_AUTHKEY=tskey-auth-kB4tAY7Lxq11CNTRL-X2BbJnXDTdLUfhZxfVLSdLurkM5FNBXwX
    volumes:
      - ./data:/var/lib
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    network_mode: host
    restart: unless-stopped
```
</details>

3. Create auth key in https://login.tailscale.com/admin/settings/keys and edit in `compose.yml`
4. Open https://login.tailscale.com/admin/acls/file and add `"tagOwners": { "tag:container": ["autogroup:admin"] }` to the config and save.
5. Run `docker compose up -d`

But it's important to mention the ACL part. why do we need to explicity add it?
