### ISSUE TITLE
netstack: could not connect to local backend server at 127.0.0.1:80: dial tcp 127.0.0.1:80: connect: connection refused

### ISSUE THREAD

**Issue by njack21** [tailscale/tailscale#14456]
### What is the issue?

I've been trying without luck to use the configuration at [this guide](https://tailscale.com/blog/docker-tailscale-guide) to have nice links for my self-hosted pages from my pi-server. WI've managed to get the Nginx webserver to show up without issue and have also configured the mealie example. I am unable to get anything else to work. 

I am now wanting to add another service, thelounge in my Tailscale network and am following the same guide. I noticed thelounge also uses port 9000, just like mealie, so I've tried different ports in the JSON configuration (thelounge.json)

**Current status**
* The Tailscale machine is created and is issued a certificate as expected.
* Machine shows as connected in Tailscale
* Unable to access the service
* Errors in logs:
    * netstack: could not connect to local backend server at 127.0.0.1:80: dial tcp 127.0.0.1:80: connect: connection refused
    *[RATELIMIT] format("netstack: could not connect to local backend server at %s: %v")

thelounge-compose.yml
```
services:
  ts-thelounge:
    image: tailscale/tailscale:latest
    container_name: ts-thelounge
    hostname: thelounge
    environment:
      - TS_AUTHKEY=tskey-client-[my-oauth-key]
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/thelounge.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TZ=America/Los_Angeles
    volumes:
      - $DOCKERDIR/appdata/ts-thelounge/state:/var/lib/tailscale
      - $DOCKERDIR/appdata/ts-thelounge/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  thelounge:
    image: thelounge/thelounge
    container_name: thelounge
    network_mode: service:ts-thelounge
    depends_on:
      - ts-thelounge
    restart: always
    volumes:
      - ~/.thelounge:/var/opt/thelounge # bind lounge config from the host's file system

volumes:
  ts-thelounge:
    driver: local
```

thelounge.json
```
{
  "TCP": {
    "443": {
      "HTTPS": true
    }
  },
  "Web": {
    "${TS_CERT_DOMAIN}:443": {
      "Handlers": {
        "/": {
          "Proxy": "http://127.0.0.1:9010"
        }
      }
    }
  },
  "AllowFunnel": {
    "${TS_CERT_DOMAIN}:443": false
  }
}
```

**curl output**
docker exec -it ts-thelounge apk add curl && curl http://127.0.0.1:9010
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/aarch64/APKINDEX.tar.gz
(1/6) Installing brotli-libs (1.0.9-r14)
(2/6) Installing libunistring (1.1-r1)
(3/6) Installing libidn2 (2.3.4-r1)
(4/6) Installing nghttp2-libs (1.57.0-r0)
(5/6) Installing libcurl (8.9.1-r1)
(6/6) Installing curl (8.9.1-r1)
Executing busybox-1.36.1-r7.trigger
OK: 26 MiB in 41 packages
curl: (7) Failed to connect to 127.0.0.1 port 9010 after 0 ms: Couldn't connect to server

**tailscale serve output**
docker exec -it ts-thelounge tailscale serve status:
https://thelounge.<mytailnet>.ts.net (tailnet only)
|-- / proxy http://127.0.0.1:9010

### Steps to reproduce

Pretty much everything in the above section.

### Are there any recent changes that introduced the issue?

Initial setup

### OS

Linux

### Tailscale version

1.78.1

### Other software

pinhole, but no related blocks

### Bug report

BUG-a686720151c8f620652c75673e3d2f25e20c1cc55467cd6a624b67bc6f8fdbf0-20241223024033Z-6ed3cbb2ed7503eb
