### ISSUE TITLE
HTTP endpoint not available on all interfaces

### ISSUE THREAD

**Issue by guyguy333** [tailscale/tailscale#14528]
### What is the issue?

HTTP endpoint is only reachable from localhost, not all interfaces.

Even if listen address is set to 0.0.0.0 or [::], HTTP endpoint is only reachable from localhost.

In a K8S context, HTTP endpoint is not available from its Pod IP. It breaks Health check and Metrics scraping.

```
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none 
    inet 100.100.0.20/32 scope global tailscale0
       valid_lft forever preferred_lft forever
    inet6 fd7a:115c:a1e0::14/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::7e3e:ba74:7ce:cb65/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
55928: eth0@if55929: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 16:22:23:4e:78:e1 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 100.64.3.105/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::1422:23ff:fe4e:78e1/64 scope link 
       valid_lft forever preferred_lft forever
/ # printenv | grep TS_LOCAL_ADDR_PORT
TS_LOCAL_ADDR_PORT=0.0.0.0:9002
/ # wget http://localhost:9002/metrics
Connecting to localhost:9002 ([::1]:9002)
saving to 'metrics'
metrics              100% |***************************************************************************************************************************************************************************************************************************|  2110  0:00:00 ETA
'metrics' saved
/ # wget http://100.64.3.105:9002/metrics
Connecting to 100.64.3.105:9002 (100.64.3.105:9002)
wget: can't connect to remote host (100.64.3.105): Operation timed out
```

### Steps to reproduce

Deploy a Tailscale pod in a K8S cluster and try to reach HTTP endpoint with its pod IP.

Enabled env vars:

```
- name: TS_ENABLE_HEALTH_CHECK
  value: "true"
- name: TS_LOCAL_ADDR_PORT
  value: "0.0.0.0:9002"
- name: TS_ENABLE_METRICS
  value: "true"
- name: TS_DEBUG_FIREWALL_MODE
  value: "auto"
- name: TS_KUBE_SECRET
  value: tailscale-auth
- name: TS_USERSPACE
  value: "false"
- name: TS_AUTHKEY
  valueFrom:
    secretKeyRef:
      name: tailscale-auth
      key: TS_AUTHKEY
      optional: false
- name: TS_DEST_IP
  value: 1.2.3.4
- name: TS_AUTH_ONCE
  value: "true"
```

### OS

Linux

### OS version

Ubuntu 22.04

### Tailscale version

1.78.3
