### ISSUE TITLE
FR: make the k8s-operator set ownerReferences for resource tracking

### ISSUE THREAD

**Issue by cromega** [tailscale/tailscale#14816]
### What are you trying to do?

We're running the k8s operator that manages some Connectors. It would be really helpful if the operator set owner references on the resources it manages so automated gitops tools such as argocd could discover the relationship between these resources and could correctly display what's in the cluster.

### How should we solve this?

An example statefulset created by a Connector could look something like this:

```
metadata:
  [...]
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: operator
    uid: abcdefabcdef-1234-1234-1234-abcdefabcdef
```

### What is the impact of not solving this?

Reduced visibility when using argocd or other gitops tools for managing kubernetes clusters.
