### ISSUE TITLE
Kubernetes ingress only proxying traffic to one pod

### ISSUE THREAD

**Issue by yquansah** [tailscale/tailscale#15140]
### What is the issue?

I have deployed a Kubernetes ingress in which the purpose is to direct traffic to a service in cluster from a tailnet Magic DNS name.

As I test making requests to the service via the tailnet, I am noticing that traffic is only ever directed to one pod behind a k8s service.

### Steps to reproduce

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 5
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - image: ealen/echo-server:latest
          imagePullPolicy: IfNotPresent
          name: echoserver
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
  type: ClusterIP
  selector:
    app: echoserver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver-ingress
spec:
  defaultBackend:
    service:
      name: echoserver
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - echoserver-ts
---
```

If you deploy this in a `minikube` cluster or wherever you have the tailscale operator running, and make requests to the associated address.

```
for i in {1..5}; do
  curl --silent https://echoserver-ts.antelope-royal.ts.net | jq '.environment.HOSTNAME'
done
"echoserver-688d6894c-rs5jf"
"echoserver-688d6894c-rs5jf"
"echoserver-688d6894c-rs5jf"
"echoserver-688d6894c-rs5jf"
"echoserver-688d6894c-rs5jf"
```

As you can see all traffic goes to one pod.

### OS

macOS

### OS version

macOS Sequoia 15.3.1

### Tailscale version

1.76.6

### Bug report

BUG-56147284035b34d840d1dde0e446ed37ca1d1eb19cdfe05e20308e3661d81b98-20250226152203Z-20665c4825e9ce1c
