### ISSUE TITLE
[Kubernetes] Tailscale Exit Sidecar blocks all internal network traffic (Including service network)

### ISSUE THREAD

**Issue by karbowiak** [tailscale/tailscale#15173]
### What is the issue?

Hi there, as i posted here a few weeks ago (https://github.com/tailscale/tailscale/issues/7695#issuecomment-2654063209) i recently tried setting up a tailscale sidecar for a container in kubernetes - using the mullvad exit.

However upon doing so, all internal network access gets cut off.
The Exit _DOES_ work, and traffic is routed through it - but even with tailscale set to allow local network connections, the service network can't access it.

What i would expect to happen is that the tailscale operator ingress can still access the webui of the container, while services internally can also still access it.
However the second the exit is running, it's all blocked.

(Initially i tried with just `--exit-node=100.73.22.4 --exit-node-allow-lan-access --hostname=sabnzbd-tailscale` but it also didn't work)

### Steps to reproduce

1. Have Tailscale operator installed to handle ingress
2. Setup something that uses it with the tailscale exit sidecar setup as well.. I've attached the example i also attached in the other post:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: sabnzbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
        app.kubernetes.io/name: sabnzbd
        app.kubernetes.io/component: sabnzbd
    spec:
      restartPolicy: Always
      containers:
        - name: tailscale
          image: tailscale/tailscale:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: "TS_KUBE_SECRET"
              value: "sabnzbd-exit-tailscale"
            - name: TS_USERSPACE
              value: "false"
            - name: TS_AUTH_KEY
              value: "tskey-auth"
            - name: TS_EXTRA_ARGS
              value: "--exit-node=100.73.22.4 --exit-node-allow-lan-access --accept-dns=false --snat-subnet-routes=false --hostname=sabnzbd-tailscale --reset"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          volumeMounts:
            - name: tailscale-state
              mountPath: /var/lib/tailscale
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          command: ["/bin/sh", "-c"]
          args: ["sleep 10 && exec /init"]
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: sabnzbd-extended-config
              mountPath: /config/extended.conf
              subPath: extended.conf
            - name: config
              mountPath: /custom-cont-init.d
              subPath: custom-cont-init.d
            - name: config
              mountPath: /custom-services.d
              subPath: custom-services.d
            - name: media
              mountPath: /storage
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: sabnzbd-extended-config
          configMap:
            name: sabnzbd-extended-config
        - name: media
          hostPath:
            path: /storage
            type: Directory
        - name: tailscale-state
          emptyDir: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - sabnzbd
    secretName: sabnzbd-tls
  defaultBackend:
    service:
      name: sabnzbd
      port:
        number: 8080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sabnzbd-tailscale
  namespace: sabnzbd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["sabnzbd-exit-tailscale"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sabnzbd-tailscale-binding
  namespace: sabnzbd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sabnzbd-tailscale
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sabnzbd
---
apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-exit-tailscale
  namespace: sabnzbd
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  selector:
    app: sabnzbd
  ports:
    - name: sabnzbd
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: sabnzbd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nvme
  resources:
    requests:
      storage: 50Gi
```

### Are there any recent changes that introduced the issue?

None that i am aware of

### OS version

Debian + k0s + Cilium (Everything default, service network lives on 10.0.0.0/8)

### Tailscale version

1.80

### Other software

- Cilium with default configuration
- K0s with default configuration
