### ISSUE TITLE
Docker - High CPU - [RATELIMIT] format("control: [v\x00JSON]%d%s")

### ISSUE THREAD

**Issue by plittlefield** [tailscale/tailscale#15339]
### What is the issue?

I updated to v1.80.3-tbd762b827, Go 1.23.5 on the Docker image and now the node running on the same machine as Headscale makes the server go into a frenzy with extremely high CPU usage on both the Tailscale container and the Headscale container ...

```
top - 15:06:17 up 10 min,  1 user,  load average: 2.07, 1.69, 1.37
Tasks: 427 total,   1 running, 426 sleeping,   0 stopped,   0 zombie
%Cpu(s): 41.2 us, 23.2 sy,  0.0 ni, 31.6 id,  0.0 wa,  0.0 hi,  1.4 si,  2.7 st
MiB Mem :   7836.0 total,    943.3 free,   3841.4 used,   3051.3 buff/cache
MiB Swap:   2048.0 total,   2048.0 free,      0.0 used.   3244.8 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  16268 root      20   0 1318796  88428  22852 S  67.5   1.1   0:30.20 tailscaled
   4039 root      20   0 1288628  66696  36960 S  46.7   0.8   0:47.87 headscale
```

... and this is the sanitised log file where the RATELIMIT lines come in every few seconds ...

```
tailscale  | 2025/03/17 15:05:32 health(warnable=warming-up): ok
tailscale  | 2025/03/17 15:05:32 health(warnable=no-derp-connection): ok
tailscale  | 2025/03/17 15:05:32 health(warnable=no-derp-connection): ok
tailscale  | 2025/03/17 15:05:32 [RATELIMIT] format("health(warnable=%s): ok")
tailscale  | boot: 2025/03/17 15:05:32 Startup complete, waiting for shutdown signal
tailscale  | 2025/03/17 15:05:32 magicsock: endpoints changed: xxxxxxxxxxxxxxxxxxxxxxxxxx
tailscale  | 2025/03/17 15:05:32 magicsock: derp-8 connected; connGen=1
tailscale  | 2025/03/17 15:05:42 [RATELIMIT] format("control: [v\x00JSON]%d%s") (201 dropped)
tailscale  | 2025/03/17 15:05:42 [RATELIMIT] format("control: [v\x00JSON]%d%s")
tailscale  | 2025/03/17 15:05:49 magicsock: disco: node [GYM4q] d:3440f535b22024fe now using xxxxxxxxxxxxxxxxx:41641 mtu=1360 tx=a9714db0733b
tailscale  | 2025/03/17 15:05:52 [RATELIMIT] format("control: [v\x00JSON]%d%s") (210 dropped)
tailscale  | 2025/03/17 15:05:52 [RATELIMIT] format("control: [v\x00JSON]%d%s")
tailscale  | 2025/03/17 15:06:02 [RATELIMIT] format("control: [v\x00JSON]%d%s") (193 dropped)
tailscale  | 2025/03/17 15:06:02 [RATELIMIT] format("control: [v\x00JSON]%d%s")
```

This is my docker compose file ...

```
services:
    tailscale:
        container_name: tailscale
        volumes:
            - /var/lib:/var/lib
            - /dev/net/tun:/dev/net/tun
        network_mode: host
        cap_add:
            - NET_ADMIN
            - NET_RAW
        privileged: true
        environment:
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=false
            - TS_EXTRA_ARGS=--login-server=https://headscale.xxxxxxxxx --advertise-exit-node --advertise-routes=10.2.0.0/24
            - TS_HOSTNAME=my-hostname
        image: tailscale/tailscale
        restart: unless-stopped
```

Hope you can help.

Regards,

Paully
