### ISSUE TITLE
tailscale container cannot reach other containers by name — only by IP

### ISSUE THREAD

**Issue by GentleHoneyLover** [tailscale/tailscale#15401]
### What is the issue?

A tailscale’s container cannot reach other containers on the user-created docker network by container name (i. e. internal docker name resolution doesn't work) — only by ip address. 

That creates a problem when you use tailescale as a side-car container to a reverse-proxy — you can reverse-proxy to services running in the tailnet (via tailsclae domain) but you cannot easily reverse-proxy to locally run services at the same time simply via `[container_name]:[port]` — you would have to reverse-proxy to an `[IP]:[port]` and have static IP configuration for the docker network and corresponding containers.

Use-case: running tailscale container on a VPS as a sidecar to a caddy container and reverse-proxying to a service hosted in the home lab and to a service hosted on VPS itself at the same time. 

### Steps to reproduce

1. Run tailscale with a few other containers on the same docker network (my example below):

```yaml
networks:

  proxy:
    name: proxy
    driver: bridge
    enable_ipv6: true

services:

  caddy-proxy:
    container_name: caddy-proxy
    image: docker.io/gentlehoneylover/caddy-godaddy-cloudflare
    restart: unless-stopped
    depends_on:
      - tailscale
    environment:
      - CLOUDFLARE_API_TOKEN=${CF_CADDY_TOKEN}
    volumes:
      - ${VLM_PATH}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${VLM_PATH}/caddy/data:/data
      - ${VLM_PATH}/caddy/config:/config
    network_mode: service:tailscale

  tailscale:
    container_name: tailscale
    hostname: my-vps
    image: docker.io/tailscale/tailscale:latest
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=${TS_KEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--advertise-exit-node --accept-routes
      - TS_ACCEPT_DNS=true
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${VLM_PATH}/tailscale/state:/var/lib/tailscale
    cap_add:
      - net_admin
      - sys_module
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - proxy

  node_exporter: 
    container_name: node_exporter
    image: docker.io/prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - ${VLM_PATH}/node_exporter/:/etc/node_exporter:ro
      - /:/host:ro,rslave
    command: '--path.rootfs=/host --collector.systemd --collector.processes'
    pid: host
    networks:
      - proxy
```
For reference, the `docker network inspect proxy` shows the following containers:
```json
"Containers": {
            "06ee4e681d7d541a7689836e7384cfe4804c1441300e45cfc0fa7ad48a559f5d": {
                "Name": "tailscale",
                "EndpointID": "998fa7035bf06ec8a9ca2a1b7fd33588426e24ce8aacef3781677a291ccd41c0",
                "MacAddress": "5e:a8:02:44:ca:dd",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": "fdd3:a99c:7b36:1::2/64"
            },
            "c8f3bb366fb57f5802e8fef386067417b13c46d9492a8f61939ea9011301d9ed": {
                "Name": "node_exporter",
                "EndpointID": "3e7bbe849cce72befe47905345b7b98ed3041bfb8e647bfd97aeed5c4eb5496a",
                "MacAddress": "ca:ac:5b:2d:dc:0c",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": "fdd3:a99c:7b36:1::3/64"
            }
        },
```

2. Enter the tailscale (or caddy) container via `docker exec -it tailscale sh`
3. Inside the container, run `ping node_exporter` and the output you get is `ping: node_exporter: Name does not resolve`. 
4. However, if you run `ping 172.19.0.3` or `ping fdd3:a99c:7b36:1::3` the ping runs successfully.

The expectation is that `ping node_exporter` correctly resolves to node_exporter's IP address (like it normally would in any other docker container).

### Are there any recent changes that introduced the issue?

N/A

### OS

Linux

### OS version

Ubuntu 24.04.2 LTS

### Tailscale version

1.80.3

### Other software

Docker version 28.0.2, build 0442a73

### Bug report

BUG-470cb79ad6c1033297f41fc2191d03d5a69fef6b003d386adaa0ef6f12886fa3-20250324134130Z-c9e749238b010841

**Comment by AbhinavS8** [comment]
Hi, I tried reproducing this issue using the same setup on a VM:

- Ubuntu 24.04
- Docker 28.0.2
- Tailscale 1.80.3
- `TS_ACCEPT_DNS=true`
- `network_mode: service:tailscale`
- User-defined bridge network with IPv6 enabled

full compose file:
```
services:
  caddy-proxy:
      image: caddy:2
      container_name: caddy-proxy
      restart: unless-stopped
      depends_on:
        - tailscale
      network_mode: service:tailscale
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile:ro

  tailscale:
    image: tailscale/tailscale:v1.80.3
    container_name: tailscale
    hostname: tailscale-test
    restart: unless-stopped
    environment:
      - TS_AUTHKEY={}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=true
    volumes:
      - ./tailscale-state:/var/lib/tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - proxy

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    pid: host
    command:
      - --path.rootfs=/host
    volumes:
      - /:/host:ro,rslave
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    enable_ipv6: true
```

I first created a sidecar container, then tried with an actual Caddy container sharing the Tailscale namespace. `ping node_exporter` works in both, even though `/etc/resolv.conf` contains only Tailscale's nameserver (`100.100.100.100`).

```
/ # ping node_exporter
PING node_exporter (172.18.0.2) 56(84) bytes of data.
64 bytes from node_exporter.tailscale-test_proxy (172.18.0.2): icmp_seq=1 ttl=64 time=0.045 ms
64 bytes from node_exporter.tailscale-test_proxy (172.18.0.2): icmp_seq=2 ttl=64 time=0.070 ms
64 bytes from node_exporter.tailscale-test_proxy (172.18.0.2): icmp_seq=3 ttl=64 time=0.057 ms
^C
--- node_exporter ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2029ms
rtt min/avg/max/mdev = 0.045/0.057/0.070/0.010 ms
```
I know this is an old issue, is it possible that the behavior has changed since then? Or is there another configuration to trigger the issue..
