### ISSUE TITLE
Kubernetes operator: enabling metrics on `ProxyClass` breaks pods in IPv6/IPv4 dual stack clusters

### ISSUE THREAD

**Issue by dhess** [tailscale/tailscale#15467]
### What is the issue?

Hi, thanks for the Kubernetes operator! It's an amazing feature of Tailscale.

We've been using the operator for quite awhile with great success. We recently learned about the metrics and `ServiceMonitor` support in `ProxyClass`, so we created a new `ProxyClass` with this feature:

```yaml
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: default
spec:
  metrics:
    enable: true
    serviceMonitor:
      enable: true
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          limits:
            squat.ai/tun: "1"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN
              - NET_RAW
```

(The new `ProxyClass` is otherwise more or less the same as the one we've been using.)

We made this the new default `ProxyClass` via the Helm chart value and applied the changes. When the existing pods restarted, they immediately began to crash loop with the following error:

```
boot: 2025/03/28 22:22:50 invalid configuration: invalid configuration: error parsing TS_LOCAL_ADDR_PORT value "2a00:<redacted>::1:1834:9002": invalid ip:port "2a00:<redacted>::1:1834:9002", IPv6 addresses must be surrounded by square brackets
```

(I've redacted part of the pod's IPv6 address for security reasons.)

Removing the `metrics` config from the new `ProxyClass` resolved the issue.

Our cluster is an IPv6/IPv4 dual stack cluster; i.e., the `$POD_IP` in our clusters is always an IPv6 address, even though pods are assigned both an IPv6 and an IPv4. All of the other components of the Tailscale pods work fine with this dual stack configuration, but apparently the metrics do not.

One interesting note is that before we changed our `ProxyClass` to enable metrics in this cluster, we created an identical `ProxyClass` (i.e., with metrics enabled) in another IPv6/IPv4 dual stack cluster with no existing Tailscale services or ingresses, and then deployed an exit node via a `Connector`. That exit node pod is running just fine, so for some reason, this bug doesn't appear to affect exit nodes deployed by the Operator.

### Steps to reproduce

1. Install the Tailscale Operator in an IPv6/IPv4 dual stack cluster. (I suspect the problem would also occur in an IPv6-only cluster.)
2. Create a default `ProxyClass` with metrics & a service monitor enabled.
3. Deploy a service with Tailscale annotations, or with a Tailscale ingress resource.

### Are there any recent changes that introduced the issue?

Unknown &mdash; we only enabled this feature for the first time today.

### OS

Linux

### OS version

Talos v1.9.5

### Tailscale version

Tailscale Operator v1.80.3

### Bug report

BUG-cfe99334b068932393ac34b8124514571d68ae61a08c0475786c45c5543a3738-20250328224344Z-5f39490e4c363b23
