### ISSUE TITLE
Tailscale Kubernetes Operator: "json.Encode: write unix /tmp/tailscaled.sock->@: write: broken pipe"

### ISSUE THREAD

**Issue by rajsinghtech** [tailscale/tailscale#15473]
### What is the issue?

K8s operator app connector pod encounters an error during operation and fails to shut down gracefully, resulting in a context deadline exceeded error when waiting for consistent state to be written to a Secret. The logs also show a `json.Encode: write unix /tmp/tailscaled.sock->@: write: broken pipe error`, suggesting a communication failure with the tailscaled daemon via its socket. 

### Steps to reproduce

``` YAML
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: app-connector
spec:
  proxyClass: prod
  tags:
    - tag:k8s
  hostname: robbinsdale-app-connector
  exitNode: false
  appConnector: {}
```

``` YAML
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: prod
spec:
  tailscale:
    acceptRoutes: true
  metrics:
    enable: true
    serviceMonitor:
      enable: true
```

### Are there any recent changes that introduced the issue?

N/A

### OS

Other

### OS version

Talos Linux

### Tailscale version

1.80.3

### Bug report

BUG-7cfc243657ba9c103eab054d8758c8e6fa8b757615206c4ce07992e234e2afdc-20250331015137Z-c79d3ee310d3513c
