### ISSUE TITLE
FR:  Support IRSA (IAM Roles for Service Accounts) in the Recorder CRD for tsrecorder

### ISSUE THREAD

**Issue by rajsinghtech** [tailscale/tailscale#15875]
### What are you trying to do?

I’d like the Tailscale Operator’s Recorder custom resource to natively support AWS IAM Roles for Service Accounts (IRSA) so that users can record SSH sessions to S3 without having to create and manage static AWS credentials in Kubernetes Secrets. I’m deploying the tsrecorder via the Recorder CRD on an EKS cluster and want it to assume an IAM role via the Kubernetes service account token mount (IRSA). Today the operator requires me to supply AWS access key and secret in a Secret, which I’d rather avoid for security and rotation reasons.

### How should we solve this?

Allow specifying a `serviceAccountName` in the Recorder spec (or via a new field under spec.statefulSet) so the Operator can use that SA when it creates the StatefulSet.

Detect when no AWS credentials Secret is provided, and if a serviceAccountName is set, configure the tsrecorder container to use the mounted IRSA token instead of looking for environment variables.
``` yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ts-recorder-sa
  namespace: tailscale
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/ts-recorder-role
```
### What is the impact of not solving this?

Operators and cluster admins must create, manage, and rotate long‑lived AWS keys in Kubernetes Secrets.

Increased risk from leaked credentials.

More operational overhead for teams who already use IRSA for other workloads.

### Anything else?

AWS SDKs automatically pick up the projected token under /var/run/secrets/eks.amazonaws.com/serviceaccount/token.

Similar IRSA support already exists in many community operators; following their model should simplify implementation.
