### ISSUE TITLE
Some `Ingress` configurations don't work with IPv6

### ISSUE THREAD

**Issue by dhess** [tailscale/tailscale#16047]
### What is the issue?

We've been using Tailscale `Ingresses` with the Kubernetes operator for quite awhile now with no issues. These have all been simple `Ingresses` serving a single service and using a `defaultBackend`.

Now we're deploying a service that serves both plain HTTP and gRPC on the same port, and so we need a more complicated `Ingress`. It looks like this:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    tailscale.com/tags: "tag:k8s"
  labels:
    app.kubernetes.io/component: omni
    app.kubernetes.io/instance: "test-a-omni"
    app.kubernetes.io/name: omni
    "app.kubernetes.io/part-of": omni
    app.kubernetes.io/version: v0.49.1
  name: omni
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - backend:
              service:
                name: omni
                port:
                  number: 8080
            path: /
            pathType: Prefix
          - backend:
              service:
                name: "omni-grpc"
                port:
                  number: 8080
            path: /cosi.resource.State
            pathType: Prefix
          - backend:
              service:
                name: "omni-grpc"
                port:
                  number: 8080
            path: /management.ManagementService
            pathType: Prefix
          - backend:
              service:
                name: "omni-grpc"
                port:
                  number: 8080
            path: /machine.MachineService
            pathType: Prefix
          - backend:
              service:
                name: "omni-grpc"
                port:
                  number: 8080
            path: /cluster.ClusterService
            pathType: Prefix
          - backend:
              service:
                name: "omni-grpc"
                port:
                  number: 8080
            path: /inspect.InspectService
            pathType: Prefix
          - backend:
              service:
                name: "omni-grpc"
                port:
                  number: 8080
            path: /resource.ResourceService
            pathType: Prefix
          - backend:
              service:
                name: "omni-grpc"
                port:
                  number: 8080
            path: /storage.StorageService
            pathType: Prefix
          - backend:
              service:
                name: "omni-grpc"
                port:
                  number: 8080
            path: /time.TimeService
            pathType: Prefix
          - backend:
              service:
                name: "omni-grpc"
                port:
                  number: 8080
            path: /auth.AuthService
            pathType: Prefix
          - backend:
              service:
                name: "omni-grpc"
                port:
                  number: 8080
            path: /oicd
            pathType: Prefix
  tls:
    - hosts:
        - omni
```

This cluster, like all of our clusters, including those where Tailscale `Ingresses` are working fine, are IPv6/IPv4 dual stack clusters; i.e., every pod's primary IP address is an IPv6 address. We have to disable IPv4 Tailnet addresses for these ingresses as explained here:

https://tailscale.com/kb/1439/kubernetes-operator-cluster-ingress?q=kubernetes+ipv6#ingress

Anyway, this particular ingress works fine for the `/` path, but attempts to use any of the gRPC prefixes results in the following error in the ingress pod's logs:

```
ts-omni-blkgx-0 tailscale boot: 2025/05/21 21:45:24 serve proxy: applying serve config
ts-omni-blkgx-0 tailscale 2025/05/21 21:45:24 serve: creating a new proxy handler for http://<redacted>:8::3f1f:8080/
ts-omni-blkgx-0 tailscale 2025/05/21 21:45:24 serve: creating a new proxy handler for http://<redacted>:8::de95:8080/inspect.InspectService
ts-omni-blkgx-0 tailscale 2025/05/21 21:45:24 serve: creating a new proxy handler for http://<redacted>:8::de95:8080/management.ManagementService
ts-omni-blkgx-0 tailscale 2025/05/21 21:45:24 serve: creating a new proxy handler for http://<redacted>:8::de95:8080/resource.ResourceService
ts-omni-blkgx-0 tailscale 2025/05/21 21:45:24 serve: creating a new proxy handler for http://<redacted>:8::de95:8080/storage.StorageService
ts-omni-blkgx-0 tailscale 2025/05/21 21:45:24 [RATELIMIT] format("serve: creating a new proxy handler for %s")
ts-omni-blkgx-0 tailscale boot: 2025/05/21 21:46:20 tailscaled config watch: ensuring that config is up to date
ts-omni-blkgx-0 tailscale boot: 2025/05/21 21:46:20 tailscaled config watch: config was reloaded
ts-omni-blkgx-0 tailscale 2025/05/21 21:47:58 wgengine: idle peer [t7bDb] now active, reconfiguring WireGuard
ts-omni-blkgx-0 tailscale 2025/05/21 21:47:58 wgengine: Reconfig: configuring userspace WireGuard config (with 1/24 peers)
ts-omni-blkgx-0 tailscale 2025/05/21 21:47:58 magicsock: disco: node [t7bDb] d:a495f41f89697a4b now using 10.8.1.22:54192 mtu=1360 tx=ec7ddce9884c
ts-omni-blkgx-0 tailscale 2025/05/21 21:47:59 cert("omni.<redacted>.ts.net"): registered ACME account.
ts-omni-blkgx-0 tailscale 2025/05/21 21:47:59 cert("omni.<redacted>.ts.net"): starting SetDNS call...
ts-omni-blkgx-0 tailscale 2025/05/21 21:48:11 cert("omni.<redacted>.ts.net"): did SetDNS
ts-omni-blkgx-0 tailscale 2025/05/21 21:48:13 cert("omni.<redacted>.ts.net"): requesting cert...
ts-omni-blkgx-0 tailscale 2025/05/21 21:48:14 cert("omni.<redacted>.ts.net"): got cert
ts-omni-blkgx-0 tailscale 2025/05/21 21:48:15 http: TLS handshake error from [fd7a:115c:a1e0:ab12:4843:cd96:6279:6f9a]:60009: remote error: tls: unknown certificate
ts-omni-blkgx-0 tailscale 2025/05/21 21:48:15 http: TLS handshake error from [fd7a:115c:a1e0:ab12:4843:cd96:6279:6f9a]:60010: remote error: tls: unknown certificate
ts-omni-blkgx-0 tailscale 2025/05/21 21:49:07 received a proxy request for plaintext gRPC
ts-omni-blkgx-0 tailscale 2025/05/21 21:49:07 http: proxy error: dial tcp: address <redacted>:8::de95:8080: too many colons in address
...
```

This is very similar to what we reported several months ago in https://github.com/tailscale/tailscale/issues/15467. Tailscale's proxy handlers aren't escaping IPv6 addresses properly.

### Steps to reproduce

See above.

### Are there any recent changes that introduced the issue?

Unknown as this is the first time we've enabled a non-trivial `Ingress`.

### OS

Other

### OS version

Talos v1.10.2

### Tailscale version

tailscale/k8s-operator:v1.82.5

### Bug report

BUG-91a47d4446a36c187ba981e5a6c8563efc3745025280627f0a64e782a19d21ca-20250521220855Z-11b8a48d8562c77b
