### ISSUE TITLE
TLS errors when using K8s Ingress and MagicDNS

### ISSUE THREAD

**Issue by joshfrench** [tailscale/tailscale#16057]
### What is the issue?

I'm trying to expose a k8s service to my tailnet using an Ingress. When I try to access it via the hostname alone, I get an SSL error:
```
% curl -v https://argocd-dev:443
* Host argocd-dev:443 was resolved.
* IPv6: (none)
* IPv4: 100.115.121.4
*   Trying 100.115.121.4:443...
* Connected to argocd-dev (100.115.121.4) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* LibreSSL/3.3.6: error:1404B438:SSL routines:ST_CONNECT:tlsv1 alert internal error
* Closing connection
curl: (35) LibreSSL/3.3.6: error:1404B438:SSL routines:ST_CONNECT:tlsv1 alert internal error
```

I can successfully connect to this service via its FQDN, and have verified that the cert is requested and stored in a secret as expected.

I can also expose it successfully via `tailscale.com/expose: "true"` annotation on the existing service, as well as through a service with `spec.type: LoadBalancer` and `spec.loadBalancerClass: tailscale`. Those options result in an endpoint with a self-signed cert however, which is what I'm trying to avoid by using an ingress.

This seems like it might be related to the certificate format:
```
% openssl s_client -connect argocd-dev:443 -prexit -showcerts
Connecting to 100.115.121.4
CONNECTED(00000005)
80CC46FD01000000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:ssl/record/rec_layer_s3.c:911:SSL alert number 80
---
no peer certificate available
---
No client certificate CA names sent
Negotiated TLS1.3 group: <NULL>
---
SSL handshake has read 7 bytes and written 1524 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Protocol: TLSv1.3
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

The same command with the FQDN shows valid certs:
```
% openssl s_client -connect argocd-dev.<our-tailnet>.ts.net:443 -prexit -showcerts
Connecting to 100.115.121.4
CONNECTED(00000005)
depth=2 C=US, O=Internet Security Research Group, CN=ISRG Root X1
verify return:1
depth=1 C=US, O=Let's Encrypt, CN=E6
verify return:1
depth=0 CN=argocd-dev.<our-tailnet>.ts.net
verify return:1
---
Certificate chain
 0 s:CN=argocd-dev.<our-tailnet>.ts.net
   i:C=US, O=Let's Encrypt, CN=E6
   a:PKEY: EC, (prime256v1); sigalg: ecdsa-with-SHA384
   v:NotBefore: May 22 14:37:58 2025 GMT; NotAfter: Aug 20 14:37:57 2025 GMT
```

### Steps to reproduce

Service:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
  name: argocd-server
  namespace: argocd
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
  type: ClusterIP
status:
  conditions:
  - lastTransitionTime: "2025-05-22T15:28:43Z"
    message: ProxyCreated
    reason: ProxyCreated
    status: "True"
    type: TailscaleProxyReady
  loadBalancer: {}
```

Ingress:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: argocd
  namespace: argocd
spec:
  defaultBackend:
    service:
      name: argocd-server
      port:
        name: https
  ingressClassName: tailscale
  tls:
  - hosts:
    - argocd-dev
status:
  loadBalancer:
    ingress:
    - hostname: argocd-dev.<our-tailnet>.ts.net
      ports:
      - port: 443
        protocol: TCP
```

```
% curl -I https://argocd-dev.<our-tailnet>.ts.net
HTTP/2 200

% curl -I https://argocd-dev
curl: (35) LibreSSL/3.3.6: error:1404B438:SSL routines:ST_CONNECT:tlsv1 alert internal error
```

### Are there any recent changes that introduced the issue?

No, this is a fresh install via the tailscale operator.

### OS

Linux

### OS version

Ubuntu 22.04.5

### Tailscale version

1.82.5

### Bug report

BUG-03da003ed0799027b8af6d6c6df78fd90bd6420a48a3d34b809370ab887d4fac-20250522160948Z-41498eb314af7924
