### ISSUE TITLE
Tailscale Docker (Sidecar) - Authentication broken with latest versions (failed to auth tailscale: failed to auth tailscale: tailscale up failed: exit status 2)

### ISSUE THREAD

**Issue by Owl-Tec** [tailscale/tailscale#16108]
### What is the issue?

Hi Everyone, 

When deploying the latest version of the Tailscale docker container with either the `tailscale/tailscale:stable` or `tailscale/tailscale:latest` tag, I receive the following error message within the logs:
```
boot: 2025/05/27 17:50:07 Sending SIGTERM to tailscaled
boot: 2025/05/27 17:50:07 failed to auth tailscale: failed to auth tailscale: tailscale up failed: exit status 2
2025/05/27 17:50:07 tailscaled got signal terminated; shutting down
2025/05/27 17:50:07 control: client.Shutdown ...
2025/05/27 17:50:07 control: updateRoutine: exiting
2025/05/27 17:50:07 control: mapRoutine: exiting
2025/05/27 17:50:07 control: authRoutine: exiting
2025/05/27 17:50:07 control: Client.Shutdown done.
```

As a result, my self-hosted web application is not accessible via Tailscale funnel and the Tailscale container enters into a restart loop as it attempts to authenticate before crashing and starting again. 

However, if I roll back the version of Tailscale to `tailscale/tailscale:v1.82` the container launches just fine and I am able to connect to my self-hosted application via Tailscale funnel.

Here is part of my compose file (containing the Tailscale container part):
```
  anuko-ts:
    image: tailscale/tailscale:latest
    container_name: timetracker-ts
    hostname: timetracker
    environment:
      - TS_AUTHKEY=tskey-XXX-XXX-XXX
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--accept-dns=true
      - TS_SERVE_CONFIG=/config/config.json
    volumes:
      - /volume1/docker/storage/timetracker/ts/state:/var/lib/tailscale
      - /volume1/docker/storage/timetracker/ts/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
```

Just to make sure it was not my `TS_AUTHKEY`, I generated a new one and the problem still persists.

**Comment by Owl-Tec** [comment]
> rolling back to v1.82 doesn't work for me. Container keeps restart looping, even after deleting the state folder.

Try going back even further. I started with V1.80 before I went to V1.82 and then stopped as every version after that was having issues.

**Comment by Major-Crash** [comment]
Removing the authkey from compose or .env files got them working for me.

**Comment by irbekrm** [comment]
Hi, thank you for opening the issue.

@Owl-Tec I think with your particular setup, the change we added in https://github.com/tailscale/tailscale/pull/15534 is breaking.

You are setting `--accept-dns` via `TS_EXTRA_ARGS` environment variable, but we also have a custom environment variable for this, [`TS_ACCEPT_DNS`](https://tailscale.com/kb/1282/docker#ts_accept_dns), so your configuration results in container running `tailscale up` with `accept-dns` provided twice, once set to false (as `TS_ACCEPT_DNS` is unset) and once set to true from `TS_EXTRA_ARGS`.
Would you be able to change the config to 
```
  anuko-ts:
    image: tailscale/tailscale:latest
    container_name: timetracker-ts
    hostname: timetracker
    environment:
      - TS_AUTHKEY=tskey-XXX-XXX-XXX
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ACCEPT_DNS=true
      - TS_SERVE_CONFIG=/config/config.json
    volumes:
      - /volume1/docker/storage/timetracker/ts/state:/var/lib/tailscale
      - /volume1/docker/storage/timetracker/ts/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
```

and let us know if that worked?

Apologies for the breaking change.

I think we need to add validation that `--accept-dns` is not set via `TS_EXTRA_ARGS`.

I don't know what configs other folks who commented on this issue have.
Looking at [the code](https://github.com/tailscale/tailscale/blob/b0d35975c0462a8499667ac7b52d685b5e90465a/cmd/containerboot/tailscaled.go#L115-L119) I don't see any other config options that could break because of this.
