### ISSUE TITLE
k8s-operator: DNSConfig + EgressProxy results in connection refused

### ISSUE THREAD

**Issue by rajsinghtech** [tailscale/tailscale#16178]
### What is the issue?

When using the default single instance egress proxy I am able to reach my egress service under `ts.net` domain with `DNSConfig`. The issue arrises when utilizing the `ProxyGroup`.

Single instance:
``` bash
network-debug-6498bf97cf-wds4p:~# curl -k -vvv https://ottawa-k8s-operator.argocd:443
* Host ottawa-k8s-operator.argocd:443 was resolved.
* IPv6: (none)
* IPv4: 10.1.3.57
*   Trying 10.1.3.57:443...
* Connected to ottawa-k8s-operator.argocd (10.1.3.57) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, internal error (592):
* OpenSSL/3.3.0: error:0A000438:SSL routines::tlsv1 alert internal error
* Closing connection
curl: (35) OpenSSL/3.3.0: error:0A000438:SSL routines::tlsv1 alert internal error
network-debug-6498bf97cf-wds4p:~# curl -k -vvv https://ottawa-k8s-operator.keiretsu.ts.net
* Host ottawa-k8s-operator.keiretsu.ts.net:443 was resolved.
* IPv6: (none)
* IPv4: 10.1.3.57
*   Trying 10.1.3.57:443...
* Connected to ottawa-k8s-operator.keiretsu.ts.net (10.1.3.57) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256 / x25519 / id-ecPublicKey
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=ottawa-k8s-operator.keiretsu.ts.net
*  start date: May  7 07:21:48 2025 GMT
*  expire date: Aug  5 07:21:47 2025 GMT
*  issuer: C=US; O=Let's Encrypt; CN=E5
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 1: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/1.x
> GET / HTTP/1.1
> Host: ottawa-k8s-operator.keiretsu.ts.net
> User-Agent: curl/8.7.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Request completely sent off
< HTTP/1.1 200 OK
< Audit-Id: 05446391-4743-449d-8574-50526fe04840
< Cache-Control: no-cache, private
< Content-Type: application/json
< Date: Tue, 03 Jun 2025 16:15:58 GMT
< X-Kubernetes-Pf-Flowschema-Uid: a774bf41-3b01-4309-8bfd-41c95115115a
< X-Kubernetes-Pf-Prioritylevel-Uid: a89ba59b-9227-4a3b-ac03-24e738b21a9d
< Transfer-Encoding: chunked
```

ProxyGroup:
``` bash
network-debug-6498bf97cf-wds4p:~# curl -k -vvv https://ottawa-k8s-operator.argocd:443
* Host ottawa-k8s-operator.argocd:443 was resolved.
* IPv6: (none)
* IPv4: 10.0.146.212
*   Trying 10.0.146.212:443...
* Connected to ottawa-k8s-operator.argocd (10.0.146.212) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, internal error (592):
* OpenSSL/3.3.0: error:0A000438:SSL routines::tlsv1 alert internal error
* Closing connection
curl: (35) OpenSSL/3.3.0: error:0A000438:SSL routines::tlsv1 alert internal error
network-debug-6498bf97cf-wds4p:~# curl -k -vvv https://ottawa-k8s-operator.keiretsu.ts.net
* Host ottawa-k8s-operator.keiretsu.ts.net:443 was resolved.
* IPv6: (none)
* IPv4: 10.1.2.213
*   Trying 10.1.2.213:443...
* connect to 10.1.2.213 port 443 from 10.1.1.186 port 49532 failed: Connection refused
* Failed to connect to ottawa-k8s-operator.keiretsu.ts.net port 443 after 16 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to ottawa-k8s-operator.keiretsu.ts.net port 443 after 16 ms: Couldn't connect to server
```

### Steps to reproduce

``` yaml
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: common
spec:
  metrics:
    enable: true
    serviceMonitor:
      enable: true
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: common-egress-proxy
spec:
  hostnamePrefix: common-egress-proxy
  tags:
    - tag:k8s
    - tag:egress
  proxyClass: common
  type: egress
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: robbinsdale-k8s-operator
  annotations:
    tailscale.com/tailnet-fqdn: robbinsdale-k8s-operator.keiretsu.ts.net
    tailscale.com/proxy-group: common-egress-proxy
spec:
  externalName: placeholder
  type: ExternalName
  ports:
  - name: https
    port: 443
    protocol: TCP
---
apiVersion: tailscale.com/v1alpha1
kind: DNSConfig
metadata:
  name: ts-dns
spec:
  nameserver:
    image:
      repo: tailscale/k8s-nameserver
      tag: unstable
```

### OS

Linux

### OS version

Talos v1.32.3

### Tailscale version

1.84.0
