### ISSUE TITLE
Only with TS_USERSPACE=true I can access my other docker networks

### ISSUE THREAD

**Issue by olonsoft** [tailscale/tailscale#16196]
I am running tailscale as a docker container on a linux server that has some more containers that I want to access from a remote location.
My linux server has IP `192.168.10.10` and my other docker containers are on `192.168.204.0/24` docker network.
My compose.yaml file is this:
```yaml
services:
  tailscale:
    image: ghcr.io/tailscale/tailscale:latest
    container_name: tailscale
    hostname: office
    privileged: true
    network_mode: host
    devices:
      - /dev/net/tun
    cap_add:
      - net_admin      
    volumes:
      - ./tailscale:/var/lib/tailscale
    environment:
      - TS_USERSPACE=true
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-exit-node --ssh --accept-routes
      - TS_ROUTES=192.168.10.0/24,192.168.204.0/24 
    restart: unless-stopped
```
I have accepted the routes from tailscale web dashboard.

I have created a docker network `ts-net` and a test container:
```yaml
 services:
  http_test:
    image: testcontainers/helloworld
    container_name: http_test
    restart: unless-stopped
    # ports:
     #  - 8080:8080 # commented to be visible only from ts-net network
    networks:
      ts-net:
        ipv4_address: 192.168.204.15

networks:
  ts-net:
    external: true
```
I have already done :
```sh
echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf
sudo sysctl -p /etc/sysctl.d/99-tailscale.conf
```

Everything works as expected.
I can see the `http_test` container from remote using `192.168.204.15:8080`

*My question is*:
Do I have to keep `TS_USERSPACE=true` ?
Setting this to `TS_USERSPACE=false`  :
**I can access** my other devices that are on  `192.168.10.0/24` network, **but not** the `192.168.204.0/24`network.
From a remote location, I can only ping `192.168.204.1` but not the service running on `192.168.204.15`
