### ISSUE TITLE
go.mod: keep our go version in sync with ./tool/go

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#16283]
These are out of sync:

```
bradfitz@tsdev:~/src/tailscale.com$ ./tool/go version
go version go1.24.4 linux/amd64

bradfitz@tsdev:~/src/tailscale.com$ grep ^go go.mod
go 1.24.0
```

I noticed that when the GitHub Actions CI was downloading exactly Go 1.24.0 on Windows to run the tests, because it uses:

```
    - name: Install Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: go.mod
```

/cc @tailscale/tooling
