### ISSUE TITLE
DNS Resolution Not Using Tailscale DNS Server in Kubernetes Cluster

### ISSUE THREAD

**Issue by V-Legendre** [tailscale/tailscale#16338]
## Description:

I am trying to reach an RDS instance with a public IP from a Kubernetes cluster using the Tailscale operator. The RDS instance is whitelisted in AWS security group rules, and there is an app connector in place. DNS resolution works correctly when targeting a Tailscale FQDN but fails when targeting a public IP or hostname, even when using ProxyClass and egress configurations.

## Context:
- I can reach my RDS instance from any local machine logged on my Tailscale network.
- I can reach hosts with a Tailscale FQDN from within my Kubernetes cluster using a service.
- I am using k3s as my Kubernetes distribution.

## Working Configuration (Tailscale FQDN):

When targeting a Tailscale FQDN, the following configuration works as expected:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: my.db-host.ts.net
  name: warehouse
  namespace: airbyte
spec:
  externalName: ts-warehouse-8ktrl.tailscale.svc.cluster.local
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  type: ExternalName
```

## Non-Working Configuration (Public IP/Hostname):

When attempting to target a public IP or hostname, DNS resolution does not use the Tailscale DNS server and resolves to the RDS public IP instead of the app connector IP. This issue persists even when using ProxyClass and egress configurations.

### ProxyClass Configuration:
```yaml
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: accept-routes
spec:
  tailscale:
    acceptRoutes: true
```

### Egress Service Configuration:
```yaml
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: accept-routes
spec:
  tailscale:
    acceptRoutes: true
```

## Troubleshooting Steps
- Verified that the Tailscale operator is running and joined the tailnet.
- Ensured that the app connector is properly configured and whitelisted in AWS security group rules.
- Confirmed that DNS resolution works correctly from local machines on the Tailscale network when using the Tailscale FQDN.
- Followed the documentation for accessing an IP address behind a subnet router, but the result was the same when targeting a public IP or hostname.

## Expected Behavior

DNS resolution should use the Tailscale DNS server and resolve to the IP of the app connector, allowing the Kubernetes cluster to reach the RDS instance through Tailscale, regardless of whether a Tailscale FQDN or a public IP/hostname is targeted.

## Actual Behavior

DNS resolution works correctly when targeting a Tailscale FQDN but resolves to the RDS public IP when targeting a public IP or hostname, bypassing the Tailscale DNS server and preventing access through Tailscale.

## Additional Information:

- Tailscale Operator Version:
  - Chart Version: tailscale-operator-1.82.5
  - App Version: v1.82.5
- Kubernetes Version:
  - Client Version: v1.33.1
  - Server Version: v1.32.3+k3s1

### OS

Linux

### OS version

Debian 12

### Tailscale version

1.82.5

### Other software

- Tailscale Operator Version:
  - Chart Version: tailscale-operator-1.82.5
  - App Version: v1.82.5
- Kubernetes Version:
  - Client Version: v1.33.1
  - Server Version: v1.32.3+k3s1

### Bug report

BUG-4c1cb507472032041c444da143d6e0d41cbfc10ff6a5cac5a2d727b94e121732-20250620150341Z-87cc59e15af0e4fd
