### ISSUE TITLE
Install script doesn't work on Ubuntu 19.10 (eoan)

### ISSUE THREAD

**Issue by Xe** [tailscale/tailscale#1936]
When using this image: https://cloud-images.ubuntu.com/releases/eoan/release/ubuntu-19.10-server-cloudimg-amd64.img `md5:f7a091a01a4235597fbfd5431e3f09fd` 
And this cloud-config:
```yaml
#cloud-config
#vim:syntax=yaml

cloud_config_modules:
 - runcmd

cloud_final_modules:
 - [users-groups, always]
 - [scripts-user, once-per-instance]

users:
  - name: xe
    groups: [ wheel ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    ssh-authorized-keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPg9gYKVglnO2HQodSJt4z4mNrUSUiyJQ7b+J798bwD9 cadey@shachi

write_files:
  - path: /etc/cloud/cloud.cfg.d/80_disable_network_after_firstboot.cfg
    content: |
      # Disable network configuration after first boot
      network:
        config: disabled

runcmd:
 - [ "sh", "-c", "curl https://raw.githubusercontent.com/tailscale/tailscale/Xe/test-install-script-libvirtd/scripts/installer.sh | sh" ]
 - [ systemctl, enable, --now, tailscaled.service ]
 - [ sh, "-c", "sleep 2" ]
```

Tailscale doesn't get installed. It fails at the `apt-get update` step of the script, which exits nonzero-ly and the script dies.

![image](https://user-images.githubusercontent.com/529003/118381064-16228080-b5b5-11eb-9a2c-3e678978ff61.png)

**Comment by Xe** [comment]
```yaml
#cloud-config
#vim:syntax=yaml

cloud_config_modules:
 - runcmd

cloud_final_modules:
 - [users-groups, always]
 - [scripts-user, once-per-instance]

users:
  - name: xe
    plain_text_passwd: hunter2
    groups: [ wheel ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    ssh-authorized-keys: 
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPg9gYKVglnO2HQodSJt4z4mNrUSUiyJQ7b+J798bwD9 cadey@shachi

write_files:
  - path: /etc/cloud/cloud.cfg.d/80_disable_network_after_firstboot.cfg
    content: |
      # Disable network configuration after first boot
      network:
        config: disabled

runcmd:
 - [ "sh", "-c", "sed -i.bak -r 's/(archive|security).ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list" ]
 - [ "sh", "-c", "curl https://raw.githubusercontent.com/tailscale/tailscale/Xe/test-install-script-libvirtd/scripts/installer.sh | sh" ]
 - [ systemctl, enable, --now, tailscaled.service ]
```
This script fixes the eoan install. We could try to detect that and warn the user, but I have a working setup now.
