### ISSUE TITLE
install script doesn't work on Debian 11

### ISSUE THREAD

**Issue by Xe** [tailscale/tailscale#1937]
When using this image: https://cdimage.debian.org/images/cloud/bullseye/daily/20210515-638/debian-11-generic-amd64-daily-20210515-638.qcow2 `md5:f53b3055410568969a20bd4fca925ed9`
And this cloud-config:

```yaml
#cloud-config
#vim:syntax=yaml

cloud_config_modules:
 - runcmd

cloud_final_modules:
 - [users-groups, always]
 - [scripts-user, once-per-instance]

users:
  - name: xe
    groups: [ wheel ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    ssh-authorized-keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPg9gYKVglnO2HQodSJt4z4mNrUSUiyJQ7b+J798bwD9 cadey@shachi

write_files:
  - path: /etc/cloud/cloud.cfg.d/80_disable_network_after_firstboot.cfg
    content: |
      # Disable network configuration after first boot
      network:
        config: disabled

runcmd:
 - [ apt-get, update ]
 - [ apt-get, install, "-y", curl, apt-transport-https, gnupg2 ]
 - [ "sh", "-c", "curl https://raw.githubusercontent.com/tailscale/tailscale/Xe/test-install-script-libvirtd/scripts/installer.sh | sh" ]
 - [ systemctl, enable, --now, tailscaled.service ]
```

Tailscale doesn't get installed. It fails at the version detection step with:

```
sh: 41: VERSION_CODENAME: parameter not set
```

Here are the contents of `/etc/os-release` and the output of `lsb_release -av`:
```console
xe@debian-11:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

xe@debian-11:~$ lsb_release -av
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        testing
Codename:       bullseye
```

It's worth noting that Debian 11 isn't fully released yet, I had to download a daily image.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_36itt)
