### ISSUE TITLE
FR: Dockerhub Parameters

### ISSUE THREAD

**Issue by jeryd** [tailscale/tailscale#3077]
### Tell us about your idea!

Parameters on the docker hub site for tailscale

### What are you trying to do?

I want to use the official docker for tail scale but without Parameters i dont know how to run it.

### How should we solve this?

Post instructions on the docker hub site (or just post a link back to somewhere else)

### What is the impact of not solving this?

I will continue to use a non official tailscale docker

### Anything else?

tailscale is the best. thank you.

**Comment by stealthybox** [comment]
There's some documentation here:
https://github.com/tailscale/tailscale/blob/main/Dockerfile#L16-L32

I also like to add `--hostname my-server` so that the name of the tailscale machine is more useful.

**Comment by airdrummingfool** [comment]
Just to add to this a bit, I'm trying out tailscale in Docker Compose, and it wasn't clear how to use it in that context. The way I'd prefer/expect it to work is that I could launch the service with an auth key environment variable and have it do everything for me, without needing to run `docker exec`, but as far as I can tell that's not available yet.

In case it is helpful, here's what I'm doing now; note that I have to run one command with `docker compose exec` to get things going.

Relevant part of docker-compose.yml:
```yml
services:
  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    command: tailscaled --tun=userspace-networking
    network_mode: host
    environment:
      AUTH_KEY: "tskey-my-key-here"
```

exec call:
```
# Get a container shell
docker compose exec tailscale /bin/sh

# In the container shell
> tailscale up --authkey $AUTH_KEY
```

thanks for this awesome product!

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/pull/4799/files added a number of parameters to `run.sh`

**Comment by airdrummingfool** [comment]
Since #4799 landed, I've been able to do everything I've wanted to do (which is just a basic setup where I provide the auth key and persist state between starts).

Here's my new `docker-compose.yml` Tailscale entry:
```yml
  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    volumes:
      - tailscale-state:/var/lib/tailscale/ # saves state to a volume
    network_mode: host
    env_file:
      - tailscale/secrets.env # this file provides TS_AUTH_KEY environment variable
    environment:
      - TS_STATE_DIR=/var/lib/tailscale/ # sets state directory env var so that state is persisted
      - TS_USERSPACE=true
      - TS_ACCEPT_DNS=false
```
