### ISSUE TITLE
tailscale in docker gets a new IP address every restart

### ISSUE THREAD

**Issue by cavedano8** [tailscale/tailscale#3780]
Hi all, i need help.
I use tailscale with a docker in a raspberry.
Everything is good but, when watchtower update the image, i must to re-login with "docker exec tailscaled tailscale up" command. So there is a new IP and edit a new machine name in tailscale console.

This is my docker-compose:

tailscale:
    container_name: tailscale
    image: tailscale/tailscale:stable
    cap_add:
      - NET_ADMIN
    command:
      - tailscaled
    volumes:
      - /var/lib/tailscaleorig:/var/lib/tailscaleorig
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    restart: unless-stopped

what am I doing wrong? Why is login not automatic?

**Comment by DentonGentry** [comment]
```
- /var/lib/tailscaleorig:/var/lib/tailscaleorig
```

That doesn't look right. tailscaled will store its state file in /var/lib/tailscale, the "orig" looks like something which snuck in during testing or something.

If /var/lib/tailscale is not in stable storage and will be lost every time the container restarts, you'd get the behavior described. It starts over as a new node every time.

**Comment by cavedano8** [comment]
Thanks @DentonGentry. I Will try and I will wait for the next updates

**Comment by DentonGentry** [comment]
As it is really clear that the container would get a new IP address if there is no persistent storage, I'm going to close this. If there is still a problem after the next restart of the container, please feel free to reopen.

**Comment by rishabgupta94** [comment]
@cavedano8 did it work out for you?
This is what my docker-compose looks like:

```
version: '3.9'
services:
  tailscale:
    image: tailscale/tailscale:v1.62.0
    container_name: tailscale
    cap_add:
      - NET_ADMIN
    environment:
      - TS_AUTH_KEY=${TS_AUTH_KEY}
      - TS_ROUTES=192.168.2.0/24
    volumes:
      - tailscale_data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    restart: unless-stopped

volumes:
  tailscale_data:
```
I checked the creation date of the `tailscale_data` volume and I am certain that the volume data is being persisted. However, anytime I restart my raspberry pi, Tailscale assigns a new IP address to it.

Can I please get some assistance regarding this? :)
