### ISSUE TITLE
Docker container sidecar service

### ISSUE THREAD

**Issue by pietersynthesis** [tailscale/tailscale#3893]
I'm trying to use the tailscale docker image as a sidecar service so I can connect to the container via my tailnet. Part of my approach is from [here](https://rnorth.org/tailscale-docker/) and I've also read the guide on [using Tailscale on Kubernetes](https://tailscale.com/kb/1185/kubernetes/), but I want to use the official container and would like to avoid moving my service deployment to Kubernetes if possible.

My docker-compose file:
```yaml
version: '3.3'
services:
  tailscaled:
    hostname: docker-sidecar
    container_name: tailscaled
    volumes:
      - './tailscale-data:/var/lib'
      - '/dev/net/tun:/dev/net/tun'
      - './connect.sh:/connect.sh'
    cap_add:
      - net_admin
      - sys_module
    network_mode: host
    privileged: true
    image: tailscale/tailscale
    command: ash connect.sh
  
  ubuntu:
    image: ubuntu:focal
    network_mode: 'service:tailscaled'
    depends_on:
      - tailscaled
```
What I'd like to be able to do is have the ubuntu container be reachable via my tailnet - the ubuntu container is simply a placeholder for my actual service.

I use the command override to run a 'connect.sh' script so I can start tailscaled and then connect using an authentication key. My connect.sh:
```bash
#!/bin/ash
echo "Starting TS daemon"
tailscaled &
sleep 3
echo "Connecting to network"
tailscale up --authkey=MY_AUTH_KEY
 ```

When I run `docker-compose up`, the logs of the tailscaled service are:
```Starting tailscaled ... done
Attaching to tailscaled
tailscaled    | 2022/02/09 06:09:20 logtail started
tailscaled    | 2022/02/09 06:09:20 Program starting: v1.20.2-t8e643357d, Go 1.17.6-tse44d304e54: []string{"tailscaled"}
tailscaled    | 2022/02/09 06:09:20 LogID: a89fbdcaed0a0be2444af2ffcff7635c7c6c24cfe1c9d50889efa7723227e666
tailscaled    | 2022/02/09 06:09:20 logpolicy: using system state directory "/var/lib/tailscale"
tailscaled    | 2022/02/09 06:09:20 wgengine.NewUserspaceEngine(tun "tailscale0") ...
tailscaled    | 2022/02/09 06:09:20 Linux kernel version: 5.13.0-28-generic
tailscaled    | 2022/02/09 06:09:20 is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: can't change directory to '/lib/modules': No such file or directory
tailscaled    | 2022/02/09 06:09:20 wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): device or resource busy
tailscaled    | 2022/02/09 06:09:20 flushing log.
tailscaled    | 2022/02/09 06:09:20 logger closing down
tailscaled    | 2022/02/09 06:09:20 logtail: dialed "log.tailscale.io:443" in 322ms
tailscaled    | 2022/02/09 06:09:21 logtail: upload: log upload of 604 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/08bf354099a11db6ba2a703cb6645d45553ba71fea7352461c16177bc7901d6a": context canceled
tailscaled    | 2022/02/09 06:09:21 createEngine: tstun.New("tailscale0"): device or resource busy
```

Any help would be greatly appreciated

**Comment by DentonGentry** [comment]
The error about the tun device is the one to focus on:
```
tailscaled | 2022/02/09 06:09:20 is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: can't change directory to '/lib/modules': No such file or directory
```

It is trying to `modprobe tun` and failing. That might be because, as it says, CONFIG_TUN was not defined in the host kernel.

**Comment by pietersynthesis** [comment]
> The error about the tun device is the one to focus on:
> 
> ```
> tailscaled | 2022/02/09 06:09:20 is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: can't change directory to '/lib/modules': No such file or directory
> ```
> 
> It is trying to `modprobe tun` and failing. That might be because, as it says, CONFIG_TUN was not defined in the host kernel.

Thanks for the reply, I ran `modprobe tun` on my Ubuntu host. After rebooting the server and running `docker-compose up` again, I get the same result.

**Comment by scyto** [comment]
I am hitting same issue with Debian and docker, this is my first time with tailscale, not the first time with docker...
did you find a fix?

`lsmod | grep tun` shows tun to be loaded
My compose had granted all prvis...

```
version: '3'
services:
  tailscale:
    image: tailscale/tailscale
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
    command:
      - tailscaled
    environment:
      - ROUTES=192.168.1.0/24
      - AUTHKEY=redacted
    volumes: 
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun 
    networks:
      - host

networks:
  host:
    external: true

**Comment by scyto** [comment]
@pietersynthesis  add 

i have moved two steps forward and one back now - try adding this volume to remove the mod probe error `      - /lib/modules:/lib/modules`
```
2022/02/15 00:11:35 logtail started
2022/02/15 00:11:35 Program starting: v1.20.4-t8e32002cf, Go 1.17.6-tse44d304e54: []string{"tailscaled"}
2022/02/15 00:11:35 LogID: 56d224f537a82703fa62763828a033f996d009dcdcb9e29e4b90b33d3f9636d1
2022/02/15 00:11:35 logpolicy: using system state directory "/var/lib/tailscale"
2022/02/15 00:11:35 wgengine.NewUserspaceEngine(tun "tailscale0") ...
2022/02/15 00:11:35 Linux kernel version: 5.10.0-11-amd64
2022/02/15 00:11:35 'modprobe tun' successful
2022/02/15 00:11:35 /dev/net/tun: Dcrw-rw-rw-
2022/02/15 00:11:35 wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): operation not permitted
2022/02/15 00:11:35 flushing log.
2022/02/15 00:11:35 logger closing down
2022/02/15 00:11:35 logtail: dialed "log.tailscale.io:443" in 72ms
2022/02/15 00:11:36 createEngine: tstun.New("tailscale0"): operation not permitted
```

**Comment by DentonGentry** [comment]
docker-compose does have a separate section for device special files. I've never understood it it does something differently than a volumes entry for `/dev/net/tun:/dev/net/tun`

```
    devices:
      - /dev/net/tun
    volumes: 
      - /var/lib:/var/lib
```

**Comment by scyto** [comment]
@DentonGentry well great suggestion (i am a 25 years windows guy and still get confused how devices appear in the filename space on linux)

However shifting the entry from volumes to dev  just generated a device not found 

I think in my sceanrio because of this

![image](https://user-images.githubusercontent.com/11369180/153970852-d47616c4-7b9b-42ed-8c71-ac38034e3dff.png)

**Comment by scyto** [comment]
I think my issue is now related to this (this describes my host and error)
https://github.com/tailscale/tailscale/issues/1457
should i move more questions to that or start a new issue?

**Comment by pietersynthesis** [comment]
Thanks for the comments, this is the first one that worked as expected:

docker-compose.yml:
```yaml
version: '3.3'
services:
  tailscaled:
    hostname: docker-nginx-sidecar
    container_name: tailscaled
    volumes:
      - './tailscale-data:/var/lib'
      - '/lib/modules:/lib/modules'
      - './connect.sh:/connect.sh'
    cap_add:
      - net_admin
      - sys_module
    privileged: true
    image: tailscale/tailscale
    command: ash connect.sh
  
  nginx-test:
    image: nginx
    network_mode: 'service:tailscaled'
    depends_on:
      - tailscaled
```
connect.sh:
```bash
#!/bin/ash
echo "Starting TS daemon"
tailscaled &
sleep 3
echo "Connecting to network"
tailscale up --authkey=mykey

tailscale status
sleep infinity
```
I'm open to more elegant ways of solving this, maybe there's unnecessary options provided, binding and executing a script inside the container isn't as nice as I'd like. Sleep infinity isn't what I'd like - but in the end this did work for me.
![image](https://user-images.githubusercontent.com/89873131/154008430-ad9de376-48df-4ca5-adc5-699fa4d452eb.png)
I can hit that nginx container over tailscale by hitting the 'docker-nginx-sidecar' IP assigned by tailscale.
