### ISSUE TITLE
--exit-node flag rejects node name argument

### ISSUE THREAD

**Issue by johannesdrescher** [tailscale/tailscale#4152]
### What is the issue?

The `--exit-node` flag should accept an IP or a node name.
```
--exit-node string
        Tailscale exit node (IP or base name) for internet traffic, or empty string to not use an exit node
```

For the initial `tailscale up` however, the node name option results in an error:

```
invalid value "my-exit-node" for --exit-node; must be IP or unique node name
```

After running the initial `tailscale up` and authenticating, it behaves as it should (the `--exit-node` flag accepts node names as well as IPs).

### Steps to reproduce

On a device with a fresh Tailscale installation (and no user data):

```
sudo tailscale up --exit-node my-exit-node
```

### OS

Linux

### Tailscale version

1.20.4

**Comment by bradfitz** [comment]
So this was actually originally by design. We didn't want it to be possible to specify an ambiguous exit node. When the network's down and you don't know your peers, you don't know where a node name points to (or who runs it).

Originally we required only an IP address. Later, for convenience, we compromised and said that if your network's already up, you can use the name because at that point it's clear which IP/owner runs that name.

We could loosen it further, but it'd give up the original paranoia.

Do you need to bring the network up & enable the exit node in one step?

/cc @danderson @mayakacz

**Comment by johannesdrescher** [comment]
@bradfitz Loosening it further might be a good idea. I'm using Tailscale in a GitHub Actions workflow. I could bring up the network and enable the exit node in two steps but I'd prefer to keep it simple and do it in one. 

The reason I would like to use the node name is that it is unlikely to change over time and I'd feel comfortable hard coding it into the workflow. I don't feel that way about the IP because it might change if the exit node is torn down and replaced.

**Comment by DentonGentry** [comment]
I don't see a really safe way to handle --exit-node=name in the initial `tailscale up`:

1. Before joining the tailnet we don't know the names of the other nodes
1. People specifying `tailscale up --exit-node=name` would reasnably expect that no traffic can leak onto the local LAN, but we don't have a good way to do that

I guess we'd need an exit-node-pending mode where we've joined the tailnet but won't allow any traffic until we figure out the exit node's name and activate the exit node. That seems like a lot of complexity.

**Comment by bradfitz** [comment]
> would reasonably expect that no traffic can leak onto the local LAN, but we don't have a good way to do that

But won't they only have that expectation one the `tailscale up` command returns with exit code 0? We can just block until it's up (I think we already do?) & the exit-node is resolved+configured. And if the name doesn't match, return an error code to the caller?

**Comment by DentonGentry** [comment]
I guess we could block until its up.

**Comment by jk563** [comment]
With the addition of Mullvad exit nodes I'd be keen to see this FR implemented — even if the compromise is that it only works for known mullvad / other provided exit nodes to reduce the unknown node owner risk.

**Comment by ClashTheBunny** [comment]
How is this best worked around with a more stateless situation like a kubernetes sidecar?  I assume some sort of init container that registers, waits for things to stableize, and then exits?  I tried to do something like that and couldn't get a clean "register" then exit from ghcr.io/tailscale/tailscale.  I had to manually start it up without the exit node, as I couldn't figure out a way for it to exit once a registration occurs in an init container.

**Comment by amontalban** [comment]
I'm having this issue using GitHub Actions, we had to recreate an exit node and the IP changed therefore I wanted to use the node name but it is not working. So I think it would be good to update help docs or command options to reflect that this does not work on first join.

As a workaround I had to do:

```
    - name: Tailscale - Initial
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
        hostname: tilt-pre-${{ github.run_id }}

    # Use MY_NODE as exit node to connect to the Kubernetes cluster
    - name: Get Exit node IP
      run: |
        TAILSCALE_EXIT_NODE="$(dig +short MY_NODE.MY_TAILNET.ts.net)"
        echo "TAILSCALE_EXIT_NODE=${TAILSCALE_EXIT_NODE}" >> "$GITHUB_ENV"

    - name: Tailscale - Exit node
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
        hostname: tilt-${{ github.run_id }}
        args: '--exit-node=${{ env.TAILSCALE_EXIT_NODE }}'
```

**Comment by notdurson** [comment]
+1, we need to use an exit node in an Action and I can't connect to the exit node in one shot. I'd love an `exit-node-pending` state.

**Comment by mstgrv** [comment]
I was about to post a fresh bug report but I think I might be experiencing this one. I'm running a simple Docker compose file which includes a Tailscale sidecar I'd like to connect to a Mullvad exit node using TS_EXTRA_ARGS. 

If I use the hostname of a given exit node, it fails with the same error from the OP - "invalid value "my-exit-node" for --exit-node; must be IP or unique node name". It only works if I use the IP address of the exit node.

**Comment by asavageiv** [comment]
Confirmed, I'm having the same issue with Tailscale as a docker sidecar. At a minimum the current error is misleading.

I was able to hack around it in docker like this:
```yaml
...snip...
  tailscale:
    image: tailscale/tailscale:latest
    # Hack to get IP address
    command: >
      sh -c "
        set -x
        export TS_EXTRA_ARGS=--exit-node=$$(getent hosts myhost.mytnet.ts.net | cut -d ' ' -f 1)
        exec /usr/local/bin/containerboot
      "
    container_name: tailscale
    hostname: myhost
    environment:
      TS_ACCEPT_DNS: true
      TS_AUTHKEY: ...snip...
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
    volumes:
...snip...
```

Obviously you'd need to put in the FQDN of your host in the `getent hosts` command.
