### ISSUE TITLE
Pass Auth Key to Container via Docker Compose Environment Variable?

### ISSUE THREAD

**Issue by Altycoder** [tailscale/tailscale#4353]
### What is the issue?

Can't seem to pass an ephemeral auth key to docker container when using docker compose, is this even possible?  I've tried several variations of the environment variable below including "AUTH_KEY", "authkey" and "AUTHKEY".

### Steps to reproduce

Docker compose:

```
  tailscale:
    image: ghcr.io/tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/lib:/var/lib
    devices:
      - /dev/net/tun:/dev/net/tun
    privileged: true
    environment:
      - AUTH_KEY="tskey-<redacted>"
```

### Are there any recent changes that introduced the issue?

New container

### OS

Linux

### OS version

Docker on top of Arch LTS host 

### Tailscale version

ghcr.io/tailscale/tailscale:latest
