### ISSUE TITLE
FR: Automatic enrollment in cloud environments

### ISSUE THREAD

**Issue by laferrieren** [tailscale/tailscale#5085]
### What are you trying to do?

I'm currently in the process of looking to leverage tailscalce to replace our cloud-to-cloud ip-sec tunnels in environment. To do this would need to install tailscale onto 100s of servers. I think it would be significant easier to roll it out if the agent supported some kind of auto enrollment feature like a few other software agents do. Just for reference okta asa does this already [link](https://help.okta.com/asa/en-us/Content/Topics/Adv_Server_Access/docs/features-by-platform.htm).

An example of something that could work would be having the agent pull in the enrollment key from an instance's metadata. This would allow me to bake tailscale into my golden images, and it join the tailnet automatically at launch based on which gcp project the machine is created in without having to have users add a user data script for their VMs or waiting for a configuration management engine to run after boot. 
NOTE: In gcp I can set a project level metadata so I just have to put the key into one place instead of pushing it each VM individually allowing me to manage the instances more like fleet.

### How should we solve this?

At service startup look for a specific [metadata](https://cloud.google.com/compute/docs/metadata/setting-custom-metadata) key in the instance metadata (maybe something like taiscale-auth-key) and if present use that as the authkey for connecting to the tailnet by default.

### What is the impact of not solving this?

Right now sticking to just using subnet routers and configuring them via user-data scripts.

**Comment by DentonGentry** [comment]
This could likely be implemented as a separate package, to be installed in the golden image along with the regular tailscale package. It would need to:
- mark its systemd unit file to run after tailscaled.service
- check if a cloud environment variable exists, or secret, or figure out what to do from instance metadata or something
- join the tailnet.

**Comment by mayakacz** [comment]
Tailscale can be installed via cloud-init: https://tailscale.com/kb/1293/cloud-init

**Comment by okmechak** [comment]
@mayakacz I have tried this solution in several combination, and unfortunately was not able to login into tailscale:
1.
```
....
late-commands:
  - curtin in-target --target=/target -- curl -fsSL https://tailscale.com/install.sh -o /install.sh
  - curtin in-target --target=/target -- sh /install.sh
  - curtin in-target --target=/target -- rm /install.sh
  - sudo curtin in-target --target=/target -- /usr/bin/tailscale login --authkey=tskey-clidfgggggggggggggggggggg?ephemeral=true --advertise-tags=tag:server
...
```
2.
```
    runcmd:
    - ['sh', '-c', 'curl -fsSL https://tailscale.com/install.sh | sh']
    - ['sh', '-c', "echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf && echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf && sudo sysctl -p /etc/sysctl.d/99-tailscale.conf" ]
    - ['tailscale', 'up', '--authkey=tskey-client-ggggggggggg-fffffffffffffff']
    - ['tailscale', 'set', '--ssh']
    - ['tailscale', 'set', '--advertise-exit-node']
```

3.
```
  cloud_config_modules:
  - runcmd
  cloud_final_modules:
  - scripts-user
  user-data:
    runcmd:
    - ['sh', '-c', 'curl -fsSL https://tailscale.com/install.sh | sh']
    - ['sh', '-c', "echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf && echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.d/99-tailscale.conf && sudo sysctl -p /etc/sysctl.d/99-tailscale.conf" ]
    - ['tailscale', 'up', '--authkey=tskey-client-kTECyh4CNTRL-fqASYjUpZZVELTgCAS6YWVTMDF8H7YjUJ']
    - ['tailscale', 'set', '--ssh']
    - ['tailscale', 'set', '--advertise-exit-node']
```

4. And finally this one which actually installed tailscale [source](https://gist.github.com/rossedman/87abb57aafb53030e881b410ea66ba4b)! But I am not able to login
```
apt:
    sources:
      tailscale.list:
        source: deb https://pkgs.tailscale.com/stable/ubuntu focal main
        keyid: 2596A99EAAB33821893C0A79458CA832957F5868
  packages: 
  - tailscale
```

[Here](https://askubuntu.com/questions/1506835/could-not-login-into-tailscale-during-ubuntu-auto-installation) is same question on Ubuntu.
