### ISSUE TITLE
tailscale running as sidecar in docker container with SSH: I can ssh into tailscale container, but not nginx

### ISSUE THREAD

**Issue by millsag** [tailscale/tailscale#5215]
related to #https://github.com/tailscale/tailscale/issues/3893

I have the following docker-compose.yml:
```yaml
version: '3.3'
services:
  tailscaled:
    hostname: docker-nginx-sidecar
    container_name: tailscaled
    volumes:
      - './tailscale-data:/var/lib'
      - '/lib/modules:/lib/modules'
      - './connect.sh:/connect.sh'
    cap_add:
      - net_admin
      - sys_module
    privileged: true
    image: tailscale/tailscale
    command: ash connect.sh
  
  nginx-test:
    image: nginx
    network_mode: 'service:tailscaled'
    depends_on:
      - tailscaled
```

and this is connect.sh:
```bash
#!/bin/ash
echo "Starting TS daemon"
tailscaled &
sleep 3
echo "Connecting to network"
tailscale up  --ssh --authkey=mykey

tailscale status
sleep infinity
```

When I run this, everything works and I see it in my console:
![image](https://user-images.githubusercontent.com/36576403/181635817-7908b48e-74ba-423f-be4f-b6ded6feb8ca.png)

However, when I ssh into that IP, I'm in the tailscale container. I need to be able to ssh into the nginx-test container. Is that possible? If I go to the URL via web browser, I see the nginx page, but I need to ssh into the nginx container, as well.
