### ISSUE TITLE
[Feat] tailscale status should provide an explicit status indication if the node is not yet connected

### ISSUE THREAD

**Issue by artis3n** [tailscale/tailscale#545]
**Is your feature request related to a problem? Please describe.**

I was recently debugging an idempotence issue in my Tailscale Ansible role. The following task was running every time when it used to be idempotent:

```yml
- name: Bring Tailscale Up
  become: yes
  # The command module cannot use | ; &
  # So we are ok not quoting the variables
  command: tailscale up --authkey={{ tailscale_auth_key }} {{ tailscale_args | default() }}
  # Since the auth key is included in this task, we do not want to log output
  no_log: true
  register: tailscale_start
  changed_when: tailscale_start.stderr != "\ntailscaled is authenticated, nothing more to do."
  notify: Confirm Tailscale
```

The difference is that now, if the Tailscale node is _already authenticated_, then a repeated invocation of `tailscale up` no longer returns a stderr message. It has this output:

```
ok: [instance] => {
        "tailscale_start": {
            "changed": true,
            "cmd": [
                "tailscale",
                "up",
                "--authkey=<redacted>"
            ],
            "delta": "0:00:07.075806",
            "end": "2020-07-11 16:17:11.040867",
            "failed": false,
            "rc": 0,
            "start": "2020-07-11 16:17:03.965061",
            "stderr": "",
            "stderr_lines": [],
            "stdout": "",
            "stdout_lines": []
        }
    }
```

Which is fine if we no longer want the stderr message `\ntailscaled is authenticated, nothing more to do.`.

So, to regain an idempotence check, I noticed that `tailscale status` behaves differently when the node is authenticated/connected vs. not. If the node is connected, then `tailscale status` delivers information about the Tailscale network.

If the node is not connected - which is the case when it is not yet authenticated, so I'm using that - then `tailscale status` returns no stdout or stderr. It's exit status is `0`.

```
    ok: [instance] => {
        "tailscale_status": {
            "changed": false,
            "cmd": [
                "tailscale",
                "status"
            ],
            "delta": "0:00:00.395397",
            "end": "2020-07-11 16:17:02.955342",
            "failed": false,
            "rc": 0,
            "start": "2020-07-11 16:17:02.559945",
            "stderr": "",
            "stderr_lines": [],
            "stdout": "",
            "stdout_lines": []
        }
    }
```

I am assuming the implicit assumption of exit code 0 with no stdout content signifies the status of the node is that it is not yet connected. However, that is ambiguous. `tailscale status` should be more explicit in the current status of the node if the node is not connected.

**Describe the solution you'd like**

`tailscale status` either exits with a particular non-zero exit code to signify it is not connected, or it returns some stdout/stderr message signifying the same. Some form of explicit status indication instead of the implicit no message/exit code 0 => your status is bad.

**Describe alternatives you've considered**

Documentation in the Tailscale docs telling people to disregard status code and that no output from `tailscale status` means you're in an unconnected state. I feel that's less useful to folks compared to a clear indication from the command line, but it is an alternative.

**Additional context**

None
