### ISSUE TITLE
sidecar.yaml uses incorrect value for the kubernetes secret variable

### ISSUE THREAD

**Issue by tleerai** [tailscale/tailscale#5653]
### What is the issue?

The [README.md](https://github.com/tailscale/tailscale/blob/main/docs/k8s/README.md?plain=1#L19) file for the k8s documentation advises users to create a secret with string data which does not match the value being used in the sidecar.yaml:

```
   stringData:
     TS_AUTH_KEY: tskey-...
```

However the [sidecar container](https://github.com/tailscale/tailscale/blob/main/docs/k8s/sidecar.yaml#L26) is actually instructed to use a different name:

```
    - name: TS_AUTH_KEY
      valueFrom:
        secretKeyRef:
          name: tailscale-auth
          key: AUTH_KEY
          optional: true
```
