### ISSUE TITLE
Kubernetes cluster with Calico can't establish direct connections 

### ISSUE THREAD

**Issue by dvcrn** [tailscale/tailscale#6157]
### What is the issue?

Running a managed kubernetes cluster that's using Calico for networking, the default Calico settings give tailscale a very hard time getting a direct connection going. That's in contrast to cilium where out-of-the-box tailscale has no issues getting a direct connection 

The host is setup to allow direct connections and has no blocking rules. Direct connection from/to the host is working fine, host is also able to have direct connections to the pods, but external access to the tailscale sidecards directly will always go through a relay

### Steps to reproduce

- Create k8s cluster with Calico CNI 
- Create a deployment with ts-sidecar configuration:

```
        - name: ts-sidecar
          imagePullPolicy: Always
          image: "ghcr.io/tailscale/tailscale:latest"
          env:
            - name: TS_SOCKET
              value: "/var/run/tailscale/tailscaled.sock"
            - name: TS_KUBE_SECRET
              value: "tailscale"
            - name: TS_USERSPACE
              value: "false"
            - name: TS_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTH_KEY
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
```

Calico DaemonSet env:

```
        - env:
            - name: DATASTORE_TYPE
              value: kubernetes
            - name: WAIT_FOR_DATASTORE
              value: "true"
            - name: NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  key: calico_backend
                  name: calico-config
            - name: IP_AUTODETECTION_METHOD
              value: interface=enp.*
            - name: CLUSTER_TYPE
              value: k8s,bgp
            - name: IP
              value: autodetect
            - name: IP6
              value: autodetect
            - name: CALICO_IPV4POOL_IPIP
              value: Never
            - name: CALICO_IPV4POOL_VXLAN
              value: Always
            - name: CALICO_IPV6POOL_VXLAN
              value: Always
            - name: FELIX_IPINIPMTU
              valueFrom:
                configMapKeyRef:
                  key: veth_mtu
                  name: calico-config
            - name: FELIX_VXLANMTU
              valueFrom:
                configMapKeyRef:
                  key: veth_mtu
                  name: calico-config
            - name: FELIX_WIREGUARDMTU
              valueFrom:
                configMapKeyRef:
                  key: veth_mtu
                  name: calico-config
            - name: CALICO_IPV4POOL_CIDR
              value: xxx
            - name: CALICO_IPV6POOL_CIDR
              value: xxx
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: ACCEPT
            - name: FELIX_IPV6SUPPORT
              value: "true"
            - name: FELIX_HEALTHENABLED
              value: "true"
          envFrom:
            - configMapRef:
                name: kubernetes-services-endpoint
                optional: true
```

### OS

Linux

### Tailscale version

1.32.2

### Bug report

BUG-29bf6fa8dfde61fb8512a09228e5dd3824caa02884b473199b9626c0ae698bc2-20221101102020Z-e34479754b97f824
