### ISSUE TITLE
failed to connect to local tailscaled

### ISSUE THREAD

**Issue by lheido** [tailscale/tailscale#6190]
### What is the issue?

Hi,

I'm trying to use the tailscale/tailscale docker image as a base image.
The build process seems to be working but when I ssh into the container and try a tailscale cmd :
`failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)`

Additional info: My server (host) (Ubuntu server 22) also run tailscale and it works well.

### Steps to reproduce

My Dockerfile:
```Dockerfile
FROM tailscale/tailscale:latest

RUN apk add --no-cache curl \
    wget \
    git \
    openssh-client \
    sudo \
    nodejs \
    npm 

ARG PROJECT_NAME
WORKDIR /workspace/${PROJECT_NAME}
```

and my docker-compose.yaml file:
```yaml
version: "3"

services:
  workspace:
    privileged: true
    build:
      network: host
      context: ../
      args:
        - PROJECT_NAME=my-project
    tty: true
    network_mode: "host"
    volumes:
      - /home/my-user/.ssh/:/root/.ssh/:ro
      - ./var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    entrypoint:
      ["sh"]
```

### OS

Linux

### OS version

Ubuntu 22 as host and Alpine as base image
