### ISSUE TITLE
Losing IP address on docker restart even though I am using a persistent volume

### ISSUE THREAD

**Issue by vladkosarev** [tailscale/tailscale#6362]
### What is the issue?

I am running tailscale in docker and any time the container restarts it gets a new IP and a duplicate entry appears in TS UI.

### Steps to reproduce

Here's my docker-compose.yml
```
version: '3'                                                                    
services:  
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    hostname: tailscale
    environment:
      - PUID=1000
      - PGID=1000
      - TS_USERSPACE=true
      - TS_AUTH_KEY=redacted
      - TS_ROUTES=192.168.0.0/24
    volumes:
      - /docker/data/tailscale:/var/lib
      - /dev/net/tun:/dev/net/tun
    privileged: true
    restart: unless-stopped
```

If I run
`docker compose up -d`
and then
`docker compose down`
the next 
`docker compose up -d`
will create a new machine in tailscale and assign it a new IP

The volume contains the following files under tailscale folder
```
-rw------- 1 dockeruser dockeruser    0 Nov 16 20:54 tailscaled.log1.txt
-rw------- 1 dockeruser dockeruser    0 Nov 16 20:54 tailscaled.log2.txt
-rw------- 1 dockeruser dockeruser  209 Nov 16 20:33 tailscaled.log.conf
```
The conf file doesn't change between restarts

### OS

Linux

### OS version

Debian 11
