### ISSUE TITLE
Tailscale kubernetes deployment is broken in prod with latest change (k8s)

### ISSUE THREAD

**Issue by opqpop** [tailscale/tailscale#6629]
### What is the issue?

Our Tailscale Kubernetes deployment has been working for the past few days, but has suddenly broken on its own w/o us having done anything. 

Error:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/5566843/205791835-0394874d-b20f-4d66-a152-28e3b0ee8727.png">

"storing device ID in kube secret", "got non-200 status code 403"

There are a couple recent changes that happened ~28d ago from @danderson:
- https://github.com/tailscale/tailscale/blame/4b34c88426de324255f0906db8ae6ecb6da5d107/cmd/containerboot/kube.go#L72
- https://github.com/tailscale/tailscale/commit/bf2d3cd07471cb0501343f694594b3e0b0e3db18

Do you know if these might be related? 

Our k8 container (deployed on Google Kubernetes Engine):

```
        - name: ts-sidecar
          imagePullPolicy: Always
          image: "ghcr.io/tailscale/tailscale:latest"
          env:
            # Store the state in a k8s secret
            - name: TS_KUBE_SECRET
              value: "tailscale-auth-dracula"
            - name: TS_USERSPACE
              value: "false"
            - name: TS_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth-dracula
                  key: TS_AUTH_KEY
                  optional: true
          securityContext:  
            capabilities:
              add:
                - NET_ADMIN
```

What we've tried
- tried using `tailscale/tailscale:stable` docker image but still failed

Any thoughts on how we can further debug this? Ideally we can figure out which of the lines is raising this error, and even better, what `kubectl` commands we can run to repro the actual error to debug.

```

// storeDeviceID writes deviceID into the "device_id" data field of
// the kube secret secretName.
func storeDeviceID(ctx context.Context, secretName, deviceID string) error {
	// First check if the secret exists at all. Even if running on
	// kubernetes, we do not necessarily store state in a k8s secret.
	req, err := http.NewRequest("GET", fmt.Sprintf("/api/v1/namespaces/%s/secrets/%s", kubeNamespace, secretName), nil)
	if err != nil {
		return err
	}
	resp, err := doKubeRequest(ctx, req)
	if err != nil {
		if resp != nil && resp.StatusCode >= 400 && resp.StatusCode <= 499 {
			// Assume the secret doesn't exist, or we don't have
			// permission to access it.
			return nil
		}
		return err
	}

	m := map[string]map[string]string{
		"stringData": map[string]string{
			"device_id": deviceID,
		},
	}
	var b bytes.Buffer
	if err := json.NewEncoder(&b).Encode(m); err != nil {
		return err
	}
	req, err = http.NewRequest("PATCH", fmt.Sprintf("/api/v1/namespaces/%s/secrets/%s?fieldManager=tailscale-container", kubeNamespace, secretName), &b)
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/strategic-merge-patch+json")
	if _, err := doKubeRequest(ctx, req); err != nil {
		return err
	}
	return nil
}
```

Thanks!

### OS

Linux
