### ISSUE TITLE
F-Droid - use golang 1.19 from Debian or rebuild tailscale/go

### ISSUE THREAD

**Issue by licaon-kter** [tailscale/tailscale#6828]
### What is the issue?

Since https://github.com/tailscale/tailscale/issues/2603 the F-Droid build would plainly download unvetted go binaries from Github instead of using the Debian ones or upstreams ones or rebuilding them in the recipe.

I've disabled tainted builds and skipped the go verification from Makefile to force the use of Debian 1.19: https://gitlab.com/fdroid/fdroiddata/-/commit/40a1bd09bfd6fe5aa1d913d812153d6e097ac0c5

Reading the notes in https://github.com/tailscale/go/releases/tag/build-dc0ce6324d19b7539e8efebc64c94631615fd80a 1.19 should be okay already?

If not, a plain rebuild of https://github.com/tailscale/go would be needed in the F-Droid recipe.

@linsui fyi

**Comment by licaon-kter** [comment]
Here's a test apk with debian go 1.19 _(save them all, remove the `.zip` and unpack .001 with 7zip)_
[t19.7z.001.zip](https://github.com/tailscale/tailscale/files/10286016/t19.7z.001.zip)
[t19.7z.002.zip](https://github.com/tailscale/tailscale/files/10286018/t19.7z.002.zip)
[t19.7z.003.zip](https://github.com/tailscale/tailscale/files/10286020/t19.7z.003.zip)

**Comment by licaon-kter** [comment]
Got done the recipe to rebuld tailscale-go before the app:
```
  - versionName: 1.35.80-t237f030cd-gfd874ed58e9
    versionCode: 144
    commit: 6f6d319048bc587a431ad464e7145c2e6fbf0e8f
    subdir: android
    sudo:
      - apt-get update
      - apt-get install -y -t bullseye-backports golang-go
      - apt-get install -y build-essential
    gradle:
      - fdroid
    prebuild:
      - sdkmanager 'platforms;android-31' 'build-tools;31.0.0'
      - sed -i -e '/rm -rf/,+2d' ../Makefile
    srclibs:
      - tailscale-go@e6ce5b50036022c91783161890eabecfddc5ae79
    build:
      - export TOOLCHAINREV=$(go run tailscale.com/cmd/printdep --go)
      - export TOOLCHAINDIR=${HOME}/.cache/tailscale-android-go-$TOOLCHAINREV
      - pushd $$tailscale-go$$
      - git checkout $TOOLCHAINREV
      - pushd src
      - ./make.bash
      - popd
      - popd
      - mkdir -p $TOOLCHAINDIR
      - ln -s $$tailscale-go$$ $TOOLCHAINDIR/go
      - export PATH=$TOOLCHAINDIR/go/bin:$PATH
      - ANDROID_NDK_ROOT=$$NDK$$ make -C .. release_aar
    ndk: r23b
```

APK to test: 
[ttgo.7z.001.zip](https://github.com/tailscale/tailscale/files/10286847/ttgo.7z.001.zip)
[ttgo.7z.003.zip](https://github.com/tailscale/tailscale/files/10286850/ttgo.7z.003.zip)
[ttgo.7z.002.zip](https://github.com/tailscale/tailscale/files/10286848/ttgo.7z.002.zip)
