### ISSUE TITLE
k8s TS_KUBE_SECRET empty string does not work, container always uses "tailscale" k8s secret key

### ISSUE THREAD

**Issue by bmoar** [tailscale/tailscale#7066]
### What is the issue?

I am configuring a simple app in k8s with two worker pods and a redis database pod using sidecars to grant access to tailscale. According to this file: https://github.com/tailscale/tailscale/blob/2adbb4863282d85f07a7d07e462a4ce87c4e4c01/cmd/containerboot/main.go#L40 I should be able to set `TS_KUBE_SECRET=""` and then tailscale will use whatever I have set in `TS_STATE_DIR` as the directory to store the state. This is exactly what I want because I have multiple copies of each worker pod running, so they cannot share a k8s secret. I configured my k8s deployment yaml like so:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: theapp
  labels:
    app: theapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: theapp
  template:
    metadata:
      labels:
        app: theapp
    spec:
      serviceAccountName: tailscale
      containers:
      - name: theapp
        image: ghcr.io/bmoar/theapp:latest
      - name: theapp-vpn-sidecar
        imagePullPolicy: Always
        image: "ghcr.io/tailscale/tailscale:latest"
        env:
        - name: TS_KUBE_SECRET
          value: ""
        - name: TS_STATE_DIR
          value: "/tmp/vpn"
        - name: TS_USERSPACE
          value: "false"
        - name: TS_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth-theapp
              key: TS_AUTH_KEY
              optional: true
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
```

However this does not work and the pod always attempts to use the `tailscale` k8s secret:

```
Program starting: v1.34.1-t331d553a5, Go 1.19.2-ts3fd24dee31: []string{"tailscaled", "--socket=/tmp/tailscaled.sock", "--state=kube:tailscale", "--statedir=/tmp"}
```

This means when there's multiple pods for a deployment, they always attempt to share a single tailscale state, which does not work and results in both pods stuck in crashloopbackoff. I don't see a way to have multiple pods connected to tailscale with this bug in place because multiple replicas will always share the same key.

### Steps to reproduce

I described it above, take the yaml file, swap out ghcr.io/bmoar/theapp with any other image and observe that both pods attempt to use the `tailscale` k8s secret instead of using a state directory on the pod filesystem. Both pods will crash.

### OS

Linux

### OS version

whatever the tailscale docker image uses

### Tailscale version

latest tailscale docker image

### Bug report

BUG-093572801543e1a4bed644ecf80c2543490897313bbcfe1bb6bb017236db3941-20230125183200Z-fc5158237b717978
