### ISSUE TITLE
FR: Fast user switching

### ISSUE THREAD

**Issue by apenwarr** [tailscale/tailscale#713]
(context added on 2022/09/14)

### What are you trying to do?
Log into multiple tailscale accounts at once (eg. example@gmail.com and example@example.com) and easy switch between accounts, i.e. improve the "Log in to a different account..." flow on a device, (possibly) without requiring re-authentication. Access only machines on the network you are currently logged into.

**FR to access all the machines on both networks simultaneously: https://github.com/tailscale/tailscale/issues/183**

### How should we solve this?

The basics of this are not that complicated to do purely client side:
- have ipn.Backend start multiple controlclient instances, one per login
- merge the netmaps from the two instances and feed the merged result to wgengine

Complexity arises from specific details:

1) Should we have multiple local IP addresses, one per account? Is that even possible on all platforms? Or should we get help from the control server to assign the same IP address to all accounts? But if we do that, what about accounts with custom IP subnet designations?

2) If we have multiple local IP addresses, there needs to be a good way to choose which local IP address to use for a given outgoing connection. (Based on routes?)

3) If we use a single local IP address, this could violate users' privacy expectations. Their distinctive identities end up tied together in the control server. It's a lot more elegant if we can support multi-login entirely client side.

4) If two accounts export the same subnet routes (--advertise-subnets), you can get conflicts between them.

5) If two accounts have different DNS overrides, they can conflict. (This isn't so bad if we use the DNS settings only for particular subdomains rather than globally.)

6) Corporate admins may not like the idea of a single machine being on both the corporate and non-corporate networks at once (although it's probably not as bad as being on both the Internet and the corporate network at once.)

**Comment by happyalu** [comment]
Although not _at the same time_, I find it useful to be able to switch accounts to access different groups of machines from my laptop. Prior to 1.0, with the [tailscale-linux-switchuser](https://github.com/happyalu/tailscale-linux-switchuser/) tool I was saving copies of relay.conf for different email addresses and setting `relay.conf` to the required account. It seems that now the information is saved in `tailscaled.state` with a base64 encoded field. 

I tried to save this new file for different email addresses similarly, and copy the right one for the address I want to login to tailscale with, but that didn't seem to work even after restarting tailscaled. Is there an easy way to switch accounts in the current setup? I thought I'll ask before trying to dive down into finding the details of the new file :)

**Comment by apenwarr** [comment]
Note: related issue: https://github.com/tailscale/tailscale/issues/183

**Comment by apenwarr** [comment]
@happyalu, a workaround for user switching is to install the latest *unstable* tailscale stream (at least version 1.1.372) and try the `tailscale up --force-reauth` option. This should let you switch between accounts more easily than by switching config files entirely.

**Comment by DentonGentry** [comment]
Related issue: https://github.com/tailscale/tailscale/issues/662

**Comment by noopsy** [comment]
`tailscale up --force-reauth` will create a new machine and with a new tailscale IP in the tailscale admin panel.  I have found that I need to delete the old machine in the tailscale admin panel before I can get network connectivity to/from this machine.

**Comment by pirate** [comment]
You can already sort of achieve this by running two separate tailscale instances in docker-compose, but YMMV as I haven't thoroughly tested this in production (only the variant described below):

**`docker-compose.yml`:**
```yaml
version: '2.4'
services:
    tailscale1:
        image: tailscale:latest
        build: https://github.com/tailscale/tailscale.git#v1.4.4
        command: tailscaled
        cap_add:
            - NET_ADMIN
            # - SYS_MODULE             # usually not needed, depends on host OS
        network_mode: host
        volumes:
            - /dev/net/tun:/dev/net/tun
            - ./data/tailscale1:/var/lib/tailscale
            
     tailscale2:
        image: tailscale:latest
        command: tailscaled
        cap_add:
            - NET_ADMIN
            # - SYS_MODULE             # usually not needed, depends on host OS
        network_mode: host
        volumes:
            - /dev/net/tun:/dev/net/tun
            - ./data/tailscale2:/var/lib/tailscale
```
```bash
# then start the containers and log into your two separate tailscale accounts
docker-compose up
docker-compose exec tailscale1 tailscale up
docker-compose exec tailscale2 tailscale up
```

Alternatively, you can remove the `network_mode: host` line to keep the containers in a separate network (shared between the containers, but isolated from the host). In that setup each machine will appear to be connected to their respective separate tailscale network but also connected to a shared LAN with the other container.
