### ISSUE TITLE
Kubernetes Deployment doesn't recognize TS_AUTHKEY

### ISSUE THREAD

**Issue by Benbentwo** [tailscale/tailscale#7163]
### What is the issue?

Starting a deployment in kubernetes I find that the pod does not recognize the secret value.

The logs always start with:
```
boot: 2023/02/02 19:10:05 No authkey found in kube secret and TS_AUTHKEY not provided, login will be interactive if needed.
```

Despite trying several ways of setting the value on the container.
Tried
```yaml
      - name: TS_AUTHKEY
        valueFrom:
          secretKeyRef:
            key: TS_AUTHKEY
            name: tailscale-auth
            optional: false
```

with a secret of 
```yaml
apiVersion: v1
  data:
    _machinekey: somethingGenerated-base64-encrypted
    TS_AUTHKEY: foo-base64-encrypted
  kind: Secret
  metadata:
    name: tailscale-auth
    namespace: tailscale
  type: Opaque
```

I'm trying to use an auth key generated by the console, as I will be deploying this to several AWS EKS Clusters, and deploying tailscale then having to tail the logs for the URL isn't as easy as creating a secret to hold the authkey.

as a side note I've also set the env variable directly using:
```yaml
env:
      - name: TS_AUTHKEY
        value: "mykey"
```

and the error still occurred.

How do I get it to recognize the authkey I've generated instead of trying to generate a URL

### Steps to reproduce

`kubectl apply -f secret.yaml`
secret.yaml
```yaml
apiVersion: v1
data:
  TS_AUTHKEY: foobar
kind: Secret
metadata:
  name: tailscale-auth
  namespace: tailscale
type: Opaque
```

`kubectl apply -f deployment.yaml`

deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: tailscale
  name: tailscale
  namespace: tailscale
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tailscale
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      automountServiceAccountToken: true
      containers:
        - env:
            - name: TS_USERSPACE
              value: "true"
            - name: TS_KUBE_SECRET
              value: tailscale-auth
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  key: TS_AUTHKEY
                  name: tailscale-auth
                  optional: false
            - name: TS_ROUTES
              value: 10.00.00.00/22
          image: tailscale/tailscale:v1.36.0
          imagePullPolicy: IfNotPresent
          name: tailscale
          resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 1000
            runAsNonRoot: false
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: tailscale
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30

```

I have also created the service account, role, and role binding following https://github.com/tailscale/tailscale/tree/main/docs/k8s, but that seems to be working fine.

### Are there any recent changes that introduced the issue?

Might be related to https://github.com/tailscale/tailscale/pull/7092

### OS

Linux, Other

### Tailscale version

1.36.0

### Other software

EKS with nodes Bottlerocket OS 1.12.0
