### ISSUE TITLE
iptables issues with the new tailscale kubernetes operator

### ISSUE THREAD

**Issue by marccampbell** [tailscale/tailscale#7278]
### What is the issue?

I installed the new Kubernetes operator, and it adds the service to the tailnet after I annotate the service. This looks promising and good. But I can't route to it. I've tried this on several clusters, with host OSs running Ubuntu 22.04 and with CentOS 8 stream.

The error in the pod that's creating the service is:

```
2023/02/14 06:22:27 health("router"): error: setting up filter/ts-input: running [/sbin/ip6tables -t filter -N ts-input --wait]: exit status 3: modprobe: can't change directory to '/lib/modules': No such file or directory
ip6tables v1.8.8 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
```

### Steps to reproduce

Install tailscale operator, deploy a service, and this error happens. I'm sure there's more missing, but I don't know what it is; unfortunately all of my attempts end with the same result.

### OS

Linux

### OS version

CentOS 8 Stream, or Ubuntu 22.04. Running K8s with Containerd

### Tailscale version

"unstable"

### Other software

Kubernetes 1.26.1

Host OS: 

uname: 
```
Linux controlplane-01 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

/etc/os-release
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by DentonGentry** [comment]
> can't change directory to '/lib/modules': No such file or directory

Is this a cluster you're running yourself, or a hosted service like EKS?

**Comment by marccampbell** [comment]
This is a cluster I'm running myself (from kurl.sh). It's kubeadm, containerd, weave (also tried flannel).
I can make changes on the host, but I'm just not sure where to start.

**Comment by bradfitz** [comment]
Smells like a dup or variant of #5621.

Your host is likely nftables only, and it's trying to use iptables in the container.

**Comment by marccampbell** [comment]
@bradfitz thanks for the pointer. This is correct. Since my current use of the operator is very limited to test cluster with known OS and environment, I was able to verify this by making a custom Dockerfile:

```
FROM --platform=linux/amd64 tailscale/tailscale:unstable

RUN apk update
RUN apk add nftables
RUN rm -f /sbin/iptables
RUN ln -s /sbin/xtables-nft-multi /sbin/iptables
RUN rm -f /sbin/ip6tables
RUN ln -s /sbin/xtables-nft-multi /sbin/ip6tables
```

And then updated the operator.yaml to use my custom image for proxy pods. This obviously isn't the great solution to detect and run legacy or nft versions automatically, but it works for this use case.

**Comment by bradfitz** [comment]
Great. Then this should be fixed by @andrew-d's work on #5621.

**Comment by DentonGentry** [comment]
At this point I don't think we'd do anything differently than fix https://github.com/tailscale/tailscale/issues/5621 and see where we are.

Dup of https://github.com/tailscale/tailscale/issues/5621

**Comment by treethought** [comment]
I'm experiencing this same issue, in an oracle cloud k8s cluster. I think this issue may be due to a recent update to the unstable image instead of the nftables only issue.

I had previously had the operator working correctly in this cluster and was able to route to services. Now the service's machine gets added to tailscale, but the pod created by the operator crashes due to this error.

I'd also note that in this same cluster, I currently also have tailscale v1.36.1 running successfully as a sidecar for multiple deployments. I had also been able to use an older unstable image for these sidecars and as a proxy deployment.

**Comment by DentonGentry** [comment]
For the `nftables` vs `iptables` issue, 1.36.1 and 1.37.x would behave the same. Could you open a new issue, and include a `tailscale bugreport` from the system experiencing a problem?

**Comment by cwiggs** [comment]
> For the `nftables` vs `iptables` issue, 1.36.1 and 1.37.x would behave the same. Could you open a new issue, and include a `tailscale bugreport` from the system experiencing a problem?

I ran into this issue and am running Oracle Kubernetes Engine as well.  I tried to run `tailscale bugreport` on the container that is failing but it reports back:

```
Failed to connect to local Tailscale daemon for /localapi/v0/bugreport; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```

It seems tailscale is failing to start.

The error I'm getting is the same as OP but just to clarify, it's coming from a container that gets created after updating a Service to use tailscale.

If you can guide me on how/where to run `tailscale bugreport` I'd love to get a new issue opened.

Thanks.

**Comment by cwiggs** [comment]
> @bradfitz thanks for the pointer. This is correct. Since my current use of the operator is very limited to test cluster with known OS and environment, I was able to verify this by making a custom Dockerfile:
> 
> ```
> FROM --platform=linux/amd64 tailscale/tailscale:unstable
> 
> RUN apk update
> RUN apk add nftables
> RUN rm -f /sbin/iptables
> RUN ln -s /sbin/xtables-nft-multi /sbin/iptables
> RUN rm -f /sbin/ip6tables
> RUN ln -s /sbin/xtables-nft-multi /sbin/ip6tables
> ```
> 
> And then updated the operator.yaml to use my custom image for proxy pods. This obviously isn't the great solution to detect and run legacy or nft versions automatically, but it works for this use case.

I followed the advice here and used my own image with nft over iptables and can confirm that the tailscale operator is working on OKE for me now.  I had to do a few things in addition to using a custom image:

1.  Used kustomize to patch the `operator` Deployment.  Had to use [merge strategy](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md) over [Json6902](https://www.rfc-editor.org/rfc/rfc6902) since json6902 doesn't allow you to select a key name in a list.
2. Since the custom image I used was private I had to create the container registry secret using this [guide](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
3. Patch the `proxies` ServiceAccount so that the "proxy" container that gets created can use the new image credentials.

Here are the bits for kustomize:

operator-deployment-patch.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: tailscale
spec:
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
        - name: operator
          env:
            - name: PROXY_IMAGE
              value: ghcr.io/namespace_example/image_name_example:tag
```

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale
resources:
  - https://raw.githubusercontent.com/tailscale/tailscale/main/cmd/k8s-operator/manifests/operator.yaml

patches:
  - target:
      kind: Deployment
      name: operator
    path: operator-deployment-patch.yaml
  - target:
      kind: ServiceAccount
      name: proxies
    patch: |-
      - op: add
        path: /imagePullSecrets
        value:
          - name: ghcr-auth
 ```
 
 Hope that helps someone or tailscale can get #5621 fixed soon.
