### ISSUE TITLE
Running Tailscale as a Sidecar Container + Tailscale on the Host system causes network issues if Tailscale takes too long to connect

### ISSUE THREAD

**Issue by MrPowerGamerBR** [tailscale/tailscale#7540]
### What is the issue?

This is a mix of a bug report and "omg I have no idea how to fix this pls help" issue.

If you are running Tailscale as a Sidecar Container + Tailscale on the Host system causes network issues if Tailscale takes too long to connect, causing active network connections to hang forever.

### Steps to reproduce

First, your host system needs to have Tailscale running.

```yml
version: "3.8"
services:
  yourservicehere:
    ... your service here, to reproduce the service needs to connect to something (database, etc) ...
    network_mode: service:tailscale
  tailscale:
    hostname: yourservicehere
    image: tailscale/tailscale:latest
    volumes:
      - "./tailscale_var_lib:/var/lib"
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
      - net_raw
    command: tailscaled
```

When I start the service with `docker compose up`, 90% of the time the application gets stuck trying to connect to the database, and, 10% of the time, the application throws a `Failed to initialize pool: This connection has been closed.` error.

I think this happens because, when starting up the `yourservicehere`, the container is using the host's Tailscale connection, then, when sidecar Tailscale container finishes initializing, the container switches to using the sidecar's Tailscale network, which causes the database connection packets to be lost, which breaks the connection.

If I'm not using `network_mode: service:tailscale` then it works, but then I'm using the host's tailscale network, which I don't want to.

If I remove the `/dev/net/tun:/dev/net/tun` bind, then the container fails because it can't initialize Tailscale AND it can't use the host Tailscale connection.

If I manually use `docker compose up -d tailscale` and, after a few seconds, I use `docker compose up -d yourservicehere`, then it works fine because the sidecar Tailscale container is already initialized.

I could manually add a startup delay to my service, but that feels hacky.

Is there's any way to NOT use the host's Tailscale network when using a Tailscale sidecar container? I don't care if that would mean that the database connection would fail when starting up because Tailscale isn't ready yet, because at least in that case I can retry the connection, whereas currently I can't do that because the connection attempt hangs for a looong time.

### OS

Linux

### OS version

Ubuntu Server 22.04

### Tailscale version

1.34.2

**Comment by MrPowerGamerBR** [comment]
Here's a workaround, [thanks to /u/jcheroske](https://www.reddit.com/r/Tailscale/comments/11p705x/weird_tailscale_issue_when_using_tailscale_within/jby6iyc/)

```yml
    depends_on:
      tailscale:
        condition: service_healthy
  tailscale:
    hostname: pantufa
    image: tailscale/tailscale:latest
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 1s
      timeout: 5s
      retries: 60
```

Now the container only starts if `tailscale status` has an 0 exit code.

It may still have race conditions, but I couldn't reproduce it after doing this change.
