### ISSUE TITLE
Tailscale 1.38.1 not caching certificate in Kubernetes state secret

### ISSUE THREAD

**Issue by dcarrion87** [tailscale/tailscale#7588]
### What is the issue?

Tailscale isn't storing certificate in Kubernetes state following upgrade to 1.38.1. I understand this feature is now in there. Original issue: https://github.com/tailscale/tailscale/issues/5676

I removed my homebrew caching mechanism and triggered a cert request via the Caddy sidecar and went to check the state and I can't see anything that looks like a certificate. I can see a new cert in /tmp/ though. Maybe I've missed a parameter?

Secret:

```
 kubectl describe -n mynamespace secret tailscale-state
Name:         tailscale-state
Namespace:    mynamespace
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
_current-profile:  12 bytes
_daemon:           817 bytes
_machinekey:       72 bytes
_nl-node-key:      135 bytes
_profiles:         331 bytes
device_fqdn:       35 bytes
device_id:         12 bytes
profile-577c:      1176 bytes
```

Sidecar params: 

```
  ts-sidecar:
    Container ID:   containerd://e9f802263677a529d918073f900d3d53a3c7551eeb6ce293086ebe7a1e848502
    Image:          ghcr.io/tailscale/tailscale:v1.38.1
    Image ID:       ghcr.io/tailscale/tailscale@sha256:f2be570c3a890c4f70bcf4dcbba2c92e1b9ea38bbfb453f0b0113f9f102b1b78
 ...
    Environment:
      TS_KUBE_SECRET:  tailscale-state
      TS_USERSPACE:    true
      TS_EXTRA_ARGS:   --hostname myhostname
      TS_AUTH_KEY:     <set to the key 'TS_AUTH_KEY' in secret 'tailscale-auth'>  Optional: false
```

### Steps to reproduce

Install Tailscale into Kubernetes and trigger a certificate request.

### Are there any recent changes that introduced the issue?

Updating to version 1.38.1

### OS

Linux

### OS version

-

### Tailscale version

1.38.1

### Other software

Kubernetes

**Comment by maisem** [comment]
Can you share your pod yaml? Specifically what env vars are you setting?

**Comment by dcarrion87** [comment]
As requested:

```
  ts-sidecar:
    Container ID:   containerd://e9f802263677a529d918073f900d3d53a3c7551eeb6ce293086ebe7a1e848502
    Image:          ghcr.io/tailscale/tailscale:v1.38.1
    Image ID:       ghcr.io/tailscale/tailscale@sha256:f2be570c3a890c4f70bcf4dcbba2c92e1b9ea38bbfb453f0b0113f9f102b1b78
 ...
    Environment:
      TS_KUBE_SECRET:  tailscale-state
      TS_USERSPACE:    true
      TS_EXTRA_ARGS:   --hostname myhostname
      TS_AUTH_KEY:     <set to the key 'TS_AUTH_KEY' in secret 'tailscale-auth'>  Optional: false
```

**Comment by dcarrion87** [comment]
One extra note is there is a caddy sidecar that requests the cert via the `/tmp/tailscaled.sock`.

My homewbrew solution was looping and pulling the cert out of `/tmp/` into a secret. I'd like to remove that and just rely on inbuilt tailscale mechanism (if it works).

**Comment by dcarrion87** [comment]
I've reverted the implementation to our custom caching mechanism until it's clearer how the feature was intended to work.

**Comment by maisem** [comment]
Yeah this is definitely broken, working on a fix.

**Comment by hypetrain-ai** [comment]
Hi @dcarrion87 could you share how to set up the caddy sidecar to request the cert?

I'm trying to set up a pod with a tailscale sidecar to have a valid cert but I'm not sure how to set it up. Ideally the tailscale sidecar would have an option TS_EXTRA_ARGS="--generate_cert" but that doesn't seem to exist. Seeing an example of how you accomplish this would be very helpful. Thanks!

**Comment by jonathanasdf** [comment]
Hi @dcarrion87 could you share how to set up the caddy sidecar to request the cert?

I'm trying to set up a pod with a tailscale sidecar to have a valid cert but I'm not sure how to set it up. Ideally the tailscale sidecar would have an option TS_EXTRA_ARGS="--generate_cert" but that doesn't seem to exist. Seeing an example of how you accomplish this would be very helpful. Thanks!

**Comment by dcarrion87** [comment]
Hi @jonathanasdf 

I'm relying on Caddy's inbuilt tailscale magic and sharing the socket to make it so. Below some cut down YAML. Hope it helps!

Caddyfile in configmap:

```
apiVersion: v1
data:
  Caddyfile: |
    myapp.mytailnet.ts.net
    reverse_proxy :3000
kind: ConfigMap
metadata:
  name: caddy-config
```

Snippet from deployment. The important part here is mounting the Caddy config file, sharing the tailscale socket via the shared /tmp path, and adding the symbolic link to where Caddy looks by default for the socket.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  template:
    spec:
      containers:
      - env:
        - name: TS_KUBE_SECRET
          value: tailscale-state
        - name: TS_USERSPACE
          value: "true"
        - name: TS_EXTRA_ARGS
          value: --hostname myapp
        - name: TS_AUTH_KEY
          valueFrom:
            secretKeyRef:
              key: TS_AUTH_KEY
              name: tailscale-auth
              optional: false
        image: ghcr.io/tailscale/tailscale:v1.38.3
        name: ts-sidecar
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      - image: caddy:2.5.2
        name: caddy
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - mkdir -p /var/run/tailscale/ && ln -s /tmp/tailscaled.sock /var/run/tailscale/tailscaled.sock
        volumeMounts:
        - mountPath: /etc/caddy/Caddyfile
          name: caddy-config
          subPath: Caddyfile
        - mountPath: /tmp
          name: tmp
      volumes:
      - configMap:
          name: caddy-config
        name: caddy-config
      - emptyDir: {}
        name: tmp
```
