### ISSUE TITLE
FR: Support CNAME responses from global nameservers that refer to magic-DNS names

### ISSUE THREAD

**Issue by kristjanvalur** [tailscale/tailscale#7650]
### What are you trying to do?

We want to create cname records in our public dns, like so:

`servitor.mycompany.com. CNAME servitor.foo-bar.ts.net.`

This allows a simpler management of DNS than having to duplicate IP values into the global DNS.

On linux and windows, this does not work.  The reason, as far as I can determine is this (from using `nslookup` in debug mode)

1. magic dns recieves the `.mycompany.com.` request.  It isn't a `foo-bar.ts.net.` request, so it forwards it to the global name server
2. global nameserver finds the cname records, but nothing else and returns it to the magic dns server
3. magic dns considers the request fully tried and returns the cname response from global server to the client, but no A record.
4. the client gives up, because it expects the name servers to resolve the CNAME records for it.

### How should we solve this?

My suggestion is a slight change in algorithm for magic dns, something like this.

1. If the domain isn't recognised as a magic domain, forward it on to other nameservers.
2. If the response is fully resolved, (i.e. a A request returns an address, return it.
3. Otherwise, consider if the "canonical name" response mathches the magic dns domain, i.e. "foo-bar.ts.net".
4. If so, perform a a magic dns lookup and return it to the client.

### What is the impact of not solving this?

The workaround is to to place tailnet IP numbers directly into the global DNS, but this is error prone.

### Anything else?

On MacOS, apparently the dnslookup library routines will _retry_ if they get a "CNAME" response and no "A" response.  The retry from the client side _will_ make this work.  In other words, it works on MacOS, but not on implementations which expect the name server to do the CNAME resolution.

**Comment by DentonGentry** [comment]
This is somewhat more invasive that it might appear: the operating systems we support differ in how they handle a CNAME from a public DNS server which refers to a name that the public DNS server cannot resolve and returns NXDOMAIN:
- macOS, iOS and Linux receive the NXDOMAIN from the public server and re-initiate a DNS lookup for the FQDN, which might get a response from a different DNS server. They effectively ignore the first NXDOMAIN and try again.
- Android and Windows treat the NXDOMAIN as definitive, and fail the response.

To make the behavior consistent across operating systems we'd need to make `100.100.100.100` into a fully recursive resolver.

THAT, in turn, brings a big downside: any DNS client settings or software nenhancements which Tailscale currently can be used with will stop working. Windows in particular has a very featureful DNS client with NRPT rules and GPO settings which currently work with Tailscale, and would stop working if `100.100.100.100` is configured to take over DNS handling and recursively resolve names.

**Comment by kristjanvalur** [comment]
I see.  Thank you for your explanation.
I guess a separate different approach could be used instead:  The ability to inject a list of custom (both FDQN and relative) aliases into the magic DNS resolver bound to the local tailnet.
magic dns will always be tried first, and if one could, in this instance, put in a "magic" CNAME record into the index, pointing `servitor.mycompany.com.` at `servitor01.foo-bar.ts.net.`  that would also be super.  That way we don't even have to have anything public.

The goal is to be able to provide familiar DNS-like host-names to the users.

I'm guessing you already have similar requests, to provide named aliases etc in the MagicDNS.

**Comment by bcat** [comment]
I think this may be somewhat more important now that shared Tailscale nodes will have [different IPv4 addresses in different tailnets](https://tailscale.com/blog/choose-your-ip/#natural-solutions). Previously, one could just point an A record in public DNS (e.g., `foo.example.net`) to the unique IPv4 address of the backing Tailscale node. Now that the node no longer has a unique IPv4 address, I hoped to have use a CNAME record instead (e.g., pointing `foo.example.net` to `machine.tail12345.ts.net`), but [that doesn't work in practice](https://www.reddit.com/r/Tailscale/comments/18dv4zl/choose_your_own_ip/kck7sq9/), as it appears I've run into this bug.

**Comment by SnoFox** [comment]
It appears I've also discovered this bug. I'm in the process from migrating a Kubernetes cluster to be accessible via Tailscale + the Kubernetes Operator from an old hacky Wireguard setup as a proof of concept.

The hypothesis I had been testing: If I create an ingress tagged for both Tailscale and my old setup, will they co-exist and function?
The answer: I'm not sure. I was surprised to find that our version of `kubernetes-sigs/external-dns` creates a CNAME for `internal-service.example.com` pointing at `example-internal-service.tailnet-NNNN.ts.net`. I've been unable to find an option in `external-dns` to set a matching A record, nor have I been able to resolve the public DNS due to the above comments about being a non-recursive resolver.

If recursion isn't an option (even for a small list of our own domains), could we perhaps delegate a (sub)domain to Tailscale for TLS certs and MagicDNS uses?

```yaml
# Example ingress tagged with both old and Tailscale setup
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: example
  name: example-internal-service
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: tailscale
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: example-internal-service
            port:
              number: 80
  tls:
  - hosts:
    - example-internal-service
  - hosts:
    - internal-service.example.com
    secretName: example-internal-service-tls
```
