### ISSUE TITLE
tailscale exit nodes do not work in Kubernetes

### ISSUE THREAD

**Issue by uhthomas** [tailscale/tailscale#7695]
### What is the issue?

It looks like Tailscale forgets that it needs to use the local cluster DNS resolver to communicate with the Kubernetes API and then times out and crashes.

```
2023/03/26 16:12:38 [RATELIMIT] format("open-conn-track: timeout opening %v to node %v; online=%v, lastRecv=%v")
2023/03/26 16:12:39 open-conn-track: flow TCP (TCP 100.97.169.251:52157 => 149.57.16.58:4934) got RST by peer
53579 => 95.102.251.18:41837) to node [iabZZ]; online=yes, lastRecv=0s
2023/03/26 16:12:48 open-conn-track: timeout opening (TCP 100.97.169.251:51851 => 82.155.153.203:48400) to node [iabZZ]; online=yes, lastRecv=0s
2023/03/26 16:12:48 [RATELIMIT] format("open-conn-track: timeout opening %v to node %v; online=%v, lastRecv=%v")
2023/03/26 16:12:49 [RATELIMIT] format("open-conn-track: flow TCP %v got RST by peer") (47 dropped)
2023/03/26 16:12:49 open-conn-track: flow TCP (TCP 100.97.169.251:36395 => 5.225.83.238:1900) got RST by peer
2023/03/26 16:12:49 open-conn-track: flow TCP (TCP 100.97.169.251:47147 => 156.146.49.174:40608) got RST by peer
2023/03/26 16:12:49 [RATELIMIT] format("open-conn-track: flow TCP %v got RST by peer")
2023/03/26 16:12:58 [RATELIMIT] format("open-conn-track: timeout opening %v to node %v; online=%v, lastRecv=%v") (206 dropped)
2023/03/26 16:12:58 open-conn-track: timeout opening (TCP 100.97.169.251:59757 => 185.229.59.115:12658) to node [iabZZ]; online=yes, lastRecv=0s
2023/03/26 16:12:58 open-conn-track: timeout opening (TCP 100.97.169.251:35647 => 41.216.203.148:47278) to node [iabZZ]; online=yes, lastRecv=0s
2023/03/26 16:12:58 [RATELIMIT] format("open-conn-track: timeout opening %v to node %v; online=%v, lastRecv=%v")
2023/03/26 16:12:59 [RATELIMIT] format("open-conn-track: flow TCP %v got RST by peer") (21 dropped)
2023/03/26 16:12:59 open-conn-track: flow TCP (TCP 100.97.169.251:35721 => 143.244.41.212:14436) got RST by peer
2023/03/26 16:12:59 open-conn-track: flow TCP (TCP 100.97.169.251:37689 => 102.33.11.42:37837) got RST by peer
2023/03/26 16:12:59 [RATELIMIT] format("open-conn-track: flow TCP %v got RST by peer")
boot: 2023/03/26 16:13:02 storing device ID in kube secret: Get "https://kubernetes.default.svc/api/v1/namespaces/media/secrets/transmission-tailscale": context deadline exceeded
```

### Steps to reproduce

Given a sidecar container like:

```cue
containers: [{
	name:  "tailscale"
	image: "tailscale/tailscale:latest"
	env: [{
		name:  "TS_KUBE_SECRET"
		value: "\(#Name)-tailscale"
	}, {
		name:  "TS_USERSPACE"
		value: "false"
	}, {
		name:  "TS_AUTHKEY"
		value: ""
	}, {
		name:  "TS_EXTRA_ARGS"
		value: "--exit-node=100.87.32.47"
	}]
	imagePullPolicy: v1.#PullIfNotPresent
	securityContext: capabilities: add: ["NET_ADMIN"]
}]
serviceAccountName: #Name
```

It's unclear at how effective it actually is as an exit node for the other containers. More importantly, it will crash every 30 seconds or so as it cannot create the `TS_KUBE_SECRET` secret. Neither of these flags help:

- `--exit-node-allow-lan-access`
- `--accept-dns=false`

### OS

Linux, Other

### OS version

Kubernetes 1.26.2 (5.15.102-talos, containerd://1.6.18)

### Tailscale version

latest (3db61d07ca81aea7b86591d1874e48db01b6abcf-dirty)

### Bug report

Failed to connect to local Tailscale daemon for /localapi/v0/bugreport; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory

**Comment by uhthomas** [comment]
There is some merit to this comment: https://github.com/tailscale/tailscale/issues/7388#issuecomment-1448349207. The older version doesn't crash, though I still don't believe it's working as intended.

**Comment by maisem** [comment]
Can you provide more details on what the goal with the exit node is?

The state management issue does look like a bug, I can investigate that.

**Comment by maisem** [comment]
Another way to make this work would be to run the sidecar in userspace mode and have it expose a SOCKS5 proxy that you can have the application the use

**Comment by uhthomas** [comment]
I have been thinking about that, though I'm not sure the application I'm sure natively supports it. Is it possible to force all traffic in a pod through a SOCKS5 proxy?

**Comment by uhthomas** [comment]
>Can you provide more details on what the goal with the exit node is?

Essentially I just want the application to be able to use an exit node so it can bypass random restrictions some UK ISPs have.

**Comment by DentonGentry** [comment]
> It looks like Tailscale forgets that it needs to use the local cluster DNS resolver to communicate with the Kubernetes API

I'm unfamiliar with the domains which Kubernetes uses. We might be able to add similar handling as is done for the various cloud provider's *.internal domain in https://github.com/tailscale/tailscale/blob/main/net/dns/resolver/forwarder.go

**Comment by maisem** [comment]
The problem is likely that we need to use `(*tsdial.Dialer).SystemDial` when contacting the k8s API. Without that, we end up routing traffic via the exit node.

**Comment by netthier** [comment]
Are there any workarounds available for this?

**Comment by karbowiak** [comment]
I just tried getting this working using a sidecar, and lo and behold - it works.
However no matter what, it ends up blocking the local kube network, and i can't find a way around it.

I'll share the YAML in it's entirety (Sans auth key)
The cluster setup is:

- k0s
- tailscale-operator setup and working with ingress (when tailscale sidecar isn't running)

What happens:
Tailscale sidecar comes up and routes traffic via mullvad just fine, but upon doing that - blocks all local network traffic inside the cluster, so the operators ingress stops working - and other containers stops being able to talk with the webapi

Whats expected::
Tailscale sidecar comes up and routes traffic via mullvad, and internal networking still works so the tailscale ingress can show the webui, and other containers in the cluster can talk to the webapi as well.

YAML:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: sabnzbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
        app.kubernetes.io/name: sabnzbd
        app.kubernetes.io/component: sabnzbd
    spec:
      restartPolicy: Always
      containers:
        - name: tailscale
          image: tailscale/tailscale:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: "TS_KUBE_SECRET"
              value: "sabnzbd-exit-tailscale"
            - name: TS_USERSPACE
              value: "false"
            - name: TS_AUTH_KEY
              value: "tskey-auth"
            - name: TS_EXTRA_ARGS
              value: "--exit-node=100.73.22.4 --exit-node-allow-lan-access --accept-dns=false --snat-subnet-routes=false --hostname=sabnzbd-tailscale --reset"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          volumeMounts:
            - name: tailscale-state
              mountPath: /var/lib/tailscale
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          command: ["/bin/sh", "-c"]
          args: ["sleep 10 && exec /init"]
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: sabnzbd-extended-config
              mountPath: /config/extended.conf
              subPath: extended.conf
            - name: config
              mountPath: /custom-cont-init.d
              subPath: custom-cont-init.d
            - name: config
              mountPath: /custom-services.d
              subPath: custom-services.d
            - name: media
              mountPath: /storage
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: sabnzbd-extended-config
          configMap:
            name: sabnzbd-extended-config
        - name: media
          hostPath:
            path: /storage
            type: Directory
        - name: tailscale-state
          emptyDir: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - sabnzbd
    secretName: sabnzbd-tls
  defaultBackend:
    service:
      name: sabnzbd
      port:
        number: 8080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sabnzbd-tailscale
  namespace: sabnzbd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["sabnzbd-exit-tailscale"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sabnzbd-tailscale-binding
  namespace: sabnzbd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sabnzbd-tailscale
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sabnzbd
---
apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-exit-tailscale
  namespace: sabnzbd
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  selector:
    app: sabnzbd
  ports:
    - name: sabnzbd
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: sabnzbd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nvme
  resources:
    requests:
      storage: 50Gi
```
