### ISSUE TITLE
FR: support funnel with k8s operator

### ISSUE THREAD

**Issue by asg0451** [tailscale/tailscale#7895]
### What is the issue?

i started a funnel on a tailscale kubernetes sidecar, but nothing will connect to it. looking at the logs:

```

ts-sidecar boot: 2023/04/17 03:13:07 Startup complete, waiting for shutdown signal
ts-sidecar 2023/04/17 03:13:07 magicsock: derp-1 connected; connGen=1
ts-sidecar 2023/04/17 03:13:07 health("overall"): ok
ts-sidecar 2023/04/17 03:13:12 wgengine: idle peer [Zhyr6] now active, reconfiguring WireGuard
ts-sidecar 2023/04/17 03:13:12 wgengine: Reconfig: configuring userspace WireGuard config (with 1/16 peers)
ts-sidecar 2023/04/17 03:13:12 Accept: TCP{100.113.125.113:35272 > 100.117.132.167:443} 52 tcp non-syn
ts-sidecar 2023/04/17 03:14:31 cert("sproter-wtf.beagle-chickadee.ts.net"): already had ACME account.
ts-sidecar 2023/04/17 03:14:31 cert("sproter-wtf.beagle-chickadee.ts.net"): starting SetDNS call...
ts-sidecar 2023/04/17 03:14:42 cert("sproter-wtf.beagle-chickadee.ts.net"): did SetDNS
ts-sidecar 2023/04/17 03:15:01 cert("sproter-wtf.beagle-chickadee.ts.net"): getCertPEM: context canceled
```

i tried with different host names and nothing works. maybe something is messed up with my account..

### OS

Linux

### OS version

Kubernetes/Ubuntu

### Tailscale version

1.38.4   tailscale commit: 043a34500dd2bb07c34e3b28a56cdbc8b5434454-dirty   go version: go1.20.3-tsddff070

### Bug report

BUG-18ca3f34a86d4f9a0fbda73c544c06739a75d4bed51de23dac4f2dff27e796c3-20230417031900Z-c851ed6f55a07ae5

**Comment by DentonGentry** [comment]
I don't think Funnel works with the k8s operator yet. https://github.com/tailscale/tailscale/issues/502#issuecomment-1414522795

**Comment by maisem** [comment]
Closed accidentally

**Comment by rodrigc** [comment]
@maisem in addition to mentioning latest `unstable`, can you also refer to an actual SHA or 
a label for the operator image with this new funnel feature?
In my Kubernetes setup, I prefer to track tailscale stuff at a finer granularity with explicit tags or SHA, rather than a moving tag like `unstable`

**Comment by maisem** [comment]
That would be `unstable-v1.49.121`

**Comment by rodrigc** [comment]
Thanks, maisem!

**Comment by dvcrn** [comment]
Awesome work, thanks maisem!

FIY, if you self-manage the manifests like with kustomize, the change you need is https://github.com/tailscale/tailscale/commit/d1b2543477777f1ea02a86cc747cea01beb4810c#diff-622a76c103f2385b84fc671bbbd1d8355baa94c1e1ec4c2b4a5a738e6bde1cf8, so that the service account is able to access ingress resources 

Tried setting it up. Funnel works now, but it was a bit wonky in the beginning with errors popping up like:
```
{"level":"info","ts":"2023-08-29T01:03:41Z","logger":"ingress-reconciler","msg":"exposing ingress over tailscale","ingress-ns":"default","ingress-name":"webdav"}
{"level":"error","ts":"2023-08-29T01:03:48Z","msg":"Reconciler error","controller":"ingress","controllerGroup":"networking.k8s.io","controllerKind":"Ingress","Ingress":{"name":"webdav","namespace":"default"},"namespace":"default","name":"webdav","reconcileID":"96f5cfed-7782-4834-9b75-b0950fd563ed","error":"failed to provision: failed to create or get API key secret: Operation cannot be fulfilled on secrets \"ts-webdav-kfrzv-0\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"}
```

Tailscale pod spawned by controller:
```
boot: 2023/08/29 01:03:53 Startup complete, waiting for shutdown signal
boot: 2023/08/29 01:03:53 failed to set serve config: sending serve config: updating config: writing ServeConfig to StateStore: Operation cannot be fulfilled on secrets "ts-webdav-kfrzv-0": the object has been modified; please apply your changes to the latest version and try again
```

At some point it just worked, but I had to re-create the ingress resources. The first run crashed, then the pod got recreated and then it worked. Now funnel is operational.

**Comment by maisem** [comment]
@dvcrn thats good feedback, I've changed how we update the secret so this error should either disappear or happen less frequently.

**Comment by rodrigc** [comment]
@maisem I did a quick test in my environment (Oracle Kubernetes) with this:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
      - env:
        - name: PROXY_IMAGE
          value: docker.io/tailscale/tailscale:unstable-v1.49.197
        - name: TS_DEBUG_FIREWALL_MODE
          value: nftables
        - name: AUTH_PROXY
          value: "true"
        - name: OPERATOR_LOGGING
          value: info
        - name: OPERATOR_HOSTNAME
          value: tailscale-operator
        - name: OPERATOR_SECRET
          value: operator
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLIENT_ID_FILE
          value: /oauth/client_id
        - name: CLIENT_SECRET_FILE
          value: /oauth/client_secret
        - name: PROXY_TAGS
          value: tag:k8s
        image: docker.io/tailscale/k8s-operator:unstable-v1.49.197
        name: operator
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
        volumeMounts:
        - mountPath: /oauth
          name: oauth
          readOnly: true
      serviceAccountName: operator
      volumes:
      - name: oauth
        secret:
          secretName: operator-oauth
```

I also tested an Ingress with the funnel annotation and it worked:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: funnel
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - funnel
  defaultBackend:
    service:
      name: nginx
      port:
        number: 80
```

I'm having some other problems though with respect to iptables (i.e. pods started by operator does not honor
`TS_DEBUG_FIREWALL_MODE` and defaults to "old" iptables) which does not work in my Oracle environment.

I'll file a separate ticket for that.

But this work is progressing well!
