### ISSUE TITLE
FR: kubernetes operator: support auth proxy

### ISSUE THREAD

**Issue by uhthomas** [tailscale/tailscale#7913]
### What are you trying to do?

It would be really nice if functionality similar to https://tailscale.com/blog/tailscale-auth-nginx/ or https://tailscale.com/blog/grafana-auth/ could be implemented natively in the Kubernetes operator.

### How should we solve this?

It might need a custom resource definition to define the appropriate configuration? Maybe service annotations? Not sure. There are probably lot's of ways to approach this.

### What is the impact of not solving this?

Either not using tailscale for auth or manually running either a dedicated deployment or sidecar to handle auth for a particular service.

### Anything else?

https://tailscale.com/blog/tailscale-auth-nginx/

https://tailscale.com/blog/grafana-auth/

https://github.com/tailscale/tailscale/blob/main/cmd/proxy-to-grafana/proxy-to-grafana.go

**Comment by DentonGentry** [comment]
I don't understand how this is different from https://tailscale.com/kb/1236/kubernetes-operator/#enabling-an-auth-proxy

**Comment by uhthomas** [comment]
@DentonGentry I believe the one you linked is an auth proxy for the kube api server. My suggestion is an auth proxy for applications like Grafana.

**Comment by maisem** [comment]
@uhthomas the latest unstable k8s operator supports k8s ingress resources. In Ingress mode, the proxy passes through [headers](https://tailscale.com/kb/1247/funnel-serve-use-cases/#use-serve-as-an-identity-proxy) which can used to identify the caller. 

You can configure ingress like 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: nginx
      port:
        number: 80
```
