### ISSUE TITLE
FR: google cloud builder image 

### ISSUE THREAD

**Issue by rojomisin** [tailscale/tailscale#8189]
### What are you trying to do?

To allow flexible networking from google cloud build worker pools to other endpoints, including GKE

### How should we solve this?

https://tailscale.com/blog/2021-05-github-actions-and-tailscale/ describes how to do this in GH actions, the proposed cloud builder would do the same things in a cloud builder pattern

### What is the impact of not solving this?

expensive cloud networking using vpns across service producer networks over non-transitive vpcs will be normalized in society

**Comment by DentonGentry** [comment]
This means posting the container image to Google'c container registry?
It looks like mirror.gcr.io already caches images accessed from DockerHub.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/8259, also filed by rojomisin, says:

package up the tailscale container like it's done for GH actions
https://github.com/tailscale/github-action/blob/main/action.yml
using the cloud builder community pattern
https://github.com/GoogleCloudPlatform/cloud-builders-community

**Comment by DentonGentry** [comment]
@rojomisin Have you been trying to use Tailscale within Google Cloud Build, and running into issues or things that you would need?

For https://github.com/tailscale/github-action it was clear what to build: GitHub Actions defines a YAML format for a workflow.

For Google Cloud Builder we don't see what we could provide which https://hub.docker.com/r/tailscale/tailscale doesn't already provide.

**Comment by rojomisin** [comment]
thanks @DentonGentry yeah I dropped this all together, there is a certain dind way to do this in google cloud build which I couldn't figure out so had to move on.

What we were trying to do is use dind to background the tailscaled process and then use it as a proxy for kubectl

```yaml
  - name: tailscale/tailscale
    id: testing to see if tailscale dameon can work in gcb
    secretEnv:
      - TSAUTHKEY
    args: [ "docker", "run", "-d", "--name=tailscaled", "-v", "/var/lib:/var/lib", "-v", "/dev/net/tun:/dev/net/tun", "--network=host", "--cap-add=NET_ADMIN", "--cap-add=NET_RAW", "--env", "TS_AUTHKEY=$$TSAUTHKEYTEST", "tailscale/tailscale" ]

```

I also tried the SOCKS5 proxy to no avail

If I figure it out will post, thanks for following up

**Comment by DentonGentry** [comment]
> use it as a proxy for kubectl

That a kubectl for your own Kubernetes cluster, or GKE, or something?

**Comment by rojomisin** [comment]
Yes, it's a pretty cool pattern if everything is in the same region, very terse yaml blocks like:

```yaml
  - id: kubectl using tailscale
    name: gcr.io/cloud-builders/kubectl
    env:
      - 'HTTP_PROXY=socks5://tailscale-container:1055'
      - 'CLOUDSDK_COMPUTE_REGION=${LOCATION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
      - 'CLOUDSDK_GET_CREDENTIALS_OPTS=--internal-ip'
    args: ['get', 'pods', '-A', '--v=8', '--request-timeout=10s']
    waitFor: ["-"]
```

But once you try to do x-region kubectl connectivity to private gke clusters, it uses private google networks, and one is [forced to provision multiple VPNs](https://cloud.google.com/build/docs/private-pools/use-in-private-network#deploying-to-clusters) to avoid unsupported transient vpc crossings... kind of nasty caveat.
