### ISSUE TITLE
FR: update docs for docker install option

### ISSUE THREAD

**Issue by ksurl** [tailscale/tailscale#8202]
### What are you trying to do?

document an official way to run tailscale via docker

### How should we solve this?

include a section for docker install including docker run and compose example in the docs

https://tailscale.com/kb/installation/

### What is the impact of not solving this?

users won't have to piece together from fragments of info in docs and issues how to run tailscale from docker.

### Anything else?

example compose:

```
services:
  tailscale:
    image: tailscale/tailscale
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TS_AUTHKEY=<KEY>
      - TS_ROUTES=<SUBNET>
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

```

from the docker hub page, supported environment variables:

```
    TS_AUTHKEY: a [Tailscale auth key](https://tailscale.com/kb/1085/auth-keys/), i.e. what you'd pass to tailscale --authkey=
    TS_KUBE_SECRET: if running in Kubernetes, secret name where to store Tailscale state
    TS_DEST_IP: destination IP, if deploying Tailscale as a proxy
    TS_ROUTES: tailscale --advertise-routes=
    TS_ACCEPT_DNS: tailscale --accept-dns=
    TS_SOCKET: tailscale --socket=
    TS_EXTRA_ARGS: any other CLI flags for tailscale
    TS_USERSPACE: tailscaled --tun=userspace-networking
    TS_STATE_DIR: tailscaled --statedir=
    TS_SOCKS5_SERVER: set to an addr+port for the SOCKS5 proxy like :1055, which will be passed to tailscaled --socks5-server=:1055
    TS_OUTBOUND_HTTP_PROXY_LISTEN: set to an addr+port for the HTTP proxy like :1055, which will be passed to tailscaled --outbound-http-proxy-listen=:1055
    TS_TAILSCALED_EXTRA_ARGS: any other flags for tailscaled
```
