### ISSUE TITLE
Tailscale's containerboot with stateDir doesn't pick up new routes

### ISSUE THREAD

**Issue by ventsislav-georgiev** [tailscale/tailscale#8381]
### What is the issue?

Using tailscale client in Kubernetes with the following configuration:
```yml
image: ghcr.io/tailscale/tailscale:v1.40.0
env:
- name: TS_USERSPACE
  value: "true"
- name: TS_AUTH_KEY 
  valueFrom:
    secretKeyRef:
      key: authKey  
      name: tailscale
- name: TS_AUTH_ONCE
  value: "true"
- name: TS_STATE_DIR
  value: /client/data
- name: TS_ROUTES
  value: "x.x.x.x/x, etc"
- name: TS_EXTRA_ARGS
  value: --accept-routes=false --accept-dns=false --advertise-exit-node=true --advertise-tags=tag:xxx
```

The TS_STATE_DIR is a persistent volume. This is used in a Statefulset.
Updating the `TS_ROUTES` doesn't update the `/client/data/tailscale.state` and the client starts with the old routes.

Is this expected?
Any way to force it to update its profile based on TS_ROUTES?

### OS

Linux

### OS version

GCP's COS

### Tailscale version

1.40.0
