### ISSUE TITLE
Kubernetes healthcheck fails and container shutsdown

### ISSUE THREAD

**Issue by denis-ev** [tailscale/tailscale#8529]
### What is the issue?

Starting Kubernetes tailscale gateway should just stay connected, but it does not.

### Steps to reproduce

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tailscale-gateway
  namespace: vpn
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    serviceAccount:
      name: tailscale

    image:
      repository: ghcr.io/tailscale/tailscale
      tag: v1.44.0
    env:
      TZ: "Europe/Berlin"
      TS_KUBE_SECRET: "tailscale-auth"
      SA_NAME: tailscale
      TS_USERSPACE: "true"
      TS_ROUTES: "${CLUSTER_CIDR},${SERVICE_CIDR}"
      TS_EXTRA_ARGS: "--advertise-exit-node"
      
    envFrom:
      - secretRef:
          name: tailscale-auth

    service:
      main:
        ports:
          http:
            port: &port 45387

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000

    ingress:
      main:
        enabled: false
```

```
Name:             tailscale-gateway-7d47bd85d9-lrgrl
Namespace:        vpn
Priority:         0
Service Account:  tailscale
Node:             k8s-worker-4/10.1.1.94
Start Time:       Tue, 04 Jul 2023 20:56:31 +0800
Labels:           app.kubernetes.io/instance=tailscale-gateway
                  app.kubernetes.io/name=tailscale-gateway
                  pod-template-hash=7d47bd85d9
Annotations:      <none>
Status:           Running
IP:               10.42.6.190
IPs:
  IP:           10.42.6.190
Controlled By:  ReplicaSet/tailscale-gateway-7d47bd85d9
Containers:
  tailscale-gateway:
    Container ID:   containerd://7a00473aad2bf4d96f71ae316ebd8ca5c8ea7dcba3fdf81ad6409a841fc26b0c
    Image:          ghcr.io/tailscale/tailscale:v1.44.0
    Image ID:       ghcr.io/tailscale/tailscale@sha256:a1a18e145f9dd0d67ede7ce88f2049eb5ae0c0706f1cea096147170410c2fb57
    Port:           45387/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Tue, 04 Jul 2023 20:59:41 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 04 Jul 2023 20:57:08 +0800
      Finished:     Tue, 04 Jul 2023 20:59:38 +0800
    Ready:          False
    Restart Count:  1
    Liveness:       tcp-socket :45387 delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      tcp-socket :45387 delay=0s timeout=1s period=10s #success=1 #failure=3
    Startup:        tcp-socket :45387 delay=0s timeout=1s period=5s #success=1 #failure=30
    Environment Variables from:
      tailscale-auth  Secret  Optional: false
    Environment:
      SA_NAME:         tailscale
      TS_EXTRA_ARGS:   --advertise-exit-node
      TS_KUBE_SECRET:  tailscale-auth
      TS_ROUTES:       10.1.1.0/24
      TS_USERSPACE:    true
      TZ:              Europe/Berlin
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9vdd6 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-9vdd6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  3m59s                 default-scheduler  Successfully assigned vpn/tailscale-gateway-7d47bd85d9-lrgrl to k8s-worker-4
  Normal   Pulling    3m51s                 kubelet            Pulling image "ghcr.io/tailscale/tailscale:v1.44.0"
  Normal   Pulled     3m26s                 kubelet            Successfully pulled image "ghcr.io/tailscale/tailscale:v1.44.0" in 25.32753279s (25.327673881s including waiting)
  Normal   Created    3m22s                 kubelet            Created container tailscale-gateway
  Normal   Started    3m20s                 kubelet            Started container tailscale-gateway
  Warning  Unhealthy  97s (x21 over 3m17s)  kubelet            Startup probe failed: dial tcp 10.42.6.190:45387: connect: connection refused
  ```
  
  ```
  2023/07/04 13:04:47 peerapi: serving on http://100.70.215.68:65073
2023/07/04 13:04:47 peerapi: serving on http://[fd7a:115c:a1e0:ab12:4843:cd96:6246:d744]:65073
2023/07/04 13:04:48 magicsock: home is now derp-5 (syd)
2023/07/04 13:04:48 magicsock: adding connection to derp-5 for home-keep-alive
2023/07/04 13:04:48 magicsock: 1 active derp conns: derp-5=cr0s,wr0s
2023/07/04 13:04:48 Switching ipn state Starting -> Running (WantRunning=true, nm=true)
2023/07/04 13:04:48 derphttp.Client.Connect: connecting to derp-5 (syd)
2023/07/04 13:04:48 control: NetInfo: NetInfo{varies=true hairpin=false ipv6=false ipv6os=true udp=true icmpv4=false derp=#5 portmap= link=""}
2023/07/04 13:04:48 magicsock: endpoints changed: 157.211.100.104:6654 (stun), 10.42.6.190:36404 (local)
2023/07/04 13:04:48 magicsock: derp-5 connected; connGen=1
2023/07/04 13:04:48 health("overall"): ok
boot: 2023/07/04 13:04:48 Startup complete, waiting for shutdown signal
boot: 2023/07/04 13:07:13 Received SIGTERM from container runtime, shutting down tailscaled
2023/07/04 13:07:13 tailscaled got signal terminated; shutting down
2023/07/04 13:07:13 control: client.Shutdown()
2023/07/04 13:07:13 control: client.Shutdown: inSendStatus=0
boot: 2023/07/04 13:07:13 failed to read from tailscaled: EOF
2023/07/04 13:07:13 control: mapRoutine: quit
2023/07/04 13:07:13 control: Client.Shutdown done.
2023/07/04 13:07:13 magicsock: closing connection to derp-5 (conn-close), age 2m25s
2023/07/04 13:07:13 magicsock: 0 active derp conns
2023/07/04 13:07:13 flushing log.
2023/07/04 13:07:13 logger closing down
  ```

### OS

Other

### Tailscale version

1.44.0
