### ISSUE TITLE
Running multiple replicas of k8s-operator breaks tailscale's kube state

### ISSUE THREAD

**Issue by irbekrm** [tailscale/tailscale#8580]
### What is the issue?

Tailscale ks8-operator does not use [leader election](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/leaderelection) so multiple operator pods existing in a cluster (either because user decided to scale it up for whatever reason or perhaps two replicas exist for a period of time during upgrade) can result in a weird behaviour and duplicate resource creation.
Further it might be difficult for a user to understand how to recover from this state.

### Steps to reproduce

- deploy k8s-operator as per [instructions](https://tailscale.com/kb/1236/kubernetes-operator/)
- scale the operator deployment to 2 replicas `kubectl scale --replicas=2 deploy/operator -n tailscale --timeout=30s`
- create some `Service` to be exposed via Tailscale:
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  labels:
    app: foobar
  name: foobar
spec:
  ports:
  - name: foobar
    port: 123
    protocol: TCP
    targetPort: 321
  loadBalancerClass: tailscale
  selector:
    app: foobar
  type: LoadBalancer
EOF
```
- observe 2 `StatefulSet`s, 2 `Secret`s and 2 headless `Service`s for foobar `Service` in `tailscale` namespace:
```
k get  sts,secret,service -n tailscale  --selector=tailscale.com/parent-resource=foobar
```
- observe various errors related to duplicate resources in the operator logs

To recover, users would have to scale down and also manually delete the duplicated resources as the operator won't be able to clean them up.

### Tailscale version

v1.43
