### ISSUE TITLE
DNS Resolution Issue with Tailscale Funnel and Proxy on Raspberry Pi with Docker and Tailscale User Space Networking

### ISSUE THREAD

**Issue by byteshiva** [tailscale/tailscale#8680]
### What is the issue?

**Description:**
After following the provided steps to set up a website using Tailscale on an ARM Raspberry Pi with user space networking and funneling enabled, there is an issue with DNS resolution. The website should be accessible outside of the Tailnet network via a custom hostname, but it fails to resolve after waiting for 10 to 15 minutes following Step 7 and Step 8.

### Steps to reproduce

**Steps to Reproduce:**
1. Run the Docker container :
   ```
   docker run -it python /bin/bash
   ```

2. Inside the container instance, Install "tailscale":
   ```
   curl -fsSL https://tailscale.com/install.sh | sh
   ```

3. Run tailscaled with user-space networking:
   ```
   sudo tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &
   ```

4. Run tailscale with custom hostname:
   ```
   sudo tailscale up --hostname=container_raspberrypi
   ```

5. Create a folder /tmp/public/ and touch index.html, echo "hello" >> index.html:
   ```
   mkdir -p /tmp/public
   echo "hello" >> /tmp/public/index.html
   ```

6. Run a Python HTTP server to serve the content:
   ```
   python3 -m http.server
   ```

7. Add proxy to route 443 to port 8000:
   ```
     tailscale serve https / http://127.0.0.1:8000

   ```

8. Enable funnel on port 443:
   ```
   tailscale funnel 443 on
   ```

9. Wait for 10 to 15 minutes and attempt to access the website using the custom hostname outside of the Tailnet network.

**Expected Result:**
The website content from index.html should be displayed when accessing it via the custom hostname outside of the Tailnet network.

**Actual Result:**
After waiting for 10 to 15 minutes following Step 7 and Step 8, the website fails to resolve when attempting to access it using the custom hostname outside of the Tailnet network.

### Are there any recent changes that introduced the issue?

**Additional Information:**
- Raspberry Pi model: Raspberrypi 4
- Operating System: [Linux 6.1.21-v8+  aarch64 GNU/Linux]
- Tailscale version: [1.44.2]
- Docker version: [Docker version 24.0.4, build 3713ee1]
- Python version: [Python 3.11.2]

### OS

Linux

### OS version

Linux 6.1.21 aarch64 GNU/Linux

### Tailscale version

1.44.2

### Bug report

BUG-2384b5e8fde9161aa0832fe10738f9017ec613df6b74c8e45ad9e990dad25894-20230722075927Z-f06502bdac90b707

**Comment by jimmybrancaccio** [comment]
A customer ran into this issue today (32296). Initially I was able to replicate it using a DigitalOcean droplet with Docker. I attempted to setup a Tailscale container that would funnel to a Portainer container. Initially I was able to reach Portainer when I was connected to my tailnet but couldn't reach it when I wasn't connected - obviously not the expected behavior.

I then tried starting up Tailscale with the following environment variable set - `TS_ACCEPT_DNS=true` (in my `docker-compose.yml`) and everything started working as I expected.

Of note, if using `tailscale` on the command line you can do `tailscale up --accept-dns=true`.

**Comment by 5ouma** [comment]
I'm the same. I use Tailscale image with Docker Compose, and can't connect to the address. (I can connect with Tailscale VPN.)
If I up this container without Tailscale and `tailscale funnel --bg 3001` on my host machine, I can connect from all devices without Tailscale VPN.

- compose.yml
```yaml
services:
  my-server:
    # ...
    depends_on:
      - tailscale
    network_mode: service:tailscale

# ...

  tailscale:
    container_name: tailscale
    hostname: my-hostname
    image: tailscale/tailscale:v1.62.1
    env_file: [".env"]
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/tailscale.json
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - ./config/tailscale.json:/config/tailscale.json:ro
    cap_add:
      - net_admin
      - sys_module
    restart: always

volumes:
  tailscale-state:
```

- tailscale.json
```jsonc
{
  "TCP": { "443": { "HTTPS": true } },
  "Web": {
    "${TS_CERT_DOMAIN}:443": {
      "Handlers": { "/": { "Proxy": "http://127.0.0.1:3001" } }
    }
  },
  "AllowFunnel": { "${TS_CERT_DOMAIN}:443": true }
}

```
