### ISSUE TITLE
portmapping not detected for BT SmartHub 2

### ISSUE THREAD

**Issue by ccalby** [tailscale/tailscale#8748]
### What is the issue?

Attempting to access Tailscale remotely. Connection being forced to relay through DERP.

ISP: British Telecom (BT)

Attempted:
1) On mobile carrier 5G
2) Another remote home network

Expected to see direct connections on both however are always relaying.

DEBUG:
```
/ # tailscale status
100.xxx.xxx.xxx  tailscale-server            me@      linux   -
100.xxx.xxx.xxx   my-mobile-device     me@      android active; relay "par", tx 60124 rx 17828
100.xxx.xxx.xxx  remote-desktop      name2@ windows idle, tx 124 rx 468
```
```
/ # tailscale ping 100.xxx.xxx.xxx
pong from my-mobile-device (100.xxx.xxx.xxx)) via DERP(lhr) in 335ms
pong from my-mobile-device (100.xxx.xxx.xxx) via DERP(par) in 129ms
pong from my-mobile-device (100.xxx.xxx.xxx) via DERP(lhr) in 135ms
pong from my-mobile-device (100.xxx.xxx.xxx) via DERP(lhr) in 100ms
pong from my-mobile-device (100.xxx.xxx.xxx) via DERP(par) in 211ms
```

Note PortMapping is blank in the debug below.
```
/ # tailscale netcheck
Report:
        * UDP: true
        * IPv4: yes, xxx.xxx.xxx.xxx:37791
        * IPv6: no, but OS has support
        * MappingVariesByDestIP: false
        * HairPinning: false
        * PortMapping: 
        * Nearest DERP: London
        * DERP latency:
                - lhr: 13.5ms  (London)
                - par: 20ms    (Paris)
                - ams: 22.6ms  (Amsterdam)
                - fra: 38ms    (Frankfurt)
                - mad: 42.6ms  (Madrid)
                - waw: 50.6ms  (Warsaw)
                - tor: 114.2ms (Toronto)
                - ord: 114.2ms (Chicago)
                - nyc: 114.2ms (New York City)
                - mia: 114.3ms (Miami)
                - den: 121.9ms (Denver)
                - dfw: 124.4ms (Dallas)
                - dbi: 138ms   (Dubai)
                - lax: 145.5ms (Los Angeles)
                - sfo: 148.8ms (San Francisco)
                - sea: 152.1ms (Seattle)
                - blr: 173.9ms (Bangalore)
                - jnb: 182.9ms (Johannesburg)
                - sao: 195.9ms (São Paulo)
                - nai: 196.3ms (Nairobi)
                - hnl: 201.8ms (Honolulu)
                - hkg: 228.1ms (Hong Kong)
                - sin:         (Singapore)
                - syd:         (Sydney)
                - tok:         (Tokyo)
/ # 
```
```
/ # tailscale debug portmap
gw=192.168.1.254; self=192.168.1.xxx
Probe: {PCP:false PMP:false UPnP:false}
no portmapping services available
/ #
```

### Steps to reproduce

Router: BT SmartHub 2.
Firmware: v0.39.01.04077-BT

### OS

Linux

### OS version

TrueNAS Scale Latest

### Tailscale version

1.44.0

### Other software

Tailscale is running on TrueNAS Scale but should not interfere. Have checked and re-checked config.

### Bug report

BUG-678a0272ffc2beb9f1b84d464e489835d299bab6a0de7d78f53f0b25ee7e9e3e-20230730145720Z-94e37c51adbb29dc
