### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [tailscale/tailscale#8987]
### What is the issue?

Looks like Java 17 is now needed, per https://monitor.f-droid.org/builds/log/com.tailscale.ipn/176#site-footer

Ok, let's add that... oh... Makefile has been redone drastically... let me try...
```
  - versionName: 1.48.0-t77c732357-g388b71affe8
    versionCode: 176
    commit: fcab2211ef57398f0042b422178ab796e258177c
    subdir: android
    sudo:
      - apt-get update
      - apt-get install -y -t bullseye-backports golang-go
      - apt-get install -y build-essential
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
    gradle:
      - fdroid
    srclibs:
      - tailscale-go@e6ce5b50036022c91783161890eabecfddc5ae79
    prebuild:
      - sdkmanager 'platforms;android-31' 'platform-tools' 'build-tools;33.0.2'
      - sed -i -e '/rm -rf/,+2d' -e 's!$(ANDROID_HOME)/cmdline-tools/latest/bin/sdkmanager!sdkmanager!g' -e 's/list_installed/list/' ../Makefile
    build:
      - export TOOLCHAINREV=$(go run tailscale.com/cmd/printdep --go)
      - export TOOLCHAINDIR=${HOME}/.cache/tailscale-android-go-$TOOLCHAINREV
      - pushd $$tailscale-go$$
      - git checkout $TOOLCHAINREV
      - pushd src
      - ./make.bash
      - popd
      - popd
      - mkdir -p $TOOLCHAINDIR
      - ln -s $$tailscale-go$$ $TOOLCHAINDIR/go
      - export PATH=$TOOLCHAINDIR/go/bin:$PATH
      - ANDROID_NDK_ROOT=$$NDK$$ make -C .. tailscale-fdroid.apk
    ndk: r23b
```
umm, looks good but
```
...
+ make -C .. tailscale-fdroid.apk
make: Entering directory '/home/vagrant/build/com.tailscale.ipn'
mkdir -p android/libs
go: downloading go4.org/mem v0.0.0-20220726221520-4f986261bf13
go: downloading github.com/google/uuid v1.3.0
go: downloading golang.org/x/mod v0.11.0
go: downloading golang.org/x/crypto v0.11.0
go: downloading golang.org/x/exp v0.0.0-20230725093048-515e97ebf090
go: downloading go4.org/netipx v0.0.0-20230728180743-ad4cb58a6516
go: downloading golang.org/x/sys v0.10.0
go run gioui.org/cmd/gogio \
        -ldflags "-X tailscale.com/version.longStamp=1.48.0-t77c732357-g388b71affe8 -X tailscale.com/version.shortStamp=1.48.0 -X tailscale.com/version.gitCommitStamp=77c732357 -X tailscale.com/version.extraGitCommitStamp=fcab2211ef57398f0042b422178ab796e258177c-dirty" \
        -buildmode archive -target android -appid com.tailscale.ipn -tags novulkan,tailscale_go -o android/libs/ipn.aar github.com/tailscale/tailscale-android/cmd/tailscale
go: downloading gioui.org/cmd v0.0.0-20210925100615-41f3a7e74ee6
go: downloading gioui.org v0.0.0-20230206180804-32c6a9b10d0b
go: downloading github.com/akavel/rsrc v0.10.1
go: downloading golang.org/x/image v0.7.0
go: downloading golang.org/x/sync v0.2.0
go: downloading golang.org/x/tools v0.9.1
go: downloading golang.org/x/text v0.11.0
gogio: go build -ldflags=-w -s -X tailscale.com/version.longStamp=1.48.0-t77c732357-g388b71affe8 -X tailscale.com/version.shortStamp=1.48.0 -X tailscale.com/version.gitCommitStamp=77c732357 -X tailscale.com/version.extraGitCommitStamp=fcab2211ef57398f0042b422178ab796e258177c-dirty -X gioui.org/app/internal/log.appID=com.tailscale.ipn -buildmode=c-shared -tags novulkan,tailscale_go -o /tmp/gogio-814326569/jni/armeabi-v7a/libgio.so github.com/tailscale/tailscale-android/cmd/tailscale failed: ../../go/pkg/mod/tailscale.com@v1.48.0/wgengine/magicsock/endpoint_tracker.go:8:2: package slices is not in GOROOT (/usr/lib/go-1.19/src/slices)

exit status 1
```

Which `make`  command should I use exactly? Why is Go failing? full log: 
[com.tailscale.ipn_176.log.gz](https://github.com/tailscale/tailscale/files/12397900/com.tailscale.ipn_176.log.gz)

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/8cb6d1fcc173478eee95ca67254ccff952959a89
