### ISSUE TITLE
Docker-compose: Cannot reach other nodes, no entries in routing table

### ISSUE THREAD

**Issue by HexPandaa** [tailscale/tailscale#9064]
### What is the issue?

I tried to set up a tailscale node on my server via docker-compose.
However I see no routes added so `tailscale ping 100.64.0.x` works from withing the container, but `ping 100.64.0.x` doesn't.
I'm not trying to advertise more routes on my remote node, only itseft.
I can ping the server / container via my laptop, but it doesn't work the other way around.

It seems like no route is added to the host / container to the other nodes.

```yml
services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscale/var_lib:/var/lib/tailscale
    environment:
      - TS_AUTHKEY=<REDACTED>
      - TS_HOSTNAME=<REDACTED>
      - TS_SOCKET=/tmp/tailscaled.sock
      - TS_STATE_DIR=/var/lib/tailscale
```

```bash
> docker compose exec tailscale ip rule
0:      from all lookup local
5210:   from all fwmark 0x80000/0xff0000 lookup main
5230:   from all fwmark 0x80000/0xff0000 lookup default
5250:   from all fwmark 0x80000/0xff0000 unreachable
5270:   from all lookup 52
32766:  from all lookup main
32767:  from all lookup default
> docker compose exec tailscale ip route show table 52
Error: ipv4: FIB table does not exist.
Dump terminated

# Same thing on the host
```

### Steps to reproduce

1. Start the tailscale container
2. try to ping the container from another node: it works
3. try to ping another node from the container or the host: it doesn't work

### Are there any recent changes that introduced the issue?

Not to my knowledge, I found no one with the same problem.

### OS

Linux, Other

### OS version

Debian 11, Docker 24.0.5

### Tailscale version

1.48.1
