### ISSUE TITLE
tailscale-operator ingress can't hit intra-cluster service

### ISSUE THREAD

**Issue by jtschelling** [tailscale/tailscale#9141]
### What is the issue?

i'm running the tailscale-operator on a kubernetes cluster, and attempting to use the new ingressclass introduced recently. here's my example manifest i'm using to test:

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: tailscale-test
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: nginx-service
                port:
                  name: web-service
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: tailscale-test
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - name: web-service
      protocol: TCP
      port: 80
      targetPort: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: tailscale-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
          name: web
```

the ingress comes up fine and i get `tailscale-test-nginx-ingress-ingress` machine added to my tailnet in the admin console. I can run `tailscale ping $INGRESSTAILNETIP` fine, here's the output

```
pong from tailscale-test-nginx-ingress-ingress ($INGRESSTAILNETIP) via DERP(ord) in 12ms
pong from tailscale-test-nginx-ingress-ingress ($INGRESSTAILNETIP) via DERP(ord) in 16ms
pong from tailscale-test-nginx-ingress-ingress ($INGRESSTAILNETIP) via DERP(ord) in 27ms
pong from tailscale-test-nginx-ingress-ingress ($INGRESSTAILNETIP) via $LANIP:58208 in 9ms
```

when i try to `curl http://$INGRESSTAILNETIP` i get:

```
curl: (7) Failed to connect to $INGRESSTAILNETIP port 80 after 37 ms: Couldn't connect to server
```

there's a pod `ts-nginx-ingress-58pz9-0` that gets created in the `tailscale` namespace that the operator is running in. when i look at the logs in that pod after running the curl command i see:

```
tailscale 2023/08/29 20:35:39 Accept: TCP{$MYLAPTOPTAILNETIP:57929 > $INGRESSTAILNETIP:80} 64 tcp ok
tailscale 2023/08/29 20:35:39 [unexpected] localbackend: got TCP conn without TCP config for port 80; from
100.106.218.33:57929
tailscale 2023/08/29 20:35:39 netstack: could not connect to local server at 127.0.0.1:80: dial tcp 127.0.0
.1:80: connect: connection refused
```

I wondered if it was something with the pod being unable to hit the namespace the test conatiner was running in so i used [netshoot](https://github.com/nicolaka/netshoot) to run a debug container in the same pod as the `ts-nginx-ingress-58pz9-0`, but i can curl the nginx service fine from there:

```
 ts-nginx-ingress-58pz9-0  ~  curl nginx-service.tailscale-test.svc.cluster.local
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
.......
```

i'm wondering if its something with iptables? i'm using a debian based distro on a raspberry pi (ARM) called dietpi. i see entries in my iptables rules for tailscale but not quite sure what i'm looking for, can provide more info if i get some guidance.

### OS

Linux, macOS

### Tailscale version

unstable-v1.49.121

### Other software

i'm using cilium for my cni. i'm monitoring with hubble, i can see the incoming connection from my laptop on the tailnet to the pod that gets created by the ingress in the `tailscale` namespace, but there's no outgoing connection to my nginx service so i don't think cilium is blocking that outgoing connection.

### Bug report

BUG-4aeb98ad042df268512fdfef314601e58f045bf66424dcabadb2e2e87f0cbba2-20230829205453Z-20c4680ff940f803
