### ISSUE TITLE
CI: linux-amd64 "bench all" takes longer than tests

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#9182]
Our CI does:

```yaml
    - name: bench all
      run: PATH=$PWD/tool:$PATH /tmp/testwrapper ./... ${{matrix.buildflags}} -bench=. -benchtime=1x -run=^$ 
      env:
        GOARCH: ${{ matrix.goarch }}
```

But on `test (amd64, -race)` that ends up taking longer than the "test all" step.

The point of that "bench all" with "1x" is basically to make sure things compile & barely run.

It shouldn't be running any tests or taking barely any time at all.

I think something is broken. Is `testwrapper` not passing `-run=^$` down?

/cc @maisem @raggi
