### ISSUE TITLE
Resolve pod/service names via MagicDNS with Kubernetes subnet router

### ISSUE THREAD

**Issue by bashirsouid** [tailscale/tailscale#9300]
### What is the issue?

Posting as a Github issue instead of a support ticket to hopefully be more discoverable to beginners who are likely going to encounter same question.

I setup a kubernetes cluster for testing/learning (so I don't mind recreating if settings were initially wrong) and want to be able to access exposed kubernetes services by DNS instead of just by IP address over the tailscale VPN.

I followed the guide for setting up a subnet router for kubernetes and that worked fine: https://github.com/tailscale/tailscale/blob/main/docs/k8s/README.md#subnet-router

I can access the service by IP address on other tailscale nodes. But as a noob, I don't see any way to get a DNS reference for the service with magic DNS. I tried `<svc_name>.tailnet-domain.ts.net` or `<svc_name>.<subnet-router-name>.tailnet-domain.ts.net` and I looked in admin console and it lists no services discovered for the section `Live services running on this machine.`

Is what I am trying to setup possible? Or am I missing some steps beyond the guide?

### Steps to reproduce

1. Setup a kubernetes cluster
2. Setup a subnet-router via guide here: https://github.com/tailscale/tailscale/blob/main/docs/k8s/README.md#subnet-router
3. Approve subnet in admin console
4. Curl web service from IP address like in guide's demo
5. Attempt to curl web service with service name at `<svc_name>.tailnet-domain.ts.net` praying MagicDNS is truly magical.

### Are there any recent changes that introduced the issue?

No

### OS

Linux

### OS version

Debian 11

### Tailscale version

1.48.1

### Other software

N/A

### Bug report

BUG-809d32514adf0b93f7fb958c811600d8cf8e1862ebe6df25e84d515b9de70250-20230908040538Z-3f3e3354f28fb100

**Comment by bashirsouid** [comment]
Here is the Kubernetes deployment yaml definition:

```
apiVersion: v1
      kind: Pod
      metadata:
        name: tailscale
        namespace: tailscale
        labels:
          app: tailscale
      spec:
        serviceAccountName: tailscale
        containers:
        - name: tailscale
          imagePullPolicy: Always
          image: "ghcr.io/tailscale/tailscale:latest"
          env:
          - name: TS_KUBE_SECRET
            value: "tailscale-auth"
          - name: TS_USERSPACE
            value: "true"
          - name: TS_ACCEPT_DNS
            value: "true"
          - name: TS_AUTHKEY
            valueFrom:
              secretKeyRef:
                name: tailscale-auth
                key: TS_AUTHKEY
                optional: true
          - name: TS_ROUTES
            value: "10.20.0.0/16,10.42.0.0/16,10.43.0.0/16"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          restartPolicy: Always
          terminationGracePeriodSeconds: 60
```

Here is a sample hello-world I am trying to access:

```
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hello-world
        namespace: canaries
      spec:
        selector:
          matchLabels:
            app: hello-world
        replicas: 1
        template:
          metadata:
            labels:
              app: hello-world
          spec:
            containers:
            - name: hello-world
              image: karthequian/helloworld:latest
              ports:
              - containerPort: 80
```

```
      apiVersion: v1
      kind: Service
      metadata:
        name: hello-world
        namespace: canaries
        labels:
          app: hello-world
      spec:
        type: ClusterIP
        ports:
          - targetPort: 80
            port: 80
        selector:
            app: hello-world
```
