### ISSUE TITLE
Docker not persisting login

### ISSUE THREAD

**Issue by pravardhanreddy** [tailscale/tailscale#9615]
### What is the issue?

I am using the following docker compose file
```
version: '3.3'
services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    hostname: docker-houston
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - './data:/var/lib'
      - '/dev/net/tun:/dev/net/tun'
    environment:
      - 'TS_EXTRA_ARGS=--advertise-exit-node'
      - 'TS_ROUTES=10.11.0.0/24'
      - 'TS_STATE_DIR=/var/lib'
    network_mode: host
    restart: unless-stopped
```
![image](https://github.com/tailscale/tailscale/assets/30177846/3f9b7190-b21c-4db5-9d65-786b05f7f9aa)

This used to work perfectly fine until about a week ago. I had key expiry disabled and added path for `/var/lib` as well. Recently all my machines went offline and when I checked the logs they were all asking for authentication and providing URL to authenticate. 

I thought this might be a one off case so I just re authenticated. I wanted to test if it still breaks so I shutdown the container and brought it back up. It was asking for authentication again. I am not able to run it in unattended mode.

### Steps to reproduce

1. Use the above docker compose file to start the container
2. Authenticate with the provided URL in the logs
3. Restart the container

### Are there any recent changes that introduced the issue?

I use Watchtower to keep my container images up to date. All my machines dropped off the tailscale network on Sep 25th. Must have been some change to the image/repo that caused this.

### OS

Linux

### OS version

Debian 12 (Docker)

### Tailscale version

v1.50.0-ta30a7198b
