### ISSUE TITLE
Split DNS resolution failed when using SOCKS5 on Docker

### ISSUE THREAD

**Issue by SushiFu** [tailscale/tailscale#9619]
### What is the issue?

I'm trying to use Tailscale inside Docker with userspace and SOCKS5 proxy.
I need multiple Tailscale client at the same time hence the userspace + proxy usage.
I'm using socks5h to forward DNS queries to Tailscale.

When trying to curl a domain setup on Tailscale with Split DNS (Nameserver is private and behind a route declared on the Tailnet) DNS resolution is not working.

`Tailscale Container`:
```
2023-10-02T10:30:54.628115250Z 2023/10/02 10:30:54 socks5: client connection failed: lookup <CUSTOM_PRIVATE_DOMAIN_WITH_SPLIT_DNS> on 127.0.0.11:53: no such host
```
`curl`:
```
* Uses proxy env variable ALL_PROXY == 'socks5h://localhost:1055/'
*   Trying 127.0.0.1:1055...
* SOCKS5 connect to schema.prod.data.cyber.stoik.tools:443 (remotely resolved)
* connection to proxy closed
* Closing connection 0
curl: (97) connection to proxy closed
```

It looks like DNS traffic coming through the SOCKS5 proxy is resolved with Docker default DNS and not `100.100.100.100`

### Steps to reproduce

`docker-compose.yml`
```
      tailscale:
        image: tailscale/tailscale:stable
        ports:
          - '1055:1055'
        env:
          TS_HOSTNAME: 'actions-runner-${{ github.run_id }}'
          TS_AUTHKEY: '${{ secrets.TAILSCALE_OAUTH_SECRET }}?preauthorized=true&ephemeral=true'
          TS_USERSPACE: 'true'
          TS_ACCEPT_DNS: 'true'
          TS_SOCKS5_SERVER: ':1055'
          TS_OUTBOUND_HTTP_PROXY_LISTEN: ':1055'
          TS_EXTRA_ARGS: '--advertise-tags=tag:something'
```

```
export ALL_PROXY=socks5h://localhost:1055/
curl -fsSL --proxy-insecure -v https://<CUSTOM_PRIVATE_DOMAIN_WITH_SPLIT_DNS/
```

### OS

Linux

### OS version

22.04 LTS

### Tailscale version

tailscale/tailscale:v1.50.0

### Other software

Docker: `24.0.6`

### Bug report

BUG-f8ff36fe09565e960ca5e72a25f6e9f8da550947b69b2b36fd1b306fb6bddf96-20231002110108Z-57a021ea8d4f4395
