### ISSUE TITLE
Operator: Annotated service not persisting ip rules

### ISSUE THREAD

**Issue by bkonicek** [tailscale/tailscale#9763]
### What is the issue?

I installed Tailscale operator following the documentation, and it successfully registered with my Tailnet.

I added the `tailscale.com/expose: "true"` annotation to a random service running in my cluster, and saw it register with tailnet. However, I could not connect to it, and when I checked my tailnet again, I saw it was disconnected.

I confirmed that I can ping other non-kubernetes hosts in my tailnet, and I can also ping the tailscale-operator.

### Steps to reproduce

1. Install tailscale-operator following the [instructions ](https://tailscale.com/kb/1236/kubernetes-operator/#setting-up-the-kubernetes-operator)
2. Create a pod
```
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
```
3. Expose the pod 
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    role: myrole
  name: static-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    role: myrole
```

Exposed service logs: https://gist.github.com/bkonicek/22a285af004fae081cc3e0639cc7e1df
Operator logs: https://gist.github.com/bkonicek/fabb9babb34f9b8c31ea4b540bee4f1c

### Are there any recent changes that introduced the issue?

No - this was a brand new installation

### OS

Other

### OS version

Kubernetes 1.27.2

### Tailscale version

1.51.117
